import { KnowledgeEntity } from "../../types";

export const HeadacheSymptom: KnowledgeEntity = {
  id: "S0003",
  slug: "headache",
  entityType: "symptom",
  editorialStatus: "published",
  legacyVerificationStatus: "verified-published",
  versionInfo: {
    version: "1.2.0",
    created: "2026-06-30T12:00:00Z",
    updated: "2026-09-23T00:00:00Z",
    reviewed: "2026-09-23T00:00:00Z",
  },
  title: {
    en: "Headache: Common Causes, What May Help, and When to Get Urgent Care",
    hi: "सिरदर्द: सामान्य कारण, क्या मदद कर सकता है और कब तत्काल देखभाल लें",
    gu: "માથાનો દુખાવો: સામાન્ય કારણો, શું મદદ કરી શકે અને ક્યારે તાત્કાલિક સારવાર લેવી",
    mr: "डोकेदुखी: सामान्य कारणे, काय मदत करू शकते आणि तातडीची मदत कधी घ्यावी",
    es: "Dolor de Cabeza: Causas Comunes, Qué Puede Ayudar y Cuándo Buscar Atención Urgente",
    ar: "الصداع: الأسباب الشائعة، ما الذي قد يساعد، ومتى تطلب رعاية عاجلة",
  },
  summary: {
    en: "Headaches are common and often linked with stress, dehydration, missed meals, eye strain, sleep changes, illness, or a primary headache condition such as migraine. A new pattern, a sudden severe headache, or headache with neurological or infection symptoms needs timely medical assessment.",
    hi: "सिरदर्द आम है और तनाव, पानी की कमी, भोजन छूटने, नींद में बदलाव या माइग्रेन से जुड़ा हो सकता है।",
    gu: "માથાનો દુખાવો સામાન્ય છે અને તણાવ, પાણીની કમી, ભોજન છૂટવું અથવા ઊંઘમાં ફેરફાર સાથે જોડાયેલો હોઈ શકે છે.",
    mr: "डोकेदुखी सामान्य आहे आणि तणाव, पाण्याची कमतरता, जेवण चुकणे किंवा झोपेतील बदलांशी संबंधित असू शकते.",
    es: "Los dolores de cabeza son comunes y pueden relacionarse con estrés, deshidratación, comidas saltadas o cambios de sueño.",
    ar: "الصداع شائع وقد يرتبط بالتوتر أو الجفاف أو تفويت الوجبات أو تغيرات النوم.",
  },
  content: {
    definition:
      "A headache is pain or pressure in the head, scalp, face, or upper neck. It may feel tight, heavy, throbbing, sharp, or one-sided. Most headaches are not caused by a dangerous problem, but the pattern and any accompanying symptoms matter.",
    clinicalMeaning:
      "Headache is a symptom rather than one diagnosis. Common primary patterns include tension-type headache and migraine; other headaches can accompany a viral illness, dehydration, eye strain, neck or jaw tension, medicines, or changes in caffeine, sleep, meals, or hormones. A clinician is especially interested in whether this is new, different, sudden, worsening, and whether there are neurological, eye, injury, or infection symptoms.",
    commonCauses: [
      "Stress, worry, prolonged screen or close work, jaw clenching, neck or shoulder tension, or poor posture",
      "Not drinking enough, skipping or delaying meals, alcohol, heat, a viral illness, or changes in caffeine use",
      "Sleep loss, oversleeping, shift changes, travel, or a change in routine",
      "Migraine or tension-type headache; some people notice a pattern around periods, menopause, or particular sensory triggers",
      "Using pain medicine too often, a new medicine or supplement, eyesight problems, or another health condition",
    ],
    differentialDiagnosis:
      "A useful assessment starts with the story: where the pain is, how quickly it began, how long it lasts, its severity, what comes with it, your usual pattern, recent illness or injury, medicines and pain-reliever use, sleep, meals, fluids, caffeine, vision, stress, and family history. Most people do not need a scan for a typical stable pattern, but urgent assessment is needed when warning signs suggest a secondary cause.",
    redFlags: [
      "A sudden, explosive or 'worst ever' headache, especially if it reaches maximum intensity quickly: seek emergency care now",
      "Headache with new trouble speaking, confusion, fainting, seizure, loss of vision, loss of balance, or new weakness or numbness of the face, arm, or leg: seek emergency care now",
      "Headache with high fever, stiff neck, a non-fading rash, severe vomiting, marked drowsiness, or sensitivity to light: seek emergency care now",
      "A severe headache after a head injury, or a new severe headache during pregnancy or soon after birth: seek urgent medical assessment",
      "A new headache after age 50, a clearly changing pattern, headache with jaw pain while eating or scalp tenderness, cancer or immune suppression, or frequent headaches with no clear cause: arrange prompt clinical advice",
    ],
    lifestyleAdvice:
      "For a familiar mild headache, start gently: drink water, eat a regular meal if you have missed one, rest your eyes and neck from close work, try a calm low-light break, and notice whether sleep, stress, heat, alcohol, caffeine, or a period of sustained screen use is part of the pattern. A short diary can record timing, location, intensity, associated symptoms, meals, fluids, sleep, stress, cycle where relevant, medicines, and what helped. Avoid taking pain relievers more often or for longer than the label or a clinician advises, because frequent use can itself perpetuate headaches.",
    references: ["CIT-0125", "CIT-0126", "CIT-0023"],
    claimCitations: [
      { claimId: "S0003-DEFINITION-AND-PATTERNS", passage: "definition; clinicalMeaning; commonCauses; differentialDiagnosis", citationIds: ["CIT-0125", "CIT-0126"] },
      { claimId: "S0003-CARE-SEEKING-AND-SUPPORT", passage: "redFlags; lifestyleAdvice", citationIds: ["CIT-0125", "CIT-0126"] },
      { claimId: "S0003-HOMEOPATHY-BOUNDARY", passage: "FAQ: can homeopathy treat headache", citationIds: ["CIT-0023"] },
    ],
    faqs: [
      { question: "What is the first useful thing to notice about a headache?", answer: "Notice when it started, how quickly it came on, where it is, how severe it is, what you were doing beforehand, and what symptoms come with it. Over a few attacks, a diary can also include sleep, meals, fluids, caffeine, stress, periods where relevant, screens, medicines, and what helped. A sudden severe headache or one with neurological or infection symptoms is not a diary situation—seek urgent care." },
      { question: "Can dehydration, missed meals, or screens cause a headache?", answer: "They can contribute for some people. Not enough fluid, a delayed meal, prolonged close work, eye strain, neck tension, or a change in caffeine can all be part of a pattern. The goal is not to blame yourself: regular fluids, meals, visual breaks, and a more comfortable work setup are simple things to try for a familiar mild headache." },
      { question: "How do migraine and tension-type headache differ?", answer: "Tension-type headache often feels like pressure or tightness on both sides of the head and may be linked with neck or shoulder tension. Migraine commonly causes more intense, often throbbing pain and may come with nausea or sensitivity to light, sound, or activity. People can have more than one pattern, so a clinician can help if attacks are frequent, disabling, or changing." },
      { question: "Can taking painkillers too often make headaches worse?", answer: "It can. Frequent use of pain-relief medicines can contribute to a recurring headache pattern for some people. Do not suddenly stop a prescribed medicine on your own; discuss the pattern with a pharmacist or clinician, who can advise on safer limits and whether another plan is needed." },
      { question: "Can homeopathy treat headache?", answer: "Reliable clinical evidence has not established homeopathy as a treatment for recurrent headache or its underlying causes. It should not replace assessment for sudden severe headache, meningitis symptoms, stroke-like symptoms, head injury, eye symptoms, medication overuse, migraine, or any other urgent warning sign." },
    ],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" },
  reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" },
  reviewerRole: "Program-owner final authorization",
  lastClinicalReview: "2026-09-23",
  nextClinicalReview: "2027-09-23",
  referencesUpdated: "2026-09-23",
  clinicalChangesSinceLastRevision: "Rewrote the topic in plain language; added safer care-seeking boundaries, practical trigger tracking, question-led FAQs, and an explicit evidence boundary for homeopathy.",
  reviewStatus: "owner-authorized-source-bound",
  citationHealth: "complete",
  contentCompleteness: 100,
  graphCompleteness: 100,
  evidenceLevel: "Consensus-Guidance",
  evidenceProfile: {
    evidenceStrength: "moderate", sourceQuality: "authoritative", classicalSource: false, modernSource: true, clinicalConfidence: 0.9, editorialConfidence: 0.95, citationCompleteness: 1,
    lastReviewedAt: "2026-09-23", reviewIntervalDays: 365, nextReviewDueAt: "2027-09-23", reviewExpiryPolicy: "flag-only",
    rationale: "Patient-facing headache information, diary support, and care-seeking boundaries are mapped to current NHS and NIH MedlinePlus public clinical guidance.", methodologyVersion: "knowledge-authority-led-v1",
  },
  tags: ["Headache", "Head Pain", "Tension Headache", "Migraine", "Headache Diary", "Cephalgia"],
  canonicalUrl: "https://homeo.healthcare/knowledge/symptoms/headache",
  readingTimeMinutes: 6,
  audience: "patient",
  license: "CC BY-NC-ND 4.0",
  changeLog: ["1.0.0: Initial Headache symptom profile.", "1.2.0: Added patient-first headache guidance, source-bound care-seeking boundaries, question-led FAQs, and visual guide."],
  clinicalPearl: "A headache diary is most useful when it captures the whole pattern—not only the pain, but timing, warning signs, daily context, and how much the headache changes life.",
  quickFacts: {
    "What it can feel like": "Pressure, tightness, throbbing, sharp pain, or pain in the head, face, or upper neck",
    "Common contributors": "Stress, sleep or meal changes, fluids, caffeine, screen or neck strain, illness, and migraine",
    "First useful step": "For a familiar mild headache, hydrate, eat regularly, take a visual break, and note the pattern",
    "Get urgent help": "For sudden severe pain, neurological symptoms, fever with stiff neck, head injury, or a major pattern change",
  },
  aiReadiness: {
    retrievalSummary: "Headache is pain or pressure in the head, face, scalp, or upper neck. Common contributors include stress, sleep, meal or fluid changes, caffeine, eye or neck strain, illness, migraine, and medicines. A sudden severe headache or headache with neurological, infection, or injury signs needs urgent assessment.",
    clinicalSummary: "Assess onset speed, severity, location, duration, associated neurologic, visual, fever, neck, injury, pregnancy, cancer, immune, and medication-overuse features; distinguish a stable primary pattern from secondary warning signs. Use targeted investigation according to history and examination.",
    patientSummary: "Most headaches are not dangerous, but their pattern matters. For a familiar mild headache, a calm break, fluids, a regular meal, and a diary may help. Seek emergency care for sudden severe pain, stroke-like symptoms, fever with stiff neck, a seizure, serious head injury, or loss of vision.",
    studentSummary: "Classify by primary versus secondary headache; take onset, duration, phenotype, associated symptoms, precipitating factors, medication use, neurologic examination, systemic risk factors, and red flags. A thunderclap phenotype or neurologic/systemic signs needs emergency assessment.",
    keywords: ["headache", "head pain", "cephalgia", "pressure in head", "tension headache", "headache diary"],
    semanticKeywords: ["sudden severe headache", "headache red flags", "headache triggers", "medication overuse headache", "migraine versus tension headache"],
    icd: "R51.9", bodySystem: "Neurology", urgency: "monitor",
  },
  qualityScore: { editorialQuality: 96, clinicalDepth: 91, graphConnectivity: 90, citationQuality: 100, educationalValue: 96, aiReadiness: 96, seoReadiness: 96 },
};
