import { KnowledgeEntity } from "../../types";

export const SleeplessnessSymptom: KnowledgeEntity = {
  id: "S0016",
  slug: "sleeplessness",
  entityType: "symptom",
  editorialStatus: "published",
  legacyVerificationStatus: "verified-published",
  versionInfo: { version: "1.2.0", created: "2026-07-08T12:00:00Z", updated: "2026-09-23T00:00:00Z", reviewed: "2026-09-23T00:00:00Z" },
  title: {
    en: "Sleeplessness: Why You May Not Be Sleeping Well and What Can Help",
    hi: "नींद न आना: नींद क्यों खराब हो सकती है और क्या मदद कर सकता है",
    gu: "ઊંઘ ન આવવી: ઊંઘ શા માટે ખરાબ હોઈ શકે અને શું મદદ કરી શકે",
    mr: "झोप न लागणे: झोप का खराब होऊ शकते आणि काय मदत करू शकते",
    es: "Insomnio: Por Qué Puede Dormir Mal y Qué Puede Ayudar",
    ar: "الأرق: لماذا قد لا تنام جيداً وما الذي قد يساعد",
  },
  summary: {
    en: "Sleeplessness means having trouble falling asleep, staying asleep, waking too early, or waking unrefreshed despite having a chance to sleep. Stress, routine changes, pain, medicines, caffeine, mood, and sleep disorders can contribute. A simple sleep record can make the next step clearer.",
    hi: "नींद न आने में सोने में कठिनाई, बार-बार जागना, बहुत जल्दी जागना या पर्याप्त अवसर के बाद भी तरोताज़ा न महसूस करना शामिल हो सकता है।",
    gu: "ઊંઘ ન આવવામાં ઊંઘવામાં મુશ્કેલી, વારંવાર જાગવું અથવા ઊંઘ પછી પણ તાજગી ન અનુભવવી સામેલ હોઈ શકે છે।",
    mr: "झोप न लागण्यात झोप येण्यास अडचण, वारंवार जाग येणे किंवा पुरेशी संधी असूनही ताजेतवाने न वाटणे समाविष्ट असू शकते.",
    es: "El insomnio puede incluir dificultad para dormir, despertares frecuentes o no sentirse renovado después de dormir.",
    ar: "قد يشمل الأرق صعوبة بدء النوم أو الاستمرار فيه أو عدم الشعور بالانتعاش بعده.",
  },
  content: {
    definition: "Sleeplessness, often called insomnia, is trouble falling asleep, staying asleep, waking too early, or getting sleep that does not feel restorative even when there is a reasonable opportunity to sleep. A bad night or a short stressful spell is common; a persistent pattern that affects daytime life deserves attention.",
    clinicalMeaning: "Sleep difficulty is a symptom and a pattern to understand, not a personal failure. It can be linked with stress, grief, anxiety or low mood, pain, medicines, caffeine or alcohol, shift work, travel, or another sleep condition. Looking at timing, routines, daytime sleepiness, snoring, breathing pauses, and how long the problem has lasted helps a clinician decide what support is useful.",
    commonCauses: [
      "Stress, worry, grief, a major life change, anxiety, low mood, or a habit of becoming anxious about not sleeping",
      "An irregular sleep schedule, daytime naps, late-night work, travel, shift work, or too much light and screen use close to bed",
      "Caffeine, nicotine, alcohol, recreational substances, or medicines that can make sleep harder",
      "Pain, reflux, breathing problems, frequent urination, hot flushes, thyroid conditions, or another physical health concern",
      "A sleep disorder such as sleep apnoea, restless legs syndrome, or a disrupted body-clock pattern",
    ],
    differentialDiagnosis: "A clinician may ask about your usual bedtime and wake time, naps, workload, mood, pain, medicines and supplements, caffeine and alcohol, snoring or gasping, leg discomfort, and daytime functioning. A sleep diary for one or two weeks is often useful. Further assessment is guided by the story: for example, loud snoring or breathing pauses may need assessment for sleep apnoea, while persistent anxiety, low mood, pain, or medicine side effects may need their own care plan.",
    redFlags: [
      "Loud snoring with gasping, choking, witnessed breathing pauses, morning headaches, or dangerous daytime sleepiness: arrange prompt medical advice, and do not drive or operate machinery if you are struggling to stay awake",
      "Sleeping far too little alongside unusually high energy, racing thoughts, impulsive behaviour, hallucinations, or severe agitation: seek urgent mental-health or emergency assessment",
      "Thoughts of harming yourself, feeling unable to keep yourself safe, or severe hopelessness: contact local emergency services or a crisis service now",
      "Severe shortness of breath, chest pain, fainting, new confusion, seizure, or a new one-sided weakness: seek emergency care",
      "Sleep difficulty that lasts for months, is worsening, or is affecting work, study, caring, mood, or safety: book a clinical appointment",
    ],
    lifestyleAdvice: "Start with a kind, consistent routine rather than trying to force sleep. Keep a regular wake time most days; make the bedroom cool, dark, and quiet; and give yourself a calming wind-down without work or scrolling. Limit caffeine, nicotine, and alcohol close to bedtime, get daylight and daytime movement that feels comfortable, and avoid using the bed for long periods of wakeful work or worry. If you are awake for a long time, a quiet low-light activity until you feel sleepy can be more helpful than struggling in bed. Avoid changing prescription medicines or relying on alcohol or over-the-counter sleep aids without clinical advice.",
    references: ["CIT-0123", "CIT-0124", "CIT-0023"],
    claimCitations: [
      { claimId: "S0016-DEFINITION-AND-CAUSES", passage: "definition; clinicalMeaning; commonCauses", citationIds: ["CIT-0123", "CIT-0124"] },
      { claimId: "S0016-CARE-SEEKING-AND-SUPPORT", passage: "redFlags; differentialDiagnosis; lifestyleAdvice", citationIds: ["CIT-0123", "CIT-0124"] },
      { claimId: "S0016-HOMEOPATHY-BOUNDARY", passage: "FAQ: homeopathy and insomnia", citationIds: ["CIT-0023"] },
    ],
    faqs: [
      { question: "When is sleeplessness considered insomnia?", answer: "Insomnia describes repeated difficulty falling asleep, staying asleep, waking too early, or getting good-quality sleep despite having a chance to sleep. A few poor nights during stress are common. Arrange an appointment when the problem is frequent, lasts for months, or affects daytime mood, concentration, work, study, driving, or safety." },
      { question: "What is the first useful thing to track?", answer: "For one or two weeks, note when you go to bed, roughly when you fall asleep, awakenings, final wake time, naps, caffeine or alcohol, medicines, exercise, stress, and how alert you feel the next day. This is not about judging yourself; it helps you and a clinician spot a pattern." },
      { question: "Could snoring be related to poor sleep?", answer: "It can be. Loud habitual snoring, gasping, choking sounds, witnessed breathing pauses, morning headaches, or excessive daytime sleepiness can point to a breathing problem during sleep such as sleep apnoea. Ask a clinician about this, and do not drive if you cannot stay awake safely." },
      { question: "Should I take melatonin or an over-the-counter sleep aid?", answer: "Do not assume these products are right or safe for you. Some can cause next-day drowsiness, interact with medicines, or mask an underlying problem. A pharmacist or clinician can help you review your situation, especially if you are pregnant, older, take regular medicines, or have a long-term condition." },
      { question: "Can homeopathy treat insomnia?", answer: "Reliable clinical evidence has not established homeopathy as a treatment for persistent insomnia or its underlying causes. It should not replace assessment for sleep apnoea, depression, anxiety, medicine side effects, pain, substance use, or urgent warning signs." },
    ],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" },
  reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" },
  reviewerRole: "Program-owner final authorization",
  lastClinicalReview: "2026-09-23",
  nextClinicalReview: "2027-09-23",
  referencesUpdated: "2026-09-23",
  clinicalChangesSinceLastRevision: "Rewrote the topic in plain language; added source-bound sleep patterns, safe care-seeking guidance, practical routine support, question-led FAQs, and an explicit evidence boundary for homeopathy.",
  reviewStatus: "owner-authorized-source-bound",
  citationHealth: "complete",
  contentCompleteness: 100,
  graphCompleteness: 100,
  evidenceLevel: "Consensus-Guidance",
  evidenceProfile: {
    evidenceStrength: "moderate", sourceQuality: "authoritative", classicalSource: false, modernSource: true, clinicalConfidence: 0.9, editorialConfidence: 0.95, citationCompleteness: 1,
    lastReviewedAt: "2026-09-23", reviewIntervalDays: 365, nextReviewDueAt: "2027-09-23", reviewExpiryPolicy: "flag-only",
    rationale: "Patient-facing insomnia information, routine support, and care-seeking boundaries are mapped to current NIH public clinical guidance.", methodologyVersion: "knowledge-authority-led-v1",
  },
  tags: ["Sleeplessness", "Insomnia", "Poor Sleep", "Sleep Problems", "Sleep Apnoea", "Sleep Diary"],
  canonicalUrl: "https://homeo.healthcare/knowledge/symptoms/sleeplessness",
  readingTimeMinutes: 6,
  audience: "patient",
  license: "CC BY-NC-ND 4.0",
  changeLog: ["1.0.0: Initial release of Sleeplessness symptom profile.", "1.2.0: Added patient-first sleep guidance, source-bound care-seeking boundaries, question-led FAQs, and visual guide."],
  clinicalPearl: "Sleep is not something to force: a steady routine, a simple record of the pattern, and timely help for breathing or safety concerns are more useful than chasing a perfect night.",
  quickFacts: {
    "What it can look like": "Trouble falling asleep, staying asleep, waking too early, or waking unrefreshed",
    "Common contributors": "Stress, routines, substances, pain, medicines, mood, and sleep disorders",
    "First useful step": "Keep a brief sleep diary and protect a steady wake time",
    "Get advice": "If it lasts, affects daytime life, or comes with snoring, gasping, or unsafe sleepiness",
  },
  aiReadiness: {
    retrievalSummary: "Sleeplessness or insomnia is repeated difficulty falling asleep, staying asleep, waking too early, or getting restorative sleep. Stress, routine changes, substances, pain, medicines, mood, and sleep disorders can contribute. Persistent symptoms or breathing and safety signs need clinical advice.",
    clinicalSummary: "Assess duration, frequency, daytime functional effect, sleep schedule, naps, stimulants and alcohol, medicines, pain, mood, snoring or breathing pauses, leg symptoms, shift work, and safety-sensitive daytime sleepiness. Use a sleep diary and investigate according to the pattern.",
    patientSummary: "Poor sleep is common and is not a personal failure. A simple sleep record and a regular wind-down can help. Seek prompt advice for loud snoring or gasping, dangerous daytime sleepiness, persistent insomnia, or a major effect on mood or safety.",
    studentSummary: "Insomnia involves sleep initiation, maintenance, or early-waking difficulty with daytime impairment despite opportunity for sleep. Consider behavioural, psychiatric, substance/medication, medical, circadian, sleep-breathing, and movement-disorder contributors; identify risk and functional impairment.",
    keywords: ["insomnia", "sleeplessness", "can't sleep", "poor sleep", "wake up at night", "sleep diary"],
    semanticKeywords: ["trouble falling asleep", "sleep apnoea signs", "sleep routine", "CBT-I", "daytime sleepiness"],
    icd: "G47.00", bodySystem: "Sleep Health", urgency: "monitor",
  },
  qualityScore: { editorialQuality: 96, clinicalDepth: 90, graphConnectivity: 90, citationQuality: 100, educationalValue: 96, aiReadiness: 96, seoReadiness: 95 },
};
