"use client";
import React from "react";
import { History, CalendarCheck, ReceiptText, CheckCircle2, ClipboardList } from "lucide-react";
import type { ClinicalActivity } from "@/lib/clinicalOperations";

const iconFor = (type: ClinicalActivity["type"]) => type.startsWith("appointment") ? CalendarCheck : type.startsWith("payment") ? ReceiptText : type.startsWith("task") ? CheckCircle2 : ClipboardList;
export default function ActivityTimeline({ activities = [] }: { activities?: ClinicalActivity[] }) {
  return <div className="rounded-[32px] border border-slate-200 bg-white p-6 shadow-xs dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-100 pb-3 dark:border-slate-800"><h3 className="flex items-center gap-2 text-sm font-bold text-slate-800 dark:text-slate-200"><History className="h-4.5 w-4.5 text-teal-500" />Clinical Audit Timeline</h3><span className="text-[9px] font-bold uppercase tracking-wider text-slate-400">Operational events</span></div>{activities.length ? <div className="mt-4 space-y-3">{activities.map((activity) => { const Icon = iconFor(activity.type); return <div key={activity.id} className="flex gap-3 text-[10px]"><div className="mt-0.5 rounded-xl bg-teal-50 p-2 text-teal-600"><Icon className="h-3.5 w-3.5" /></div><div className="min-w-0 flex-1"><div className="font-bold text-slate-800 dark:text-slate-100">{activity.title}</div><div className="mt-0.5 truncate text-slate-500">{activity.detail}</div><div className="mt-1 text-[8px] text-slate-400">{activity.actor.name} · {new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "short", timeZone: "Asia/Kolkata" }).format(new Date(activity.createdAt))}</div></div></div>; })}</div> : <div className="py-8 text-center text-[10px] text-slate-400">No operational events recorded yet.</div>}</div>;
}
