"use client";
import React, { useState } from "react";
import { CheckCircle2, ClipboardList, Plus } from "lucide-react";
import type { ClinicalTask } from "@/lib/clinicalOperations";

export default function MyTasksWidget({ tasks = [], onRefresh }: { tasks?: ClinicalTask[]; onRefresh: () => Promise<void> | void }) {
  const [title, setTitle] = useState(""); const [priority, setPriority] = useState<ClinicalTask["priority"]>("medium"); const [working, setWorking] = useState(false);
  const create = async (event: React.FormEvent) => { event.preventDefault(); if (!title.trim()) return; setWorking(true); try { const response = await fetch("/api/clinical-tasks", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, priority }) }); if (!response.ok) throw new Error(); setTitle(""); await onRefresh(); } finally { setWorking(false); } };
  const complete = async (id: string) => { setWorking(true); try { await fetch("/api/clinical-tasks", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status: "completed" }) }); await onRefresh(); } finally { setWorking(false); } };
  const openTasks = tasks.filter((task) => task.status === "open");
  return <div className="rounded-[24px] border border-slate-202 bg-white p-5 shadow-xs dark:bg-slate-900"><div className="flex items-center justify-between border-b border-slate-100 pb-3 dark:border-slate-800"><h3 className="flex items-center gap-2 text-xs font-bold text-slate-800 dark:text-slate-200"><ClipboardList className="h-4 w-4 text-teal-500" />My Tasks</h3><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[9px] font-bold text-slate-500">{openTasks.length} open</span></div><form onSubmit={create} className="mt-3 flex gap-2"><input value={title} onChange={(event) => setTitle(event.target.value)} className="min-w-0 flex-1 rounded-xl border border-slate-200 px-2.5 py-2 text-[10px]" placeholder="Add a clinical or admin task" /><select value={priority} onChange={(event) => setPriority(event.target.value as ClinicalTask["priority"])} className="rounded-xl border border-slate-200 bg-white px-2 text-[9px]"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select><button disabled={working} className="rounded-xl bg-teal-600 px-2.5 text-white"><Plus className="h-3.5 w-3.5" /></button></form><div className="mt-3 space-y-2">{openTasks.length ? openTasks.map((task) => <div key={task.id} className="flex items-center justify-between gap-2 rounded-xl bg-slate-50 p-2.5 text-[10px] dark:bg-slate-850"><div><div className="font-bold text-slate-700 dark:text-slate-200">{task.title}</div><div className="mt-0.5 text-[8px] uppercase text-slate-400">{task.priority} · assigned to {task.assignedTo.name}</div></div><button disabled={working} onClick={() => complete(task.id)} className="rounded-lg bg-emerald-50 px-2 py-1 text-[8px] font-bold text-emerald-700"><CheckCircle2 className="mr-1 inline h-3 w-3" />Done</button></div>) : <p className="py-4 text-center text-[10px] text-slate-400">No tasks assigned. Add one above when action is needed.</p>}</div></div>;
}
