/**
 * OSTM™ 3D Anatomy Preview — 12-System Modular Registry
 * Digestive, cardiovascular, renal, nervous, respiratory, skeletal,
 * All twelve system pilots now use source-verified anatomical references.
 */

import { AnatomySystemId } from "../data/medicalAcademyData";

export interface AnatomicalStructureDefinition {
  id: string;
  name: string;
  aliases: string[];
  meshNodeNames: string[];
  icon: string;
  description: string;
  focusHint: string;
  knowledgeGraphId: string;
  confidence: "placeholder-label" | "source-defined" | "metadata-mapped" | "unknown";
  layer?: "visceral" | "vasculature";
}

export interface AnatomicalAssetDefinition {
  id: string;
  name: string;
  filePath: string;
  source: string;
  sourceUpAxis?: "y" | "z";
  sourceType: "procedural-placeholder" | "imaging-derived" | "anatomically-modeled" | "anatomical-reference";
  productionEligible: boolean;
  provenanceStatus?: "repository-generated" | "source-verified";
  sourceUrl?: string;
  sourceVersion?: string;
  sourceChecksum?: string;
  license?: string;
  licenseUrl?: string;
  attribution?: string;
  reviewStatus?: "not-reviewed" | "source-reviewed" | "locally-reviewed";
  capabilities?: {
    vasculature: boolean;
  };
  structures: AnatomicalStructureDefinition[];
}

export interface SubOrganItem {
  id: string;
  name: string;
  icon: string;
  description: string;
  focusHint: string;
}

export interface System3DConfig {
  id: AnatomySystemId;
  name: string;
  subtitle: string;
  badge: string;
  coverageLabel: string;
  accentColor: string;
  primaryAssetPath?: string;
  assets: AnatomicalAssetDefinition[];
  subOrgans: SubOrganItem[];
  overview: string;
  clinicalFocus: string;
}

/** Resolve the asset that contains a selected structure, falling back safely. */
export function resolveSystem3DAsset(
  config: System3DConfig,
  structureId: string | null
): AnatomicalAssetDefinition | undefined {
  const primaryAsset =
    config.assets.find((asset) => asset.filePath === config.primaryAssetPath) || config.assets[0];
  if (!structureId) return primaryAsset;

  const matchingAssets = config.assets
    .filter((asset) => asset.structures.some((structure) => structure.id === structureId))
    .sort((left, right) => left.structures.length - right.structures.length);

  return matchingAssets[0] || primaryAsset;
}

export function matchesMeshNodePattern(meshName: string, pattern: string): boolean {
  const normalizedName = meshName.toLowerCase();
  const normalizedPattern = pattern.toLowerCase();
  return normalizedPattern.endsWith("*")
    ? normalizedName.startsWith(normalizedPattern.slice(0, -1))
    : normalizedName === normalizedPattern;
}

export function resolveStructureForMesh(
  structures: AnatomicalStructureDefinition[],
  meshName: string
): AnatomicalStructureDefinition | undefined {
  return structures.find((structure) =>
    structure.meshNodeNames.some((pattern) => matchesMeshNodePattern(meshName, pattern))
  );
}

export const SYSTEM_3D_REGISTRY: Record<AnatomySystemId, System3DConfig> = {
  digestive: {
    id: "digestive",
    name: "Digestive System & Gastrointestinal Tract",
    subtitle: "Nutrient Digestion, Hepatic Metabolism & Enteric Absorption",
    badge: "Metabolic Engine",
    coverageLabel: "Expanded alimentary reference",
    accentColor: "#EA580C",
    primaryAssetPath: "/models/anatomy/digestive/alimentary_system_bodyparts3d_v4.glb",
    assets: [
      {
        id: "bodyparts3d_alimentary_system_v4",
        name: "Alimentary System",
        filePath: "/models/anatomy/digestive/alimentary_system_bodyparts3d_v4.glb",
        source: "BodyParts3D v4.0 / Database Center for Life Science",
        sourceUpAxis: "z",
        sourceType: "anatomical-reference",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html",
        sourceVersion: "BodyParts3D 4.0 PART-OF tree, 99% polygon reduction",
        sourceChecksum: "9fbc713fffeee924a5a657d9813d84d7eb957bded63adb854931dd5e3eb61c97",
        license: "CC BY-SA 2.1 Japan (conservative classification from embedded OBJ notice)",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en",
        attribution: "BodyParts3D, © The Database Center for Life Science",
        reviewStatus: "not-reviewed",
        structures: [
          {
            id: "mouth",
            name: "Mouth and Oral Structures",
            aliases: ["mouth", "oral cavity", "tongue"],
            meshNodeNames: ["BodyParts3D_mouth_*"],
            icon: "👄",
            description: "Eleven source surfaces representing the mouth and its modeled oral subdivisions.",
            focusHint: "Oral cavity",
            knowledgeGraphId: "FMA:49184",
            confidence: "source-defined",
          },
          {
            id: "esophagus",
            name: "Esophagus",
            aliases: ["esophagus", "oesophagus", "food pipe"],
            meshNodeNames: ["BodyParts3D_esophagus_*"],
            icon: "🟤",
            description: "Source-defined whole esophageal surface connecting pharyngeal and gastric regions.",
            focusHint: "Cervical and thoracic alimentary conduit",
            knowledgeGraphId: "FMA:7131",
            confidence: "source-defined",
          },
          {
            id: "stomach",
            name: "Stomach",
            aliases: ["stomach", "gaster", "gastric organ"],
            meshNodeNames: ["BodyParts3D_stomach_*"],
            icon: "🫕",
            description: "Source-preserving whole-organ surface model used for gross anatomical orientation.",
            focusHint: "Epigastrium and left hypochondrium",
            knowledgeGraphId: "FMA:7148",
            confidence: "source-defined",
          },
          {
            id: "small_intestine",
            name: "Small Intestine and Mesentery",
            aliases: ["small intestine", "duodenum", "jejunum", "ileum", "mesentery"],
            meshNodeNames: ["BodyParts3D_small_intestine_*"],
            icon: "🟠",
            description: "Fifty-six source surfaces covering small-intestinal regions and their modeled mesentery.",
            focusHint: "Central and lower abdomen",
            knowledgeGraphId: "FMA:7200",
            confidence: "source-defined",
          },
          {
            id: "large_intestine",
            name: "Large Intestine and Mesocolon",
            aliases: ["large intestine", "colon", "cecum", "appendix", "rectum"],
            meshNodeNames: ["BodyParts3D_large_intestine_*"],
            icon: "🟫",
            description: "Eleven source surfaces covering the colon, appendix, ileocecal junction, mesoappendix, and transverse mesocolon.",
            focusHint: "Peripheral abdominal and pelvic bowel",
            knowledgeGraphId: "FMA:7201",
            confidence: "metadata-mapped",
          },
          {
            id: "gallbladder",
            name: "Gallbladder and Extrahepatic Ducts",
            aliases: ["gallbladder", "cystic duct", "common hepatic duct"],
            meshNodeNames: ["BodyParts3D_gallbladder_*"],
            icon: "🫒",
            description: "Source surfaces for the gallbladder, cystic duct, and common hepatic duct.",
            focusHint: "Right upper quadrant biliary apparatus",
            knowledgeGraphId: "FMA:7202",
            confidence: "metadata-mapped",
          },
          {
            id: "liver",
            name: "Liver",
            aliases: ["liver", "hepatic lobes", "hepatic segments"],
            meshNodeNames: ["BodyParts3D_liver_*"],
            icon: "🥩",
            description: "Sixty source surfaces representing the liver and its modeled lobar, sectoral, and biliary subdivisions.",
            focusHint: "Right hypochondrium and epigastrium",
            knowledgeGraphId: "FMA:7197",
            confidence: "source-defined",
          },
          {
            id: "pancreas",
            name: "Pancreas",
            aliases: ["pancreas", "pancreatic parenchyma"],
            meshNodeNames: ["BodyParts3D_pancreas_*"],
            icon: "🟡",
            description: "Four source surfaces representing pancreatic gross anatomy and modeled parenchyma.",
            focusHint: "Retroperitoneal upper abdomen",
            knowledgeGraphId: "FMA:7198",
            confidence: "source-defined",
          },
        ],
      },
      {
        id: "hra_liver_male_v1",
        name: "Liver",
        filePath: "/models/anatomy/digestive/liver_hra_male_v1.glb",
        source: "Human Reference Atlas / HuBMAP",
        sourceType: "imaging-derived",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://cdn.humanatlas.io/hra-kg--staging/ref-organ/liver-male/v1.0/",
        sourceVersion: "v1.0",
        sourceChecksum: "e94f18646d1b8f72cc45b92bdd67bbb4eb71d5bf954888bc8b8f8b52b3940b6a",
        license: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        attribution: "Kristen Browne. 2021. 3D Reference Organ for Liver, Male v1.0. DOI: 10.48539/HBM793.BQGC.274",
        reviewStatus: "source-reviewed",
        structures: [
          {
            id: "liver",
            name: "Liver and Couinaud Segments",
            aliases: ["liver", "hepatic lobe", "hepatocytes"],
            meshNodeNames: ["VH_M_liver", "VH_M_couinaud_liver_segment"],
            icon: "🥩",
            description: "Visible Human-derived liver reference organ with lobar, segmental, surface, and ligament meshes.",
            focusHint: "Right hypochondrium & epigastrium",
            knowledgeGraphId: "UBERON:0002107",
            confidence: "source-defined",
          },
        ],
      },
      {
        id: "hra_pancreas_male_v1",
        name: "Pancreas",
        filePath: "/models/anatomy/digestive/pancreas_hra_male_v1.glb",
        source: "Human Reference Atlas / HuBMAP",
        sourceType: "imaging-derived",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://cdn.humanatlas.io/hra-kg--staging/ref-organ/pancreas-male/v1.0/",
        sourceVersion: "v1.0",
        sourceChecksum: "3486e3a4d6f2093460396fb65a907499f1457680156fe80be220a148677138e4",
        license: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        attribution: "Kristen Browne. 2021. 3D Reference Organ for Pancreas, Male v1.0. DOI: 10.48539/HBM249.BLBM.234",
        reviewStatus: "source-reviewed",
        structures: [
          {
            id: "pancreas",
            name: "Pancreas",
            aliases: ["pancreas", "pancreatic head", "pancreatic body", "pancreatic tail"],
            meshNodeNames: ["VH_M_pancreas", "VH_M_body_of_pancreas", "VH_M_head_of_pancreas"],
            icon: "🟡",
            description: "Visible Human-derived pancreas reference organ with head, neck, body, tail, and uncinate-process meshes.",
            focusHint: "Retroperitoneal upper abdomen",
            knowledgeGraphId: "UBERON:0001264",
            confidence: "source-defined",
          },
        ],
      },
    ],
    subOrgans: [
      {
        id: "mouth",
        name: "Mouth & Oral Structures",
        icon: "👄",
        description: "Source-mapped mouth and modeled oral subdivisions.",
        focusHint: "Oral cavity",
      },
      {
        id: "esophagus",
        name: "Esophagus",
        icon: "🟤",
        description: "Whole esophageal surface in shared alimentary coordinates.",
        focusHint: "Cervical and thoracic alimentary conduit",
      },
      {
        id: "stomach",
        name: "Stomach",
        icon: "🫕",
        description: "Whole-organ BodyParts3D surface reference; local anatomical review pending.",
        focusHint: "Epigastrium and left hypochondrium",
      },
      {
        id: "small_intestine",
        name: "Small Intestine",
        icon: "🟠",
        description: "Duodenal, jejunal, ileal, and modeled mesenteric source surfaces.",
        focusHint: "Central and lower abdomen",
      },
      {
        id: "large_intestine",
        name: "Large Intestine",
        icon: "🟫",
        description: "Colon, appendix, ileocecal junction, and modeled mesocolon surfaces.",
        focusHint: "Peripheral abdomen and pelvis",
      },
      {
        id: "gallbladder",
        name: "Gallbladder & Ducts",
        icon: "🫒",
        description: "Gallbladder, cystic duct, and common hepatic duct surfaces.",
        focusHint: "Right upper quadrant",
      },
      {
        id: "liver",
        name: "Liver",
        icon: "🥩",
        description: "HRA liver reference with anatomical surfaces and Couinaud segments.",
        focusHint: "Right upper quadrant",
      },
      {
        id: "pancreas",
        name: "Pancreas",
        icon: "🟡",
        description: "HRA pancreas reference with head, neck, body, tail, and uncinate process.",
        focusHint: "Retroperitoneal upper abdomen",
      },
    ],
    overview: "Continuous alimentary canal and accessory glandular organs orchestrating mechanical breakdown, enzymatic hydrolysis, hepatic assimilation, and nutrient absorption.",
    clinicalFocus: "Peptic ulcer disease, GERD, gastroparesis, non-alcoholic fatty liver (NAFLD), cholelithiasis, and malabsorption syndromes.",
  },

  cardiovascular: {
    id: "cardiovascular",
    name: "Cardiovascular System & Hemodynamics",
    subtitle: "Pulsatile 4-Chamber Heart & Coronary Network",
    badge: "Vital Pump",
    coverageLabel: "Regional reference: heart",
    accentColor: "#E11D48",
    primaryAssetPath: "/models/anatomy/cardiovascular/heart_hra_female_v1_1.glb",
    assets: [
      {
        id: "hra_heart_female_v1_1",
        name: "Heart, Chambers & Great Vessels",
        filePath: "/models/anatomy/cardiovascular/heart_hra_female_v1_1.glb",
        source: "Human Reference Atlas / HuBMAP",
        sourceType: "imaging-derived",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://cdn.humanatlas.io/hra-kg--staging/ref-organ/heart-female/v1.1/",
        sourceVersion: "v1.1",
        sourceChecksum: "a7f85f36cd693eca742c8ed9c7bace42305521d4246db985c2c38e3bd22f3055",
        license: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        attribution: "Kristen Browne. 2021. 3D Reference Organ for Heart, Female v1.1. DOI: 10.48539/HBM459.GVPS.249",
        reviewStatus: "source-reviewed",
        capabilities: { vasculature: true },
        structures: [
          {
            id: "left_ventricle",
            name: "Left Ventricle",
            aliases: ["left ventricle", "ventricular chamber"],
            meshNodeNames: ["VH_F_left_ventricle"],
            icon: "❤️",
            description: "Source-defined left ventricular chamber surface in the Visible Human Female-derived reference heart.",
            focusHint: "Anterior-inferior apex / 5th left intercostal space",
            knowledgeGraphId: "UBERON:0002084",
            confidence: "source-defined",
            layer: "visceral",
          },
          {
            id: "aorta_arch",
            name: "Aortic Arch & Branches",
            aliases: ["aorta", "aortic arch"],
            meshNodeNames: [
              "VH_F_aortic_arch",
              "VH_F_ascending_aorta",
              "VH_F_descending_aorta*",
              "VH_F_left_common_carotid_artery*",
              "VH_F_left_subclavian_artery*",
              "VH_F_brachiocephalic_artery*"
            ],
            icon: "🫀",
            description: "Source-defined ascending aorta, arch, descending segments, and principal arch branches.",
            focusHint: "Superior mediastinum / T4 level",
            knowledgeGraphId: "UBERON:0001508",
            confidence: "source-defined",
            layer: "vasculature",
          },
          {
            id: "coronary_arteries",
            name: "Coronary Arterial Tree",
            aliases: ["coronary", "lad", "rca"],
            meshNodeNames: [
              "VH_F_left_anterior_descending_artery",
              "VH_F_left_circumflex_artery",
              "VH_F_diagonal_branch_of_left_anterior_descending_artery",
              "VH_F_left_coronary_artery",
              "VH_F_left_marginal_branch",
              "VH_F_left_posterior_descending_branch*",
              "VH_F_posterior_left_ventricular_branch",
              "VH_F_right_coronary_artery",
              "VH_F_right_marginal_artery"
            ],
            icon: "🩸",
            description: "Source-defined left and right coronary arteries with named major branches.",
            focusHint: "Coronary and anterior interventricular sulci",
            knowledgeGraphId: "UBERON:0001626",
            confidence: "source-defined",
            layer: "vasculature",
          },
          {
            id: "cardiac_valves",
            name: "Cardiac Valves",
            aliases: ["aortic valve", "pulmonary valve", "mitral valve", "tricuspid valve"],
            meshNodeNames: [
              "VH_F_aortic_valve",
              "VH_F_pulmonary_valve",
              "VH_F_mitral_valve",
              "VH_F_tricuspid_valve"
            ],
            icon: "🔄",
            description: "Source-defined aortic, pulmonary, mitral, and tricuspid valve surfaces.",
            focusHint: "Central cardiac valve plane",
            knowledgeGraphId: "UBERON:0000948",
            confidence: "source-defined",
            layer: "visceral",
          },
        ],
      },
    ],
    subOrgans: [
      {
        id: "left_ventricle",
        name: "Left Ventricle",
        icon: "❤️",
        description: "High-pressure muscular chamber generating systemic systolic blood pressure.",
        focusHint: "Anterior-inferior apex",
      },
      {
        id: "aorta_arch",
        name: "Aorta & Great Vessels",
        icon: "🫀",
        description: "Ascending aorta, aortic arch, and brachiocephalic/carotid trunks.",
        focusHint: "Superior mediastinum",
      },
      {
        id: "coronary_arteries",
        name: "Coronary Vasculature",
        icon: "🩸",
        description: "Left anterior descending and right coronary arterial perfusion network.",
        focusHint: "Interventricular sulcus",
      },
      {
        id: "cardiac_valves",
        name: "Cardiac Valves",
        icon: "🔄",
        description: "Aortic, pulmonary, mitral, and tricuspid valve surfaces.",
        focusHint: "Central valve plane",
      },
    ],
    overview: "Closed high-pressure systemic and low-pressure pulmonary circuit driven by rhythmic electromechanical myocardial contractions.",
    clinicalFocus: "Ischemic heart disease, coronary artery disease, heart failure with preserved/reduced ejection fraction, and valvular stenosis.",
  },

  renal: {
    id: "renal",
    name: "Renal & Urinary Excretory System",
    subtitle: "Glomerular Ultrafiltration, Acid-Base & Fluid Homeostasis",
    badge: "Master Filter",
    coverageLabel: "Multi-organ urinary reference",
    accentColor: "#0284C7",
    primaryAssetPath: "/models/anatomy/renal/kidney_hra_male_left_v1_2.glb",
    assets: [
      {
        id: "hra_kidney_male_left_v1_2",
        name: "Left Kidney",
        filePath: "/models/anatomy/renal/kidney_hra_male_left_v1_2.glb",
        source: "Human Reference Atlas / HuBMAP",
        sourceType: "imaging-derived",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://cdn.humanatlas.io/hra-kg--staging/ref-organ/kidney-male-left/v1.2/",
        sourceVersion: "v1.2",
        sourceChecksum: "733eef9ec169796196470e538dc248c4397bce0ff7ed679f7b7eb0bb9f185612",
        license: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        attribution: "Kristen Browne and Heidi Schlehlein. 2024. 3D Reference Organ for Kidney, Male, Left v1.2. DOI: 10.48539/HBM562.JGPS.244",
        reviewStatus: "source-reviewed",
        structures: [
          {
            id: "kidney_left",
            name: "Left Kidney",
            aliases: ["left kidney", "renal cortex", "renal pyramids", "renal papillae"],
            meshNodeNames: [
              "VH_M_kidney_capsule_L",
              "VH_M_hilum_of_kidney_L",
              "VH_M_renal_column_L",
              "VH_M_outer_cortex_of_kidney_L",
              "VH_M_renal_papilla_L_*",
              "VH_M_renal_pyramid_L_*",
            ],
            icon: "🫘",
            description: "Visible Human Male-derived left kidney reference with source-defined capsule, hilum, cortex, columns, pyramids, and papillae.",
            focusHint: "Left retroperitoneal renal region",
            knowledgeGraphId: "UBERON:0002113",
            confidence: "source-defined",
          },
        ],
      },
      {
        id: "hra_kidney_male_right_v1_2",
        name: "Right Kidney",
        filePath: "/models/anatomy/renal/kidney_hra_male_right_v1_2.glb",
        source: "Human Reference Atlas / HuBMAP",
        sourceType: "imaging-derived",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://cdn.humanatlas.io/hra-kg--staging/ref-organ/kidney-male-right/v1.2/",
        sourceVersion: "v1.2",
        sourceChecksum: "ff9821e0b8fb7fa6174a07b9cafb9f98bb25feca34ddc0e802beeefb24cd3779",
        license: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        attribution: "Kristen Browne and Heidi Schlehlein. 2024. 3D Reference Organ for Kidney, Male, Right v1.2. DOI: 10.48539/HBM272.ZVPQ.979",
        reviewStatus: "source-reviewed",
        structures: [
          {
            id: "kidney_right",
            name: "Right Kidney",
            aliases: ["right kidney", "renal cortex", "renal pyramids", "renal papillae"],
            meshNodeNames: [
              "VH_M_kidney_capsule_R",
              "VH_M_hilum_of_kidney_R",
              "VH_M_renal_column_R",
              "VH_M_outer_cortex_of_kidney_R",
              "VH_M_renal_papilla_R_*",
              "VH_M_renal_pyramid_*",
            ],
            icon: "🫘",
            description: "Visible Human Male-derived right kidney reference with source-defined capsule, hilum, cortex, columns, pyramids, and papillae.",
            focusHint: "Right retroperitoneal renal region",
            knowledgeGraphId: "UBERON:0002113",
            confidence: "source-defined",
          },
        ],
      },
      {
        id: "hra_ureter_male_left_v1_2",
        name: "Left Ureter & Collecting System",
        filePath: "/models/anatomy/renal/ureter_hra_male_left_v1_2.glb",
        source: "Human Reference Atlas / HuBMAP",
        sourceType: "imaging-derived",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://cdn.humanatlas.io/hra-kg--staging/ref-organ/ureter-male-left/v1.2/",
        sourceVersion: "v1.2",
        sourceChecksum: "ebdd493c2e8095ccb6e795f49bf26c94e8d205c94097a7e1f9a9d7b168a1173c",
        license: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        attribution: "Kristen Browne and Heidi Schlehlein. 2024. 3D Reference Organ for Ureter, Male, Left v1.2. DOI: 10.48539/HBM434.VLQJ.299",
        reviewStatus: "source-reviewed",
        structures: [
          {
            id: "ureter_left",
            name: "Left Ureter & Calyces",
            aliases: ["left ureter", "renal pelvis", "major calyx", "minor calyx"],
            meshNodeNames: [
              "VH_M_renal_pelvis_L",
              "VH_M_major_calyx_L_*",
              "VH_M_minor_calyx_L_*",
              "VH_M_ureter_L",
            ],
            icon: "💧",
            description: "Source-defined left ureter with renal pelvis and major and minor calyces.",
            focusHint: "Left collecting system and retroperitoneal ureter",
            knowledgeGraphId: "UBERON:0001223",
            confidence: "source-defined",
          },
        ],
      },
      {
        id: "hra_ureter_male_right_v1_2",
        name: "Right Ureter & Collecting System",
        filePath: "/models/anatomy/renal/ureter_hra_male_right_v1_2.glb",
        source: "Human Reference Atlas / HuBMAP",
        sourceType: "imaging-derived",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://cdn.humanatlas.io/hra-kg--staging/ref-organ/ureter-male-right/v1.2/",
        sourceVersion: "v1.2",
        sourceChecksum: "215978b67cf4d3876249a8dafb8c83a13471b5e1eb601559dca25a61a7c9d091",
        license: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        attribution: "Kristen Browne and Heidi Schlehlein. 2024. 3D Reference Organ for Ureter, Male, Right v1.2. DOI: 10.48539/HBM852.SVFJ.388",
        reviewStatus: "source-reviewed",
        structures: [
          {
            id: "ureter_right",
            name: "Right Ureter & Calyces",
            aliases: ["right ureter", "renal pelvis", "major calyx", "minor calyx"],
            meshNodeNames: [
              "VH_M_renal_pelvis_R",
              "VH_M_major_calyx_R_*",
              "VH_M_minor_calyx_R_*",
              "VH_M_ureter_R",
            ],
            icon: "💧",
            description: "Source-defined right ureter with renal pelvis and major and minor calyces.",
            focusHint: "Right collecting system and retroperitoneal ureter",
            knowledgeGraphId: "UBERON:0001222",
            confidence: "source-defined",
          },
        ],
      },
      {
        id: "hra_urinary_bladder_male_v1_2",
        name: "Urinary Bladder",
        filePath: "/models/anatomy/renal/urinary_bladder_hra_male_v1_2.glb",
        source: "Human Reference Atlas / HuBMAP",
        sourceType: "imaging-derived",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://cdn.humanatlas.io/hra-kg--staging/ref-organ/urinary-bladder-male/v1.2/",
        sourceVersion: "v1.2",
        sourceChecksum: "070893aea9139d9a2c4f8da3aa66ca309a3c683a599d93a37dd7031c7d71021d",
        license: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        attribution: "Kristen Browne and Heidi Schlehlein. 2024. 3D Reference Organ for Urinary Bladder, Male v1.2. DOI: 10.48539/HBM722.RMHQ.397",
        reviewStatus: "source-reviewed",
        structures: [
          {
            id: "urinary_bladder",
            name: "Urinary Bladder",
            aliases: ["bladder", "bladder neck", "fundus", "trigone", "ureteral orifice"],
            meshNodeNames: [
              "VH_M_urinary_bladder_neck_smooth_muscle",
              "VH_M_fundus_of_urinary_bladder_dome",
              "VH_M_fundus_of_urinary_bladder_base1",
              "VH_M_ureteral_orifice_R",
              "VH_M_ureteral_orifice_L",
              "VH_M_trigone_of_urinary_bladder",
            ],
            icon: "🎈",
            description: "Visible Human Male-derived bladder reference with source-defined neck smooth muscle, fundus, trigone, and ureteral orifices.",
            focusHint: "Pelvic urinary reservoir",
            knowledgeGraphId: "UBERON:0001255",
            confidence: "source-defined",
          },
        ],
      },
    ],
    subOrgans: [
      {
        id: "kidney_left",
        name: "Left Kidney",
        icon: "🫘",
        description: "Capsule, hilum, cortex, columns, pyramids, and papillae from the HRA left-kidney reference.",
        focusHint: "Left retroperitoneal renal region",
      },
      {
        id: "kidney_right",
        name: "Right Kidney",
        icon: "🫘",
        description: "Capsule, hilum, cortex, columns, pyramids, and papillae from the HRA right-kidney reference.",
        focusHint: "Right retroperitoneal renal region",
      },
      {
        id: "ureter_left",
        name: "Left Ureter",
        icon: "💧",
        description: "Left renal pelvis, major and minor calyces, and ureter.",
        focusHint: "Left collecting system",
      },
      {
        id: "ureter_right",
        name: "Right Ureter",
        icon: "💧",
        description: "Right renal pelvis, major and minor calyces, and ureter.",
        focusHint: "Right collecting system",
      },
      {
        id: "urinary_bladder",
        name: "Urinary Bladder",
        icon: "🎈",
        description: "Bladder neck, fundus, trigone, and paired ureteral orifices.",
        focusHint: "Pelvic urinary reservoir",
      },
    ],
    overview: "Precision filtration and osmoregulatory system clearing nitrogenous metabolic wastes, balancing electrolytes, and secreting erythropoietin and renin.",
    clinicalFocus: "Chronic kidney disease (CKD), glomerulonephritis, nephrolithiasis, and diabetic nephropathy.",
  },

  nervous: {
    id: "nervous",
    name: "Nervous System & Neural Circuits",
    subtitle: "Cerebral Cortex, Synaptic Signaling & Central Integration",
    badge: "Command Matrix",
    coverageLabel: "Regional reference: brain",
    accentColor: "#8B5CF6",
    primaryAssetPath: "/models/anatomy/nervous/brain_bodyparts3d_v4.glb",
    assets: [
      {
        id: "bodyparts3d_brain_v4",
        name: "Brain, Cerebellum & Brainstem",
        filePath: "/models/anatomy/nervous/brain_bodyparts3d_v4.glb",
        source: "BodyParts3D v4.0 / Database Center for Life Science",
        sourceUpAxis: "z",
        sourceType: "anatomical-reference",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html",
        sourceVersion: "BodyParts3D 4.0 PART-OF tree, 99% polygon reduction",
        sourceChecksum: "9fbc713fffeee924a5a657d9813d84d7eb957bded63adb854931dd5e3eb61c97",
        license: "CC BY-SA 2.1 Japan (conservative classification from embedded OBJ notices)",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en",
        attribution: "BodyParts3D, © The Database Center for Life Science",
        reviewStatus: "not-reviewed",
        structures: [
          {
            id: "cerebral_hemisphere_left",
            name: "Left Cerebral Hemisphere",
            aliases: ["left cerebrum", "left cerebral cortex", "left hemisphere"],
            meshNodeNames: ["BodyParts3D_cerebral_hemisphere_left_*"],
            icon: "🧠",
            description: "Nineteen BodyParts3D surfaces mapped by the source PART-OF table to the left cerebral hemisphere.",
            focusHint: "Left supratentorial cranial compartment",
            knowledgeGraphId: "FMA:61819",
            confidence: "source-defined",
          },
          {
            id: "cerebral_hemisphere_right",
            name: "Right Cerebral Hemisphere",
            aliases: ["right cerebrum", "right cerebral cortex", "right hemisphere"],
            meshNodeNames: ["BodyParts3D_cerebral_hemisphere_right_*"],
            icon: "🧠",
            description: "Nineteen BodyParts3D surfaces mapped by the source PART-OF table to the right cerebral hemisphere.",
            focusHint: "Right supratentorial cranial compartment",
            knowledgeGraphId: "FMA:67292",
            confidence: "source-defined",
          },
          {
            id: "cerebellum",
            name: "Cerebellum",
            aliases: ["cerebellum"],
            meshNodeNames: ["BodyParts3D_cerebellum_*"],
            icon: "🌿",
            description: "Two source surfaces mapped to the cerebellum in the BodyParts3D PART-OF hierarchy.",
            focusHint: "Posterior cranial fossa",
            knowledgeGraphId: "FMA:67944",
            confidence: "source-defined",
          },
          {
            id: "brainstem",
            name: "Brainstem",
            aliases: ["brainstem", "midbrain", "pons", "medulla oblongata"],
            meshNodeNames: ["BodyParts3D_brainstem_*"],
            icon: "⚡",
            description: "Eleven source surfaces spanning source-mapped midbrain, pons, medulla, collicular, and aqueduct structures.",
            focusHint: "Central and inferior cranial base",
            knowledgeGraphId: "FMA:79876",
            confidence: "source-defined",
          },
          {
            id: "deep_brain_ventricles",
            name: "Deep Brain & Ventricles",
            aliases: ["diencephalon", "hypothalamus", "pineal body", "third ventricle", "fourth ventricle"],
            meshNodeNames: ["BodyParts3D_deep_brain_ventricles_*"],
            icon: "🔬",
            description: "Viewer grouping of eight source brain surfaces covering ventricular and diencephalic structures; the grouping itself is application metadata.",
            focusHint: "Deep midline brain",
            knowledgeGraphId: "FMA:50801",
            confidence: "metadata-mapped",
          },
        ],
      },
    ],
    subOrgans: [
      {
        id: "cerebral_hemisphere_left",
        name: "Left Cerebral Hemisphere",
        icon: "🧠",
        description: "Source-mapped left cerebral hemisphere surfaces.",
        focusHint: "Left supratentorial compartment",
      },
      {
        id: "cerebral_hemisphere_right",
        name: "Right Cerebral Hemisphere",
        icon: "🧠",
        description: "Source-mapped right cerebral hemisphere surfaces.",
        focusHint: "Right supratentorial compartment",
      },
      {
        id: "cerebellum",
        name: "Cerebellum",
        icon: "🌿",
        description: "Source-mapped cerebellar surfaces.",
        focusHint: "Infratentorial compartment",
      },
      {
        id: "brainstem",
        name: "Brainstem",
        icon: "⚡",
        description: "Source-mapped brainstem structures including pons, medulla, and midbrain regions.",
        focusHint: "Base of skull",
      },
      {
        id: "deep_brain_ventricles",
        name: "Deep Brain & Ventricles",
        icon: "🔬",
        description: "Application grouping of source diencephalic and ventricular structures.",
        focusHint: "Deep midline brain",
      },
    ],
    overview: "Electro-chemical biological computational matrix integrating sensory inputs, voluntary motor outputs, and autonomic homeostatic reflexes.",
    clinicalFocus: "Neurodegenerative disorders, stroke, peripheral neuropathies, migraine, and autonomic dysautonomia.",
  },

  respiratory: {
    id: "respiratory",
    name: "Respiratory System & Gas Exchange",
    subtitle: "Pulmonary Ventilation, Alveolar Diffusion & Acid-Base Balance",
    badge: "Oxygen Gateway",
    coverageLabel: "Multi-organ airway reference",
    accentColor: "#06B6D4",
    primaryAssetPath: "/models/anatomy/respiratory/lung_hra_male_v1_4.glb",
    assets: [
      {
        id: "hra_lung_male_v1_4",
        name: "Lungs & Intrapulmonary Bronchi",
        filePath: "/models/anatomy/respiratory/lung_hra_male_v1_4.glb",
        source: "Human Reference Atlas / HuBMAP",
        sourceType: "imaging-derived",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://cdn.humanatlas.io/hra-kg--staging/ref-organ/lung-male/v1.4/",
        sourceVersion: "v1.4",
        sourceChecksum: "bba95516fa993ac45c3b1c53f32b58d97232ffd78ae56397e5a2589c6ce4903d",
        license: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        attribution: "Kristen Browne and Heidi Schlehlein. 2024. 3D Reference Organ for Lung, Male v1.4. DOI: 10.48539/HBM532.KLZD.394",
        reviewStatus: "source-reviewed",
        structures: [
          {
            id: "left_lung_segments",
            name: "Left Bronchopulmonary Segments",
            aliases: ["left lung", "left bronchopulmonary segments", "lingula"],
            meshNodeNames: [
              "VH_M_hilum_L",
              "VH_M_hilum_upper_L",
              "VH_M_hilum_lower_L",
              "VH_M_left_lingula_superior_bronchopulmonary_segment",
              "VH_M_left_posterior_bronchopulmonary_segment",
              "VH_M_left_anterior_bronchopulmonary_segment",
              "VH_M_left_apical_bronchopulmonary_segment",
              "VH_M_left_lingula_inferior_bronchopulmonary_segment",
              "VH_M_left_anterior_basal_bronchopulmonary_segment",
              "VH_M_left_lateral_basal_bronchopulmonary_segment",
              "VH_M_left_medial_basal_bronchopulmonary_segment",
              "VH_M_left_posetrior_basal_bronchopulmonary_segment",
              "VH_M_left_superior_bronchopulmonary_segment",
            ],
            icon: "🫁",
            description: "Source-defined left bronchopulmonary segment and hilum surfaces from the Visible Human Male-derived lung reference.",
            focusHint: "Left thoracic cavity",
            knowledgeGraphId: "UBERON:0002168",
            confidence: "source-defined",
          },
          {
            id: "right_lung_segments",
            name: "Right Bronchopulmonary Segments",
            aliases: ["right lung", "right bronchopulmonary segments"],
            meshNodeNames: [
              "VH_M_hilum_R",
              "VH_M_hilum_middle_R",
              "VH_M_hilum_lower_R",
              "VH_M_hilum_upper_R",
              "VH_M_right_lateral_bronchopulmonary_segment",
              "VH_M_right_medial_bronchopulmonary_segment",
              "VH_M_right_anterior_basal_bronchopulmonary_segment",
              "VH_M_right_lateral_basal_bronchopulmonary_segment",
              "VH_M_right_medial_basal_bronchopulmonary_segment",
              "VH_M_right_posterior_basal_bronchopulmonary_segment",
              "VH_M_right_superior_bronchopulmonary_segment",
              "VH_M_right_apical_bronchopulmonary_segment",
              "VH_M_right_posterior_bronchopulmonary_segment",
              "VH_M_right_anterior_bronchopulmonary_segment",
            ],
            icon: "🫁",
            description: "Source-defined right bronchopulmonary segment and hilum surfaces from the Visible Human Male-derived lung reference.",
            focusHint: "Right thoracic cavity",
            knowledgeGraphId: "UBERON:0002167",
            confidence: "source-defined",
          },
          {
            id: "intrapulmonary_bronchi",
            name: "Intrapulmonary Bronchi",
            aliases: ["lobar bronchi", "segmental bronchi", "bronchial cartilage"],
            meshNodeNames: [
              "VH_M_left_*",
              "VH_M_right_*",
              "VH_M_cartilage_of_the_lobar_bronchus_*",
              "VH_M_cartilage_of_the_tertiary_bronchus_*",
              "VH_M_bronchus",
            ],
            icon: "🌬️",
            description: "Source-defined lobar and segmental bronchi retained inside the HRA lung model.",
            focusHint: "Bilateral intrapulmonary airway tree",
            knowledgeGraphId: "UBERON:0002185",
            confidence: "source-defined",
          },
        ],
      },
      {
        id: "hra_main_bronchus_male_v1_1",
        name: "Main Bronchi",
        filePath: "/models/anatomy/respiratory/main_bronchus_hra_male_v1_1.glb",
        source: "Human Reference Atlas / HuBMAP",
        sourceType: "imaging-derived",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://cdn.humanatlas.io/hra-kg--staging/ref-organ/main-bronchus-male/v1.1/",
        sourceVersion: "v1.1",
        sourceChecksum: "1f1f50659daba678a5738af67d4fc8add5a113a744c93427280a19ce9e0c5755",
        license: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        attribution: "Kristen Browne and Heidi Schlehlein. 2024. 3D Reference Organ for Main Bronchus, Male v1.1. DOI: 10.48539/HBM373.XHXV.928",
        reviewStatus: "source-reviewed",
        structures: [
          {
            id: "main_bronchi",
            name: "Left & Right Main Bronchi",
            aliases: ["main bronchus", "primary bronchi", "bronchial cartilage"],
            meshNodeNames: [
              "VH_M_left_main_bronchus",
              "VH_M_cartilage_of_the_main_bronchus_L",
              "VH_M_right_main_bronchus",
              "VH_M_cartilage_of_the_main_bronchus_R",
            ],
            icon: "🌿",
            description: "Source-defined left and right main bronchial surfaces with their cartilage meshes.",
            focusHint: "Tracheal bifurcation and lung roots",
            knowledgeGraphId: "UBERON:0002185",
            confidence: "source-defined",
          },
        ],
      },
      {
        id: "hra_trachea_male_v1_1",
        name: "Trachea",
        filePath: "/models/anatomy/respiratory/trachea_hra_male_v1_1.glb",
        source: "Human Reference Atlas / HuBMAP",
        sourceType: "imaging-derived",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://cdn.humanatlas.io/hra-kg--staging/ref-organ/trachea-male/v1.1/",
        sourceVersion: "v1.1",
        sourceChecksum: "bca5616e505baff61dce1bbc31d6602eb72c112bcbe4531931e37e0c254ddd8d",
        license: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        attribution: "Kristen Browne and Heidi Schlehlein. 2024. 3D Reference Organ for Trachea, Male v1.1. DOI: 10.48539/HBM357.VGJC.676",
        reviewStatus: "source-reviewed",
        structures: [
          {
            id: "trachea",
            name: "Trachea, Cartilage & Carina",
            aliases: ["trachea", "tracheal cartilage", "carina"],
            meshNodeNames: ["VH_M_trachea", "VH_M_tracheal_cartilage", "VH_M_carina"],
            icon: "🌬️",
            description: "Source-defined tracheal surface, cartilage, and carina meshes.",
            focusHint: "Cervical and superior mediastinal airway",
            knowledgeGraphId: "UBERON:0003126",
            confidence: "source-defined",
          },
        ],
      },
    ],
    subOrgans: [
      {
        id: "left_lung_segments",
        name: "Left Lung Segments",
        icon: "🫁",
        description: "Source-defined left bronchopulmonary segments and hilum.",
        focusHint: "Left thoracic cavity",
      },
      {
        id: "right_lung_segments",
        name: "Right Lung Segments",
        icon: "🫁",
        description: "Source-defined right bronchopulmonary segments and hilum.",
        focusHint: "Right thoracic cavity",
      },
      {
        id: "intrapulmonary_bronchi",
        name: "Intrapulmonary Bronchi",
        icon: "🌿",
        description: "Lobar and segmental bronchi retained within the HRA lung model.",
        focusHint: "Bilateral intrapulmonary airway tree",
      },
      {
        id: "main_bronchi",
        name: "Main Bronchi",
        icon: "🌿",
        description: "Left and right main bronchi with source-defined cartilage.",
        focusHint: "Tracheal bifurcation",
      },
      {
        id: "trachea",
        name: "Trachea & Carina",
        icon: "🌬️",
        description: "Tracheal wall, cartilage, and carina surfaces.",
        focusHint: "Cervical and superior mediastinal airway",
      },
    ],
    overview: "Conducting airways and compliant alveolar parenchyma facilitating oxygen uptake and carbon dioxide elimination.",
    clinicalFocus: "Asthma, COPD, pneumonia, pulmonary fibrosis, and acute respiratory distress syndrome.",
  },

  skeletal: {
    id: "skeletal",
    name: "Skeletal System & Structural Framework",
    subtitle: "Axial & Appendicular Osteology, Protection & Locomotion",
    badge: "Structural Matrix",
    coverageLabel: "Whole skeleton reference",
    accentColor: "#64748B",
    primaryAssetPath: "/models/anatomy/skeletal/whole_skeleton_bodyparts3d_v4.glb",
    assets: [
      {
        id: "bodyparts3d_whole_skeleton_v4",
        name: "Whole Skeleton — Axial & Appendicular",
        filePath: "/models/anatomy/skeletal/whole_skeleton_bodyparts3d_v4.glb",
        source: "BodyParts3D v4.0 / Database Center for Life Science",
        sourceUpAxis: "z",
        sourceType: "anatomical-reference",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html",
        sourceVersion: "BodyParts3D 4.0 PART-OF tree, 99% polygon reduction",
        sourceChecksum: "9fbc713fffeee924a5a657d9813d84d7eb957bded63adb854931dd5e3eb61c97",
        license: "CC BY-SA 2.1 Japan (conservative classification from embedded OBJ notices)",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en",
        attribution: "BodyParts3D, © The Database Center for Life Science",
        reviewStatus: "not-reviewed",
        structures: [
          {
            id: "skull",
            name: "Skull",
            aliases: ["skull", "cranium"],
            meshNodeNames: ["BodyParts3D_skull_*"],
            icon: "💀",
            description: "Forty-three source surfaces mapped by the BodyParts3D PART-OF table to the skull.",
            focusHint: "Cephalic skeleton",
            knowledgeGraphId: "FMA:46565",
            confidence: "source-defined",
          },
          {
            id: "vertebral_column",
            name: "Vertebral Column",
            aliases: ["spine", "vertebrae"],
            meshNodeNames: ["BodyParts3D_vertebral_column_*"],
            icon: "🦴",
            description: "Forty-eight source surfaces mapped to the vertebral column, including its sacral and coccygeal components.",
            focusHint: "Posterior axial midline",
            knowledgeGraphId: "FMA:13478",
            confidence: "source-defined",
          },
          {
            id: "rib_cage",
            name: "Rib Cage & Sternum",
            aliases: ["ribcage", "ribs", "sternum"],
            meshNodeNames: ["BodyParts3D_rib_cage_*"],
            icon: "🛡️",
            description: "Forty-one source surfaces assigned to the rib-cage region after vertebral components are mapped separately.",
            focusHint: "Thoracic cage",
            knowledgeGraphId: "FMA:7480",
            confidence: "source-defined",
          },
          {
            id: "pelvic_skeleton",
            name: "Pelvic Skeleton",
            aliases: ["pelvis", "hip bones", "pelvic girdle"],
            meshNodeNames: ["BodyParts3D_pelvic_skeleton_*"],
            icon: "🦴",
            description: "Paired source hip-bone surfaces; the coccygeal surface remains classified with the vertebral column.",
            focusHint: "Inferior axial skeleton",
            knowledgeGraphId: "FMA:72062",
            confidence: "source-defined",
          },
          {
            id: "pectoral_girdles",
            name: "Pectoral Girdles",
            aliases: ["clavicles", "scapulae", "shoulder girdles"],
            meshNodeNames: ["BodyParts3D_pectoral_girdles_*"],
            icon: "🦴",
            description: "Application grouping of four source clavicle and scapula surfaces mapped to the paired pectoral girdles.",
            focusHint: "Superior thoracic appendicular attachments",
            knowledgeGraphId: "FMA:24163",
            confidence: "metadata-mapped",
          },
          {
            id: "upper_limbs",
            name: "Upper Limb Skeleton",
            aliases: ["arms", "upper limbs", "humerus", "radius", "ulna", "hands"],
            meshNodeNames: ["BodyParts3D_upper_limbs_*"],
            icon: "🦴",
            description: "Seventy-seven source surfaces covering paired free upper-limb bones from humeri through hands and digits.",
            focusHint: "Paired upper appendicular skeleton",
            knowledgeGraphId: "FMA:24880/FMA:24881",
            confidence: "metadata-mapped",
          },
          {
            id: "lower_limbs",
            name: "Lower Limb Skeleton",
            aliases: ["legs", "lower limbs", "femur", "tibia", "fibula", "feet"],
            meshNodeNames: ["BodyParts3D_lower_limbs_*"],
            icon: "🦴",
            description: "Sixty source surfaces covering paired free lower-limb bones from femora through feet and digits.",
            focusHint: "Paired lower appendicular skeleton",
            knowledgeGraphId: "FMA:24882/FMA:24883",
            confidence: "metadata-mapped",
          },
        ],
      },
    ],
    subOrgans: [
      {
        id: "skull",
        name: "Skull",
        icon: "💀",
        description: "Forty-three source-mapped cranial and facial skeletal surfaces.",
        focusHint: "Cephalic skeleton",
      },
      {
        id: "vertebral_column",
        name: "Vertebral Column",
        icon: "🦴",
        description: "Source-mapped vertebral, sacral, and coccygeal surfaces.",
        focusHint: "Posterior axial midline",
      },
      {
        id: "rib_cage",
        name: "Rib Cage & Sternum",
        icon: "🛡️",
        description: "Source-mapped rib-cage region with vertebrae separated into the spinal focus.",
        focusHint: "Thoracic cage",
      },
      {
        id: "pelvic_skeleton",
        name: "Pelvic Skeleton",
        icon: "🦴",
        description: "Paired hip-bone surfaces from the source skeletal mapping.",
        focusHint: "Inferior axial skeleton",
      },
      {
        id: "pectoral_girdles",
        name: "Pectoral Girdles",
        icon: "🦴",
        description: "Paired clavicles and scapulae grouped for viewer focus.",
        focusHint: "Superior thoracic attachments",
      },
      {
        id: "upper_limbs",
        name: "Upper Limb Skeleton",
        icon: "🦴",
        description: "Paired humeri, forearm, wrist, hand, and digit bone surfaces.",
        focusHint: "Upper appendicular skeleton",
      },
      {
        id: "lower_limbs",
        name: "Lower Limb Skeleton",
        icon: "🦴",
        description: "Paired femora, leg, ankle, foot, and digit bone surfaces.",
        focusHint: "Lower appendicular skeleton",
      },
    ],
    overview: "Rigid mineralized osseous framework supporting soft tissues, shielding vital viscera, and anchoring musculoskeletal levers.",
    clinicalFocus: "Osteoporosis, osteoarthritis, fractures, spondylolisthesis, and scoliosis.",
  },

  endocrine: {
    id: "endocrine",
    name: "Endocrine System & Hormonal Axis",
    subtitle: "Pituitary-Pineal-Adrenal-Pancreatic Axis",
    badge: "Hormonal Regulators",
    coverageLabel: "Partial gland collection",
    accentColor: "#EAB308",
    primaryAssetPath: "/models/anatomy/endocrine/endocrine_glands_bodyparts3d_v4.glb",
    assets: [
      {
        id: "bodyparts3d_endocrine_collection_v4",
        name: "Endocrine Gland Collection",
        filePath: "/models/anatomy/endocrine/endocrine_glands_bodyparts3d_v4.glb",
        source: "BodyParts3D v4.0 / Database Center for Life Science",
        sourceUpAxis: "z",
        sourceType: "anatomical-reference",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html",
        sourceVersion: "BodyParts3D 4.0 PART-OF tree, 99% polygon reduction",
        sourceChecksum: "9fbc713fffeee924a5a657d9813d84d7eb957bded63adb854931dd5e3eb61c97",
        license: "CC BY-SA 2.1 Japan (conservative classification from embedded OBJ notices)",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en",
        attribution: "BodyParts3D, © The Database Center for Life Science",
        reviewStatus: "not-reviewed",
        structures: [
          {
            id: "pituitary_gland",
            name: "Pituitary Gland",
            aliases: ["pituitary", "hypophysis"],
            meshNodeNames: ["BodyParts3D_pituitary_gland_FJ1796"],
            icon: "🔴",
            description: "Source-defined pituitary surface mapped to FMA13889 in the BodyParts3D PART-OF data.",
            focusHint: "Sellar region",
            knowledgeGraphId: "FMA:13889",
            confidence: "source-defined",
          },
          {
            id: "pineal_body",
            name: "Pineal Body",
            aliases: ["pineal gland", "epiphysis cerebri"],
            meshNodeNames: ["BodyParts3D_pineal_body_FJ1795"],
            icon: "✨",
            description: "Source-defined pineal body surface mapped to FMA62033.",
            focusHint: "Posterior diencephalic midline",
            knowledgeGraphId: "FMA:62033",
            confidence: "source-defined",
          },
          {
            id: "adrenal_gland_left",
            name: "Left Adrenal Gland",
            aliases: ["left adrenal", "left suprarenal gland"],
            meshNodeNames: ["BodyParts3D_adrenal_gland_left_FJ3129"],
            icon: "🟠",
            description: "Source-defined left adrenal gland surface mapped to FMA15630.",
            focusHint: "Superior pole of left kidney",
            knowledgeGraphId: "FMA:15630",
            confidence: "source-defined",
          },
          {
            id: "adrenal_gland_right",
            name: "Right Adrenal Gland",
            aliases: ["right adrenal", "right suprarenal gland"],
            meshNodeNames: ["BodyParts3D_adrenal_gland_right_FJ3130"],
            icon: "🟠",
            description: "Source-defined right adrenal gland surface mapped to FMA15629.",
            focusHint: "Superior pole of right kidney",
            knowledgeGraphId: "FMA:15629",
            confidence: "source-defined",
          },
          {
            id: "pancreas_endocrine",
            name: "Pancreas",
            aliases: ["pancreas", "pancreatic parenchyma", "pancreatic duct"],
            meshNodeNames: ["BodyParts3D_pancreas_endocrine_*"],
            icon: "🟡",
            description: "Four source pancreatic surfaces retained because the BodyParts3D PART-OF data associates them with the endocrine system.",
            focusHint: "Retroperitoneal upper abdomen",
            knowledgeGraphId: "FMA:7198",
            confidence: "source-defined",
          },
        ],
      },
    ],
    subOrgans: [
      {
        id: "pituitary_gland",
        name: "Pituitary Gland",
        icon: "🔴",
        description: "Source-defined pituitary reference surface.",
        focusHint: "Sellar region",
      },
      {
        id: "pineal_body",
        name: "Pineal Body",
        icon: "✨",
        description: "Source-defined pineal body surface.",
        focusHint: "Posterior diencephalic midline",
      },
      {
        id: "adrenal_gland_left",
        name: "Left Adrenal",
        icon: "🟠",
        description: "Source-defined left adrenal gland surface.",
        focusHint: "Superior pole of left kidney",
      },
      {
        id: "adrenal_gland_right",
        name: "Right Adrenal",
        icon: "🟠",
        description: "Source-defined right adrenal gland surface.",
        focusHint: "Superior pole of right kidney",
      },
      {
        id: "pancreas_endocrine",
        name: "Pancreas",
        icon: "🟡",
        description: "Source-mapped pancreatic surfaces included in the endocrine collection.",
        focusHint: "Retroperitoneal upper abdomen",
      },
    ],
    overview: "Ductless endocrine glandular network coordinating hormonal signal cascades across systemic target receptors.",
    clinicalFocus: "Pituitary adenomas, adrenal insufficiency or hyperfunction, pancreatic endocrine disorders, and circadian dysregulation.",
  },

  // Supporting 5 systems registered in the modular architecture
  muscular: {
    id: "muscular",
    name: "Muscular System & Biomechanics",
    subtitle: "Skeletal Muscle Fascicles, Tendons & Motor Units",
    badge: "Kinetic Drive",
    coverageLabel: "Whole-body muscle reference",
    accentColor: "#EF4444",
    primaryAssetPath: "/models/anatomy/muscular/muscular_system_bodyparts3d_v4.glb",
    assets: [
      {
        id: "bodyparts3d_muscular_system_v4",
        name: "Whole-body Skeletal Musculature",
        filePath: "/models/anatomy/muscular/muscular_system_bodyparts3d_v4.glb",
        source: "BodyParts3D v4.0 / Database Center for Life Science",
        sourceUpAxis: "z",
        sourceType: "anatomical-reference",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html",
        sourceVersion: "BodyParts3D 4.0 IS-A tree, 99% polygon reduction",
        sourceChecksum: "40665852c49f218326590e204db91064a1ecfc3c6f8cbd7bbbcaac62c7cd409e",
        license: "CC BY-SA 2.1 Japan (conservative classification from embedded OBJ notices)",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en",
        attribution: "BodyParts3D, © The Database Center for Life Science",
        reviewStatus: "not-reviewed",
        structures: [
          {
            id: "head_neck_muscles",
            name: "Head and Neck Muscles",
            aliases: ["facial muscles", "masticatory muscles", "neck muscles"],
            meshNodeNames: ["BodyParts3D_head_neck_muscles_*"],
            icon: "🗣️",
            description: "Seventy-seven source muscle surfaces classified under the head and neck muscle branches.",
            focusHint: "Craniofacial and cervical regions",
            knowledgeGraphId: "FMA:9616",
            confidence: "metadata-mapped",
          },
          {
            id: "axial_trunk_muscles",
            name: "Axial and Trunk Muscles",
            aliases: ["thoracic muscles", "abdominal muscles", "back muscles", "pelvic muscles"],
            meshNodeNames: ["BodyParts3D_axial_trunk_muscles_*"],
            icon: "🫁",
            description: "Seventy-six source muscle surfaces spanning thorax, abdomen, pelvis, vertebral column, and trunk.",
            focusHint: "Thorax, abdomen, back, and pelvis",
            knowledgeGraphId: "FMA:58274",
            confidence: "metadata-mapped",
          },
          {
            id: "upper_limb_muscles",
            name: "Upper Limb Muscles",
            aliases: ["arm muscles", "forearm muscles", "hand muscles"],
            meshNodeNames: ["BodyParts3D_upper_limb_muscles_*"],
            icon: "💪",
            description: "Seventy-eight source surfaces in the upper-limb muscle class.",
            focusHint: "Shoulder girdle through hands",
            knowledgeGraphId: "FMA:9621",
            confidence: "source-defined",
          },
          {
            id: "lower_limb_muscles",
            name: "Lower Limb Muscles",
            aliases: ["thigh muscles", "leg muscles", "foot muscles"],
            meshNodeNames: ["BodyParts3D_lower_limb_muscles_*"],
            icon: "🦵",
            description: "Ninety-two source surfaces in the lower-limb muscle class.",
            focusHint: "Hip through feet",
            knowledgeGraphId: "FMA:9622",
            confidence: "source-defined",
          },
        ],
      },
    ],
    subOrgans: [
      { id: "head_neck_muscles", name: "Head & Neck", icon: "🗣️", description: "Source-mapped craniofacial and cervical muscle surfaces.", focusHint: "Craniofacial and cervical regions" },
      { id: "axial_trunk_muscles", name: "Axial & Trunk", icon: "🫁", description: "Source-mapped thoracic, abdominal, pelvic, and vertebral muscle surfaces.", focusHint: "Thorax, abdomen, back, and pelvis" },
      { id: "upper_limb_muscles", name: "Upper Limbs", icon: "💪", description: "Source-defined upper-limb muscle surfaces.", focusHint: "Shoulder girdle through hands" },
      { id: "lower_limb_muscles", name: "Lower Limbs", icon: "🦵", description: "Source-defined lower-limb muscle surfaces.", focusHint: "Hip through feet" },
    ],
    overview: "Contractile muscular apparatus generating kinetic locomotion, postural stability, and heat production.",
    clinicalFocus: "Myopathies, fibromyalgia, sarcopenia, tendinopathies, and myasthenia gravis.",
  },

  lymphatic: {
    id: "lymphatic",
    name: "Lymphatic & Immune Defense System",
    subtitle: "Regional Lymph Nodes & Lymphoid Organ Defense",
    badge: "Immune Sentinel",
    coverageLabel: "Nodes and lymphoid organs; no vessels",
    accentColor: "#10B981",
    primaryAssetPath: "/models/anatomy/lymphatic/lymphatic_nodes_organs_zanatomy.glb",
    assets: [
      {
        id: "zanatomy_lymphatic_nodes_organs",
        name: "Lymph Nodes, Spleen, Tonsils and Thymus",
        filePath: "/models/anatomy/lymphatic/lymphatic_nodes_organs_zanatomy.glb",
        source: "Z-Anatomy",
        sourceType: "anatomical-reference",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://github.com/LluisV/Z-Anatomy/tree/PC-Version/Resources/Models/FBX",
        sourceVersion: "PC-Version @ 6c7f9016bd5899ac8edafd31b9900c151df42ed6",
        sourceChecksum: "310ff82f502f4f3a79e85f99ddc2009bba9514338119af9edff87b20cf1b3609",
        license: "CC BY-SA 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
        attribution: "Z-Anatomy contributors; derived from BodyParts3D, © The Database Center for Life Science",
        reviewStatus: "not-reviewed",
        structures: [
          {
            id: "head_neck_nodes",
            name: "Head and Neck Lymph Nodes",
            aliases: ["cervical lymph nodes", "facial lymph nodes", "parotid lymph nodes"],
            meshNodeNames: ["ZAnatomy_head_neck_nodes_*"],
            icon: "🟢",
            description: "Forty-two source meshes covering modeled lymph-node groups of the head and neck.",
            focusHint: "Head and cervical chains",
            knowledgeGraphId: "FMA:5034",
            confidence: "metadata-mapped",
          },
          {
            id: "thoracic_nodes",
            name: "Thoracic Lymph Nodes",
            aliases: ["mediastinal nodes", "tracheobronchial nodes", "pulmonary nodes"],
            meshNodeNames: ["ZAnatomy_thoracic_nodes_*"],
            icon: "🫁",
            description: "Sixteen source meshes covering modeled mediastinal, pulmonary, and parietal thoracic node groups.",
            focusHint: "Thoracic and mediastinal chains",
            knowledgeGraphId: "FMA:5034",
            confidence: "metadata-mapped",
          },
          {
            id: "abdominal_nodes",
            name: "Abdominal Lymph Nodes",
            aliases: ["mesenteric nodes", "lumbar nodes", "coeliac nodes"],
            meshNodeNames: ["ZAnatomy_abdominal_nodes_*"],
            icon: "🟩",
            description: "Thirty-two source meshes covering modeled parietal and visceral abdominal node groups.",
            focusHint: "Abdominal and mesenteric chains",
            knowledgeGraphId: "FMA:5034",
            confidence: "metadata-mapped",
          },
          {
            id: "pelvic_nodes",
            name: "Pelvic Lymph Nodes",
            aliases: ["iliac nodes", "sacral nodes", "pelvic lymph nodes"],
            meshNodeNames: ["ZAnatomy_pelvic_nodes_*"],
            icon: "🟢",
            description: "Twenty-eight source meshes covering modeled iliac, sacral, gluteal, vesical, and pararectal node groups.",
            focusHint: "Pelvic lymph-node chains",
            knowledgeGraphId: "FMA:5034",
            confidence: "metadata-mapped",
          },
          {
            id: "upper_limb_nodes",
            name: "Upper Limb Lymph Nodes",
            aliases: ["axillary nodes", "cubital nodes", "brachial nodes"],
            meshNodeNames: ["ZAnatomy_upper_limb_nodes_*"],
            icon: "💪",
            description: "Twenty source meshes covering modeled axillary, infraclavicular, brachial, and cubital node groups.",
            focusHint: "Axillary and upper-limb chains",
            knowledgeGraphId: "FMA:5034",
            confidence: "metadata-mapped",
          },
          {
            id: "lower_limb_nodes",
            name: "Lower Limb Lymph Nodes",
            aliases: ["inguinal nodes", "popliteal nodes", "tibial nodes"],
            meshNodeNames: ["ZAnatomy_lower_limb_nodes_*"],
            icon: "🦵",
            description: "Twenty source meshes covering modeled inguinal, popliteal, tibial, and fibular node groups.",
            focusHint: "Inguinal and lower-limb chains",
            knowledgeGraphId: "FMA:5034",
            confidence: "metadata-mapped",
          },
          {
            id: "spleen",
            name: "Spleen",
            aliases: ["splenic organ", "splenic pulp"],
            meshNodeNames: ["ZAnatomy_spleen_*"],
            icon: "🛡️",
            description: "Source-defined whole-spleen surface retained from the Z-Anatomy lymphoid hierarchy.",
            focusHint: "Left hypochondrium",
            knowledgeGraphId: "FMA:7196",
            confidence: "source-defined",
          },
          {
            id: "tonsils",
            name: "Palatine Tonsils",
            aliases: ["tonsils", "left palatine tonsil", "right palatine tonsil"],
            meshNodeNames: ["ZAnatomy_tonsils_*"],
            icon: "👄",
            description: "Bilateral source-defined palatine tonsil meshes from the modeled pharyngeal lymphoid ring.",
            focusHint: "Lateral oropharynx",
            knowledgeGraphId: "FMA:54974/FMA:54973",
            confidence: "source-defined",
          },
          {
            id: "thymus",
            name: "Thymus",
            aliases: ["thymic lobes", "left thymic lobe", "right thymic lobe"],
            meshNodeNames: ["ZAnatomy_thymus_*"],
            icon: "🌱",
            description: "Bilateral source-defined thymic lobes presented as a combined viewer focus.",
            focusHint: "Anterior superior mediastinum",
            knowledgeGraphId: "FMA:9607",
            confidence: "source-defined",
          },
        ],
      },
    ],
    subOrgans: [
      { id: "head_neck_nodes", name: "Head & Neck Nodes", icon: "🟢", description: "Source-mapped head and cervical lymph-node groups.", focusHint: "Head and neck" },
      { id: "thoracic_nodes", name: "Thoracic Nodes", icon: "🫁", description: "Source-mapped thoracic and mediastinal lymph-node groups.", focusHint: "Thorax and mediastinum" },
      { id: "abdominal_nodes", name: "Abdominal Nodes", icon: "🟩", description: "Source-mapped parietal and visceral abdominal lymph-node groups.", focusHint: "Abdomen and mesentery" },
      { id: "pelvic_nodes", name: "Pelvic Nodes", icon: "🟢", description: "Source-mapped pelvic lymph-node groups.", focusHint: "Pelvis" },
      { id: "upper_limb_nodes", name: "Upper Limb Nodes", icon: "💪", description: "Source-mapped axillary and upper-limb node groups.", focusHint: "Upper limbs and axillae" },
      { id: "lower_limb_nodes", name: "Lower Limb Nodes", icon: "🦵", description: "Source-mapped inguinal and lower-limb node groups.", focusHint: "Lower limbs and groins" },
      { id: "spleen", name: "Spleen", icon: "🛡️", description: "Source-defined whole-organ surface; microscopic splenic pulp is not separately modeled.", focusHint: "Left hypochondrium" },
      { id: "tonsils", name: "Palatine Tonsils", icon: "👄", description: "Source-defined bilateral palatine tonsil surfaces.", focusHint: "Lateral oropharynx" },
      { id: "thymus", name: "Thymus", icon: "🌱", description: "Source-defined bilateral thymic-lobe surfaces.", focusHint: "Anterior superior mediastinum" },
    ],
    overview: "Whole-body lymph-node and lymphoid-organ reference covering 158 regional node meshes, spleen, bilateral palatine tonsils, and bilateral thymic lobes. Lymphatic vessels, trunks, ducts, and marrow are not modeled in this source asset.",
    clinicalFocus: "Lymphedema, lymphadenopathy, lymphoma, and autoimmune conditions.",
  },

  reproductive: {
    id: "reproductive",
    name: "Reproductive & Gonadal System",
    subtitle: "Gametogenesis, Gonadal Steroidogenesis & Uterine Physiology",
    badge: "Generative Axis",
    coverageLabel: "Multi-organ reproductive set",
    accentColor: "#EC4899",
    primaryAssetPath: "/models/anatomy/reproductive/uterus_hra_female_v1_2.glb",
    assets: [
      {
        id: "hra_uterus_female_v1_2",
        name: "Uterus, Female",
        filePath: "/models/anatomy/reproductive/uterus_hra_female_v1_2.glb",
        source: "Human Reference Atlas / HuBMAP",
        sourceType: "imaging-derived",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://cdn.humanatlas.io/hra-kg--staging/ref-organ/uterus-female/v1.2/",
        sourceVersion: "v1.2",
        sourceChecksum: "41014d2b222c2dbbe8d1cc38206b0099ce76d79659a9fdea9f28b8c7d669b864",
        license: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        attribution: "Kristen Browne and Heidi Schlehlein. 2024. 3D Reference Organ for Uterus, Female v1.2. DOI: 10.48539/HBM627.VTKD.892",
        reviewStatus: "source-reviewed",
        structures: [
          {
            id: "uterus",
            name: "Uterus and Cervix",
            aliases: ["uterus", "uterine body", "fundus", "cervix"],
            meshNodeNames: ["VH_F_*"],
            icon: "🌸",
            description: "Visible Human Female-derived uterus with body, fundus, walls, cornua, lower segment, and cervical landmarks.",
            focusHint: "Female true pelvis",
            knowledgeGraphId: "UBERON:0000995",
            confidence: "source-defined",
          },
        ],
      },
      {
        id: "hra_ovary_female_left_v1_1",
        name: "Left Ovary, Female",
        filePath: "/models/anatomy/reproductive/ovary_hra_female_left_v1_1.glb",
        source: "Human Reference Atlas / HuBMAP",
        sourceType: "imaging-derived",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://cdn.humanatlas.io/hra-kg--staging/ref-organ/ovary-female-left/v1.1/",
        sourceVersion: "v1.1",
        sourceChecksum: "ed91414a667dec5e4e14aeaa2f8641731f06725dbc914bc0da3dd8b5d77f5062",
        license: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        attribution: "Kristen Browne and Heidi Schlehlein. 2022. 3D Reference Organ for Ovary, Female, Left v1.1. DOI: 10.48539/HBM499.JLMB.357",
        reviewStatus: "source-reviewed",
        structures: [
          {
            id: "ovary_left",
            name: "Left Ovary",
            aliases: ["left ovary", "left female gonad"],
            meshNodeNames: ["VH_F_left_ovary"],
            icon: "🟣",
            description: "Visible Human Female-derived left ovarian reference surface.",
            focusHint: "Left ovarian fossa",
            knowledgeGraphId: "FMA:7214",
            confidence: "source-defined",
          },
        ],
      },
      {
        id: "hra_ovary_female_right_v1_1",
        name: "Right Ovary, Female",
        filePath: "/models/anatomy/reproductive/ovary_hra_female_right_v1_1.glb",
        source: "Human Reference Atlas / HuBMAP",
        sourceType: "imaging-derived",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://cdn.humanatlas.io/hra-kg--staging/ref-organ/ovary-female-right/v1.1/",
        sourceVersion: "v1.1",
        sourceChecksum: "99cc2b91602feacaee08ec1771b993fc0f8b0e32a08bdd7fd6b990a6736aa53b",
        license: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        attribution: "Kristen Browne and Heidi Schlehlein. 2022. 3D Reference Organ for Ovary, Female, Right v1.1. DOI: 10.48539/HBM453.QTZX.449",
        reviewStatus: "source-reviewed",
        structures: [
          {
            id: "ovary_right",
            name: "Right Ovary",
            aliases: ["right ovary", "right female gonad"],
            meshNodeNames: ["VH_F_right_ovary"],
            icon: "🟣",
            description: "Visible Human Female-derived right ovarian reference surface.",
            focusHint: "Right ovarian fossa",
            knowledgeGraphId: "FMA:7213",
            confidence: "source-defined",
          },
        ],
      },
      {
        id: "hra_fallopian_tube_female_left_v1_1",
        name: "Left Fallopian Tube, Female",
        filePath: "/models/anatomy/reproductive/fallopian_tube_hra_female_left_v1_1.glb",
        source: "Human Reference Atlas / HuBMAP",
        sourceType: "imaging-derived",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://cdn.humanatlas.io/hra-kg--staging/ref-organ/fallopian-tube-female-left/v1.1/",
        sourceVersion: "v1.1",
        sourceChecksum: "5025453048a83c26393b866bc69859a255b4c38816f34ed3a196bfe7d4f33dd1",
        license: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        attribution: "Kristen Browne and Heidi Schlehlein. 2022. 3D Reference Organ for Fallopian Tube, Female, Left v1.1. DOI: 10.48539/HBM887.HZKB.637",
        reviewStatus: "source-reviewed",
        structures: [
          {
            id: "fallopian_tube_left",
            name: "Left Fallopian Tube",
            aliases: ["left uterine tube", "left oviduct"],
            meshNodeNames: ["VH_F_*"],
            icon: "〰️",
            description: "Visible Human Female-derived left tube with ampulla, isthmus, fimbriae, and infundibulum.",
            focusHint: "Left uterine adnexa",
            knowledgeGraphId: "UBERON:0001303",
            confidence: "source-defined",
          },
        ],
      },
      {
        id: "hra_fallopian_tube_female_right_v1_1",
        name: "Right Fallopian Tube, Female",
        filePath: "/models/anatomy/reproductive/fallopian_tube_hra_female_right_v1_1.glb",
        source: "Human Reference Atlas / HuBMAP",
        sourceType: "imaging-derived",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://cdn.humanatlas.io/hra-kg--staging/ref-organ/fallopian-tube-female-right/v1.1/",
        sourceVersion: "v1.1",
        sourceChecksum: "17aef41a430e068705dc21ac8ccf746a74f14f47ffc1a31908198b0b026849df",
        license: "CC BY 4.0",
        licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
        attribution: "Kristen Browne and Heidi Schlehlein. 2022. 3D Reference Organ for Fallopian Tube, Female, Right v1.1. DOI: 10.48539/HBM875.FCDP.878",
        reviewStatus: "source-reviewed",
        structures: [
          {
            id: "fallopian_tube_right",
            name: "Right Fallopian Tube",
            aliases: ["right uterine tube", "right oviduct"],
            meshNodeNames: ["VH_F_*"],
            icon: "〰️",
            description: "Visible Human Female-derived right tube with ampulla, isthmus, fimbriae, and infundibulum.",
            focusHint: "Right uterine adnexa",
            knowledgeGraphId: "UBERON:0001302",
            confidence: "source-defined",
          },
        ],
      },
      {
        id: "bodyparts3d_male_reproductive_v4",
        name: "Male Reproductive Structures",
        filePath: "/models/anatomy/reproductive/male_reproductive_bodyparts3d_v4.glb",
        source: "BodyParts3D v4.0 / Database Center for Life Science",
        sourceUpAxis: "z",
        sourceType: "anatomical-reference",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html",
        sourceVersion: "BodyParts3D 4.0 IS-A tree, 99% polygon reduction",
        sourceChecksum: "40665852c49f218326590e204db91064a1ecfc3c6f8cbd7bbbcaac62c7cd409e",
        license: "CC BY-SA 2.1 Japan (conservative classification from embedded OBJ notices)",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en",
        attribution: "BodyParts3D, © The Database Center for Life Science",
        reviewStatus: "not-reviewed",
        structures: [
          {
            id: "male_reproductive_organs",
            name: "Male Reproductive Organs",
            aliases: ["testes", "epididymides", "deferent ducts", "seminal vesicles", "prostate", "penile erectile tissues"],
            meshNodeNames: ["BodyParts3D_*"],
            icon: "♂️",
            description: "Twelve source-mapped male reproductive surfaces in shared BodyParts3D coordinates.",
            focusHint: "Male pelvis and external genital region",
            knowledgeGraphId: "FMA:45664",
            confidence: "metadata-mapped",
          },
        ],
      },
    ],
    subOrgans: [
      { id: "uterus", name: "Uterus", icon: "🌸", description: "Female HRA uterus and cervical landmarks.", focusHint: "Female true pelvis" },
      { id: "ovary_left", name: "Left Ovary", icon: "🟣", description: "Female HRA left ovarian surface.", focusHint: "Left ovarian fossa" },
      { id: "ovary_right", name: "Right Ovary", icon: "🟣", description: "Female HRA right ovarian surface.", focusHint: "Right ovarian fossa" },
      { id: "fallopian_tube_left", name: "Left Tube", icon: "〰️", description: "Female HRA left uterine tube regions.", focusHint: "Left uterine adnexa" },
      { id: "fallopian_tube_right", name: "Right Tube", icon: "〰️", description: "Female HRA right uterine tube regions.", focusHint: "Right uterine adnexa" },
      { id: "male_reproductive_organs", name: "Male Organs", icon: "♂️", description: "Separately labeled BodyParts3D male reproductive collection.", focusHint: "Male pelvic and external genital regions" },
    ],
    overview: "Sex-specific reproductive reference organs. Female HRA assets and the male BodyParts3D collection remain separate and are not presented as one assembled body.",
    clinicalFocus: "PCOS, endometriosis, uterine fibroids, infertility, and gonadal hypogonadism.",
  },

  integumentary: {
    id: "integumentary",
    name: "Integumentary System & Skin Barrier",
    subtitle: "Gross Skin Envelope & Modeled Hair Appendages",
    badge: "Barrier Armor",
    coverageLabel: "Whole-body surface envelope",
    accentColor: "#F97316",
    primaryAssetPath: "/models/anatomy/integumentary/skin_hair_bodyparts3d_v4.glb",
    assets: [
      {
        id: "bodyparts3d_integumentary_v4",
        name: "Skin and Modeled Hair Appendages",
        filePath: "/models/anatomy/integumentary/skin_hair_bodyparts3d_v4.glb",
        source: "BodyParts3D v4.0 / Database Center for Life Science",
        sourceUpAxis: "z",
        sourceType: "anatomical-reference",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html",
        sourceVersion: "BodyParts3D 4.0 IS-A tree, 99% polygon reduction",
        sourceChecksum: "40665852c49f218326590e204db91064a1ecfc3c6f8cbd7bbbcaac62c7cd409e",
        license: "CC BY-SA 2.1 Japan (conservative classification from embedded OBJ notices)",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en",
        attribution: "BodyParts3D, © The Database Center for Life Science",
        reviewStatus: "not-reviewed",
        structures: [
          {
            id: "skin_surface",
            name: "Skin Surface",
            aliases: ["skin", "cutaneous envelope", "body surface"],
            meshNodeNames: ["BodyParts3D_skin_surface_*"],
            icon: "🧍",
            description: "Source-defined whole-body gross skin envelope; microscopic layers are not separated.",
            focusHint: "External body surface",
            knowledgeGraphId: "FMA:7163",
            confidence: "source-defined",
          },
          {
            id: "hair_appendages",
            name: "Modeled Hair Appendages",
            aliases: ["head hair", "eyebrows", "pubic hair"],
            meshNodeNames: ["BodyParts3D_hair_appendages_*"],
            icon: "💇",
            description: "Source-defined eyebrow, head-hair, and pubic-hair surfaces grouped for viewer focus.",
            focusHint: "Head, face, and pubic region",
            knowledgeGraphId: "FMA:53667",
            confidence: "metadata-mapped",
          },
        ],
      },
    ],
    subOrgans: [
      { id: "skin_surface", name: "Skin Surface", icon: "🧍", description: "Whole-body gross skin surface; epidermis and dermis are not separately segmented.", focusHint: "External body surface" },
      { id: "hair_appendages", name: "Hair Appendages", icon: "💇", description: "Modeled head hair, eyebrows, and pubic hair; follicles and glands are not represented.", focusHint: "Head, face, and pubic region" },
    ],
    overview: "Gross cutaneous envelope with the hair structures available in the selected source release. Microscopic layers, glands, follicles, nails, and tactile receptors are not modeled.",
    clinicalFocus: "Atopic dermatitis, psoriasis, eczema, acne vulgaris, and melanoma.",
  },

  sensory: {
    id: "sensory",
    name: "Sensory Organs & Special Senses",
    subtitle: "Bilateral Ocular Anatomy & External Ear Surfaces",
    badge: "Perception Array",
    coverageLabel: "Partial: eyes and external ears",
    accentColor: "#3B82F6",
    primaryAssetPath: "/models/anatomy/sensory/ocular_external_ear_bodyparts3d_v4.glb",
    assets: [
      {
        id: "bodyparts3d_sensory_collection_v4",
        name: "Ocular Structures and External Ears",
        filePath: "/models/anatomy/sensory/ocular_external_ear_bodyparts3d_v4.glb",
        source: "BodyParts3D v4.0 / Database Center for Life Science",
        sourceUpAxis: "z",
        sourceType: "anatomical-reference",
        productionEligible: false,
        provenanceStatus: "source-verified",
        sourceUrl: "https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html",
        sourceVersion: "BodyParts3D 4.0 IS-A tree, 99% polygon reduction",
        sourceChecksum: "40665852c49f218326590e204db91064a1ecfc3c6f8cbd7bbbcaac62c7cd409e",
        license: "CC BY-SA 2.1 Japan (conservative classification from embedded OBJ notices)",
        licenseUrl: "https://creativecommons.org/licenses/by-sa/2.1/jp/deed.en",
        attribution: "BodyParts3D, © The Database Center for Life Science",
        reviewStatus: "not-reviewed",
        structures: [
          {
            id: "ocular_structures",
            name: "Bilateral Ocular Structures",
            aliases: ["eyes", "corneas", "lenses", "irises", "retinas", "optic nerves"],
            meshNodeNames: ["BodyParts3D_ocular_structures_*"],
            icon: "👁️",
            description: "Twenty-two bilateral ocular surfaces covering major gross layers, optical structures, and optic nerves.",
            focusHint: "Bilateral bony orbits",
            knowledgeGraphId: "FMA:12514/FMA:12515",
            confidence: "metadata-mapped",
          },
          {
            id: "external_ears",
            name: "External Ears",
            aliases: ["auricles", "pinnae", "outer ears"],
            meshNodeNames: ["BodyParts3D_external_ears_*"],
            icon: "👂",
            description: "Source-defined bilateral external-ear surface; middle and inner ear are not modeled.",
            focusHint: "Bilateral lateral head",
            knowledgeGraphId: "FMA:52781",
            confidence: "source-defined",
          },
        ],
      },
    ],
    subOrgans: [
      { id: "ocular_structures", name: "Ocular Structures", icon: "👁️", description: "Corneas, lenses, irises, sclerae, choroids, ciliary regions, retinas, chambers, and optic nerves.", focusHint: "Bilateral bony orbits" },
      { id: "external_ears", name: "External Ears", icon: "👂", description: "Bilateral external-ear surface; auditory canal, ossicles, cochlea, and vestibular labyrinth are not represented.", focusHint: "Bilateral lateral head" },
    ],
    overview: "Gross bilateral ocular anatomy and external-ear surfaces available in the selected release. Cochlear, vestibular, organ-of-Corti, and olfactory structures are not modeled.",
    clinicalFocus: "Glaucoma, macular degeneration, sensorineural hearing loss, vertigo, and tinnitus.",
  },
};
