import { CdssRecommendation } from "../types";
import { PatientId } from "../types/branded";

export interface CdssDomainModel extends CdssRecommendation {
  patientId: PatientId;
  advisoryDisclaimer: string;
  isAdvisoryConfirmed: boolean;
}

/**
 * Standard disclaimer to be included on all AI-supported recommendations
 */
export const CDSS_ADVISORY_DISCLAIMER = 
  "Clinical Decision Support: This suggestion is generated by AI algorithms and is intended solely for clinician review. This is not a confirmed diagnosis. Final therapeutic decisions remain the sole responsibility of the attending physician.";

/**
 * Normalizes a raw recommendation to include appropriate clinical advisories
 */
export function enforceCdssAdvisory(rec: CdssRecommendation): CdssDomainModel {
  return {
    ...rec,
    patientId: rec.patientId as PatientId,
    advisoryDisclaimer: CDSS_ADVISORY_DISCLAIMER,
    isAdvisoryConfirmed: true,
  };
}
