import { CitationRecord } from "../types";

export const CITATIONS: CitationRecord[] = [
  {
    id: "CIT-0001",
    title: "Efficacy of Constitutional Homeopathy in Gastroesophageal Reflux Disease (GERD)",
    authors: ["Jethwani N.", "Sharma R."],
    journal: "International Journal of Homeopathic Research",
    year: 2024,
    citationStyle: "AMA",
    category: "Primary-Research",
    sourceIdentifier: "UNVERIFIED-CIT-0001",
    sourceAuthority: "external-secondary",
    verificationStatus: "disputed",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl: "https://pubmed.ncbi.nlm.nih.gov/34892019/",
    verificationNotes:
      "The stored PubMed identifier resolves to an unrelated neuroimaging paper, and the stored DOI could not be matched in PubMed.",
    scopeTags: ["gerd", "homeopathy", "unverified-research"]
  },
  {
    id: "CIT-0002",
    title: "Individualized Homeopathic Treatment for Atopic Dermatitis: A Cohort Study",
    authors: ["Witt C. M.", "Lüdtke R."],
    journal: "Complementary Medicine Research",
    year: 2019,
    citationStyle: "AMA",
    category: "Primary-Research",
    sourceIdentifier: "UNVERIFIED-CIT-0002",
    sourceAuthority: "external-secondary",
    verificationStatus: "disputed",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl: "https://pubmed.ncbi.nlm.nih.gov/19729965/",
    verificationNotes:
      "The stored DOI resolves to an unrelated nephrology paper and the stored PubMed identifier resolves to an unrelated fetal-anemia paper.",
    scopeTags: ["atopic-dermatitis", "homeopathy", "unverified-research"]
  },
  {
    id: "CIT-0003",
    title: "TSH Reference Intervals and Homeopathic Prescribing Mappings",
    authors: ["Miller D."],
    journal: "Clinical Endocrinology Review",
    year: 2021,
    citationStyle: "AMA",
    category: "Primary-Research",
    sourceIdentifier: "UNVERIFIED-CIT-0003",
    sourceAuthority: "external-secondary",
    verificationStatus: "disputed",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl: "https://pubmed.ncbi.nlm.nih.gov/34490640/",
    verificationNotes:
      "The stored DOI resolves to an unrelated neonatal bone-mass paper and the stored PubMed identifier resolves to an unrelated outbreak report.",
    scopeTags: ["thyroid", "homeopathy", "unverified-research"]
  },
  {
    id: "CIT-0004",
    title: "Materia Medica Pura",
    authors: ["Hahnemann S."],
    journal: "Adolph Arnold",
    year: 1811,
    citationStyle: "Traditional",
    category: "Materia-Medica",
    canonicalUrl: "https://archive.org/details/materiamedicapu00dudggoog",
    sourceIdentifier: "IA-MATERIAMEDICAPU00DUDGGOOG",
    sourceAuthority: "external-secondary",
    verificationStatus: "verified",
    verifiedAt: "2026-07-30",
    verificationEvidenceUrl:
      "https://archive.org/details/materiamedicapu00dudggoog",
    verificationNotes:
      "The linked 1880 Dudgeon/Hughes English edition verifies the bibliographic identity of the earlier work. It may support traditional-use or historical description only; it is not modern clinical efficacy evidence.",
    scopeTags: ["traditional-use", "materia-medica", "historical-reference", "hahnemann"]
  },
  {
    id: "CIT-0005",
    title: "Lectures on Homoeopathic Materia Medica",
    authors: ["Kent J. T."],
    journal: "Boericke & Tafel",
    year: 1905,
    citationStyle: "Traditional",
    category: "Materia-Medica",
    canonicalUrl: "https://archive.org/details/lecturesonhomoeo00kent",
    sourceIdentifier: "IA-LECTURESONHOMOEO00KENT",
    sourceAuthority: "external-secondary",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl:
      "https://archive.org/details/lecturesonhomoeo00kent",
    verificationNotes:
      "Bibliographic identity is verified for traditional-source description only; it is not modern clinical efficacy evidence.",
    scopeTags: ["traditional-use", "materia-medica", "kent"]
  },
  {
    id: "CIT-0006",
    title: "Pocket Manual of Homoeopathic Materia Medica",
    authors: ["Boericke W."],
    journal: "Boericke & Runyon",
    year: 1901,
    citationStyle: "Traditional",
    category: "Materia-Medica",
    canonicalUrl: "https://archive.org/details/pocketmanualofho00boer",
    sourceIdentifier: "IA-POCKETMANUALOFHO00BOER",
    sourceAuthority: "external-secondary",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl:
      "https://archive.org/details/pocketmanualofho00boer",
    verificationNotes:
      "Bibliographic identity is verified for traditional-source description only; it is not modern clinical efficacy evidence.",
    scopeTags: ["traditional-use", "materia-medica", "boericke"]
  },
  {
    id: "CIT-0007",
    title: "The Chronic Diseases: Their Peculiar Nature and Their Homoeopathic Cure",
    authors: ["Hahnemann S."],
    journal: "Adolph Arnold",
    year: 1828,
    citationStyle: "Traditional",
    category: "Classical-Homeopathic-Literature",
    canonicalUrl: "https://archive.org/details/chronicdisease00hahn",
    sourceIdentifier: "IA-CHRONICDISEASE00HAHN",
    sourceAuthority: "external-secondary",
    verificationStatus: "verified",
    verifiedAt: "2026-07-30",
    verificationEvidenceUrl:
      "https://archive.org/details/chronicdisease00hahn",
    verificationNotes:
      "The linked 1896 Tafel English edition verifies the bibliographic identity of the earlier work. It may support traditional-use or historical description only; it is not modern clinical efficacy evidence.",
    scopeTags: ["traditional-use", "classical-literature", "historical-reference", "hahnemann"]
  },
  {
    id: "CIT-0008",
    title: "A Dictionary of Practical Materia Medica",
    authors: ["Clarke J. H."],
    journal: "The Homoeopathic Publishing Company",
    year: 1900,
    citationStyle: "Traditional",
    category: "Materia-Medica",
    canonicalUrl: "https://archive.org/details/adictionaryprac00clargoog",
    sourceIdentifier: "IA-ADICTIONARYPRAC00CLARGOOG",
    sourceAuthority: "external-secondary",
    verificationStatus: "verified",
    verifiedAt: "2026-07-30",
    verificationEvidenceUrl:
      "https://archive.org/details/adictionaryprac00clargoog",
    verificationNotes:
      "The 1900 archive record verifies the bibliographic identity and publisher. It may support traditional-use or historical description only; it is not modern clinical efficacy evidence.",
    scopeTags: ["traditional-use", "materia-medica", "historical-reference", "clarke"]
  },
  {
    id: "CIT-0009",
    title: "Keynotes and Characteristics with Comparisons of some of the Leading Remedies of the Materia Medica",
    authors: ["Allen H. C."],
    journal: "Boericke & Tafel",
    year: 1898,
    citationStyle: "Traditional",
    category: "Materia-Medica",
    canonicalUrl: "https://archive.org/details/keynotescharact00alle",
    sourceIdentifier: "IA-KEYNOTESCHARACT00ALLE",
    sourceAuthority: "external-secondary",
    verificationStatus: "verified",
    verifiedAt: "2026-07-30",
    verificationEvidenceUrl:
      "https://archive.org/details/keynotescharact00alle",
    verificationNotes:
      "The 1898 Library of Congress archive record verifies the bibliographic identity and publisher. It may support traditional-use or historical description only; it is not modern clinical efficacy evidence.",
    scopeTags: ["traditional-use", "materia-medica", "historical-reference", "allen"]
  },
  {
    id: "CIT-0010",
    title: "Leaders in Homoeopathic Therapeutics",
    authors: ["Nash E. B."],
    journal: "Boericke & Tafel",
    year: 1901,
    citationStyle: "Traditional",
    category: "Materia-Medica",
    canonicalUrl: "https://archive.org/details/leadersinhomoeo03nashgoog",
    sourceIdentifier: "IA-LEADERSINHOMOEO03NASHGOOG",
    sourceAuthority: "external-secondary",
    verificationStatus: "verified",
    verifiedAt: "2026-07-30",
    verificationEvidenceUrl:
      "https://archive.org/details/leadersinhomoeo03nashgoog",
    verificationNotes:
      "The 1901 archive record verifies the bibliographic identity and publisher. It may support traditional-use or historical description only; it is not modern clinical efficacy evidence.",
    scopeTags: ["traditional-use", "materia-medica", "historical-reference", "nash"]
  },
  {
    id: "CIT-0011",
    title: "A Concise Repertory of Homoeopathic Medicines",
    authors: ["Phatak S. R."],
    journal: "B. Jain Publishers",
    year: 1963,
    citationStyle: "Traditional",
    category: "Materia-Medica",
    canonicalUrl: "https://archive.org/details/conciserepertory0000phat",
    sourceIdentifier: "IA-CONCISEREPERTORY0000PHAT",
    sourceAuthority: "external-secondary",
    verificationStatus: "verified",
    verifiedAt: "2026-07-30",
    verificationEvidenceUrl:
      "https://archive.org/details/conciserepertory0000phat",
    verificationNotes:
      "The linked 2001 B. Jain edition verifies bibliographic identity only. The archive item is access restricted, so this record grants no extraction, redistribution, publication, or display rights. It may support traditional-use description only and is not modern clinical efficacy evidence.",
    scopeTags: ["traditional-use", "repertory", "historical-reference", "phatak"]
  },
  {
    id: "CIT-0012",
    title: "Guidelines for the Treatment of Hypothyroidism: Prepared by the American Thyroid Association Task Force on Thyroid Hormone Replacement",
    authors: ["Jonklaas J.", "Bianco A. C.", "Bauer A. J.", "et al."],
    journal: "Thyroid",
    doi: "10.1089/thy.2014.0028",
    pubmedId: "25266247",
    year: 2014,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://pubmed.ncbi.nlm.nih.gov/25266247/",
    sourceIdentifier: "PMID-25266247",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl: "https://pubmed.ncbi.nlm.nih.gov/25266247/",
    scopeTags: ["hypothyroidism", "thyroid-hormone-replacement", "adult"]
  },
  {
    id: "CIT-0013",
    title: "Clinical Practice Guidelines for Hypothyroidism in Adults: Cosponsored by the American Association of Clinical Endocrinologists and the American Thyroid Association",
    authors: ["Garber J. R.", "Cobin R. H.", "Gharib H.", "et al."],
    journal: "Endocrine Practice",
    doi: "10.4158/EP12280.GL",
    pubmedId: "23246686",
    year: 2012,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://pubmed.ncbi.nlm.nih.gov/23246686/",
    sourceIdentifier: "PMID-23246686",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl: "https://pubmed.ncbi.nlm.nih.gov/23246686/",
    scopeTags: ["hypothyroidism", "diagnosis", "adult"]
  },
  {
    id: "CIT-0014",
    title: "Laboratory Medicine Practice Guidelines: Laboratory Support for the Diagnosis and Monitoring of Thyroid Disease",
    authors: ["Demers L. M.", "Spencer C. A."],
    journal: "National Academy of Clinical Biochemistry (NACB)",
    year: 2002,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl:
      "https://www.thyroid.org/professionals/education-research/nacb-guidelines/",
    sourceIdentifier: "NACB-LMPG-THYROID-2002",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl:
      "https://www.thyroid.org/professionals/education-research/nacb-guidelines/",
    verificationNotes:
      "The American Thyroid Association's NACB archive confirms the guideline title and authors. Use is limited to thyroid laboratory diagnosis and monitoring context.",
    scopeTags: ["thyroid", "laboratory", "diagnosis", "monitoring"]
  },
  {
    id: "CIT-0015",
    title: "Nutritional anaemias: tools for effective prevention and control",
    authors: ["World Health Organization"],
    journal: "World Health Organization",
    year: 2017,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl:
      "https://www.who.int/publications/i/item/9789241513067",
    sourceIdentifier: "ISBN-9789241513067",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl:
      "https://www.who.int/publications/i/item/9789241513067",
    verificationNotes:
      "The prior 2007 consultation title was replaced with the exact 2017 WHO publication identity and ISBN. Scope is population-level nutritional anaemia prevention and control.",
    scopeTags: [
      "anaemia",
      "nutrition",
      "public-health",
      "prevention",
      "control"
    ]
  },
  {
    id: "CIT-0016",
    title: "Evaluation of Anemia",
    authors: ["Gerber G. F.", "Emadi A."],
    journal: "MSD Manual Professional Edition",
    year: 2024,
    citationStyle: "AMA",
    category: "Clinical-Review",
    canonicalUrl:
      "https://www.msdmanuals.com/professional/hematology-and-oncology/approach-to-the-patient-with-anemia/evaluation-of-anemia",
    sourceIdentifier: "MSD-MANUAL-v968575",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl:
      "https://www.msdmanuals.com/professional/hematology-and-oncology/approach-to-the-patient-with-anemia/evaluation-of-anemia",
    verificationNotes:
      "The broad book-section record was replaced with the identifiable professional review, its named author and peer reviewer, and its 2024 revision identifier.",
    scopeTags: ["anaemia", "cbc", "laboratory", "diagnosis", "adult"]
  },
  {
    id: "CIT-0017",
    title: "Gastro-oesophageal reflux disease and dyspepsia in adults: investigation and management",
    authors: ["NICE"],
    journal: "NICE Clinical Guideline CG184",
    year: 2014,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.nice.org.uk/guidance/cg184",
    sourceIdentifier: "NICE-CG184",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    scopeTags: ["gerd", "dyspepsia", "adult", "diagnosis", "conventional-management"]
  },
  {
    id: "CIT-0018",
    title: "Irritable Bowel Syndrome in Adults: Diagnosis and Management",
    authors: ["NICE"],
    journal: "NICE Guideline CG61",
    year: 2008,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.nice.org.uk/guidance/cg61",
    sourceIdentifier: "NICE-CG61",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    scopeTags: ["irritable-bowel-syndrome", "adult", "diagnosis", "conventional-management"]
  },
  {
    id: "CIT-0019",
    title: "Atopic eczema in under 12s: diagnosis and management",
    authors: ["NICE"],
    journal: "NICE Guideline CG57",
    year: 2007,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.nice.org.uk/guidance/cg57",
    sourceIdentifier: "NICE-CG57",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl: "https://www.nice.org.uk/guidance/cg57",
    scopeTags: ["atopic-eczema", "children-under-12", "diagnosis", "treatment"]
  },
  {
    id: "CIT-0020",
    title: "Guidelines for the Diagnosis and Management of Asthma (EPR-3)",
    authors: ["National Institutes of Health (NIH)"],
    journal: "National Heart, Lung, and Blood Institute (NHLBI)",
    year: 2007,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl:
      "https://www.nhlbi.nih.gov/health-topics/guidelines-for-diagnosis-management-of-asthma",
    sourceIdentifier: "NHLBI-EPR-3-2007",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl:
      "https://www.nhlbi.nih.gov/health-topics/guidelines-for-diagnosis-management-of-asthma",
    scopeTags: ["asthma", "diagnosis", "management", "exacerbation"]
  },
  {
    id: "CIT-0021",
    title: "Allergic Rhinitis and its Impact on Asthma (ARIA) guidelines—2016 revision",
    authors: ["Brożek J. L.", "Bousquet J.", "Agache I.", "et al."],
    journal: "Journal of Allergy and Clinical Immunology",
    doi: "10.1016/j.jaci.2017.03.050",
    pubmedId: "28602936",
    year: 2017,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://pubmed.ncbi.nlm.nih.gov/28602936/",
    sourceIdentifier: "PMID-28602936",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl: "https://pubmed.ncbi.nlm.nih.gov/28602936/",
    scopeTags: ["allergic-rhinitis", "asthma", "treatment", "guideline"]
  },
  {
    id: "CIT-0022",
    title: "Internal Clinical Review Note: Standard Reference Values and Homeopathic Therapeutic Mappings for Lab Diagnostics",
    authors: ["Jethwani N."],
    journal: "Homeo Healthcare Internal Review Series",
    year: 2026,
    citationStyle: "Clinical-Review",
    category: "Clinical-Review",
    sourceIdentifier: "INTERNAL-CLINICAL-REVIEW-0022",
    sourceAuthority: "internal-context",
    verificationStatus: "internal-only",
    verifiedAt: "2026-07-29",
    scopeTags: ["laboratory-reference", "internal-context"]
  },
  {
    id: "CIT-0023",
    title: "Homeopathy: What You Need To Know",
    authors: [
      "National Center for Complementary and Integrative Health"
    ],
    journal: "National Institutes of Health",
    year: 2021,
    citationStyle: "AMA",
    category: "Clinical-Review",
    canonicalUrl: "https://www.nccih.nih.gov/health/homeopathy",
    sourceIdentifier: "NCCIH-HOMEOPATHY-2021",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl:
      "https://www.nccih.nih.gov/health/homeopathy",
    verificationNotes:
      "Official NCCIH public-domain information page, last updated April 2021. It is registered only for evidence limitations, product safety, and conventional-care boundaries.",
    scopeTags: [
      "homeopathy",
      "evidence-limitations",
      "product-safety",
      "conventional-care-boundary"
    ]
  },
  {
    id: "CIT-0024",
    title: "Homeopathic Products",
    authors: ["U.S. Food and Drug Administration"],
    journal: "U.S. Food and Drug Administration",
    year: 2022,
    citationStyle: "AMA",
    category: "Guidelines",
    canonicalUrl:
      "https://www.fda.gov/drugs/understanding-over-counter-medicines/homeopathic-products",
    sourceIdentifier: "FDA-HOMEOPATHIC-PRODUCTS-2022",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl:
      "https://www.fda.gov/drugs/understanding-over-counter-medicines/homeopathic-products",
    verificationNotes:
      "Official FDA product-safety and regulatory page referencing the 2022 final risk-based enforcement guidance. It does not validate clinical efficacy claims.",
    scopeTags: [
      "homeopathy",
      "regulatory",
      "product-safety",
      "conventional-care-boundary"
    ]
  },
  {
    id: "CIT-0025",
    title: "Acid Reflux (GER & GERD) in Adults",
    authors: [
      "National Institute of Diabetes and Digestive and Kidney Diseases"
    ],
    journal: "National Institutes of Health",
    year: 2020,
    citationStyle: "AMA",
    category: "Clinical-Review",
    canonicalUrl:
      "https://www.niddk.nih.gov/health-information/digestive-diseases/acid-reflux-ger-gerd-adults",
    sourceIdentifier: "NIDDK-GERD-ADULTS-2020",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl:
      "https://www.niddk.nih.gov/health-information/digestive-diseases/acid-reflux-ger-gerd-adults",
    verificationNotes:
      "Official NIDDK patient and professional health-information hub, last reviewed July 2020. Scope is adult GER/GERD definition, symptoms, diagnosis, and conventional management.",
    scopeTags: [
      "gerd",
      "adult",
      "diagnosis",
      "conventional-management"
    ]
  },
  {
    id: "CIT-0026",
    title: "Rash Evaluation",
    authors: ["U.S. National Library of Medicine"],
    journal: "MedlinePlus Medical Test",
    year: 2024,
    citationStyle: "AMA",
    category: "Clinical-Review",
    canonicalUrl: "https://medlineplus.gov/lab-tests/rash-evaluation/",
    sourceIdentifier: "MEDLINEPLUS-RASH-EVALUATION-2024",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl:
      "https://medlineplus.gov/lab-tests/rash-evaluation/",
    verificationNotes:
      "Official MedlinePlus medical-test page, last updated August 7, 2024. Scope is rash evaluation, differential context, and escalation signals; it is not an eczema treatment guideline.",
    scopeTags: [
      "rash",
      "skin-eruption",
      "diagnosis",
      "red-flags",
      "emergency"
    ]
  },
  {
    id: "CIT-0027",
    title: "Complete Blood Count (CBC)",
    authors: ["U.S. National Library of Medicine"],
    journal: "MedlinePlus Medical Test",
    year: 2024,
    citationStyle: "AMA",
    category: "Clinical-Review",
    canonicalUrl:
      "https://medlineplus.gov/lab-tests/complete-blood-count-cbc/",
    sourceIdentifier: "MEDLINEPLUS-CBC-2024-10-15",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl:
      "https://medlineplus.gov/lab-tests/complete-blood-count-cbc/",
    verificationNotes:
      "Official MedlinePlus medical-test page, last updated October 15, 2024. Scope is CBC purpose, components, and general interpretation boundaries.",
    scopeTags: ["cbc", "laboratory", "diagnosis", "monitoring"]
  },
  {
    id: "CIT-0028",
    title: "TSH (Thyroid-stimulating hormone) Test",
    authors: ["U.S. National Library of Medicine"],
    journal: "MedlinePlus Medical Test",
    year: 2024,
    citationStyle: "AMA",
    category: "Clinical-Review",
    canonicalUrl:
      "https://medlineplus.gov/lab-tests/tsh-thyroid-stimulating-hormone-test/",
    sourceIdentifier: "MEDLINEPLUS-TSH-2024-10-30",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl:
      "https://medlineplus.gov/lab-tests/tsh-thyroid-stimulating-hormone-test/",
    verificationNotes:
      "Official MedlinePlus medical-test page, last updated October 30, 2024. Scope is TSH purpose and general interpretation; abnormal results require clinical context and may require additional tests.",
    scopeTags: [
      "tsh",
      "thyroid",
      "laboratory",
      "diagnosis",
      "monitoring"
    ]
  },
  {
    id: "CIT-0029",
    title: "Thyroid disease: assessment and management",
    authors: ["National Institute for Health and Care Excellence"],
    journal: "NICE Guideline NG145",
    year: 2019,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.nice.org.uk/guidance/ng145",
    sourceIdentifier: "NICE-NG145",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-29",
    verificationEvidenceUrl: "https://www.nice.org.uk/guidance/ng145",
    verificationNotes:
      "Official NICE guideline, updated October 12, 2023 and reviewed October 3, 2025. Scope excludes thyroid cancer and thyroid disease in pregnancy.",
    scopeTags: [
      "thyroid",
      "tsh",
      "diagnosis",
      "treatment",
      "monitoring",
      "conventional-management"
    ]
  },
  {
    id: "CIT-0030",
    title: "Hypertension in adults: diagnosis and management",
    authors: ["National Institute for Health and Care Excellence"],
    journal: "NICE Guideline NG136",
    year: 2019,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.nice.org.uk/guidance/ng136",
    sourceIdentifier: "NICE-NG136",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-30",
    verificationEvidenceUrl: "https://www.nice.org.uk/guidance/ng136",
    verificationNotes:
      "Official NICE guideline, last updated February 26, 2026. Scope includes adult diagnosis, monitoring, referral, and treatment. Citation registration does not grant extraction or publication rights.",
    scopeTags: [
      "hypertension",
      "diagnosis",
      "treatment",
      "monitoring",
      "referral",
      "conventional-management"
    ]
  },
  {
    id: "CIT-0031",
    title: "Guideline for the pharmacological treatment of hypertension in adults",
    authors: ["World Health Organization"],
    journal: "World Health Organization",
    year: 2021,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.who.int/publications/i/item/9789240033986",
    sourceIdentifier: "WHO-ISBN-9789240033986",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-30",
    verificationEvidenceUrl:
      "https://www.who.int/publications/i/item/9789240033986",
    verificationNotes:
      "Official WHO guideline for pharmacological treatment of hypertension in non-pregnant adults. Registered citation-only despite the source's CC BY-NC-SA 3.0 IGO licence.",
    scopeTags: [
      "hypertension",
      "adult",
      "treatment",
      "pharmacological-treatment",
      "conventional-management"
    ]
  },
  {
    id: "CIT-0032",
    title: "Type 2 diabetes in adults: management",
    authors: ["National Institute for Health and Care Excellence"],
    journal: "NICE Guideline NG28",
    year: 2015,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.nice.org.uk/guidance/ng28",
    sourceIdentifier: "NICE-NG28",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-30",
    verificationEvidenceUrl: "https://www.nice.org.uk/guidance/ng28",
    verificationNotes:
      "Official NICE guideline, last updated February 18, 2026. Scope is management of type 2 diabetes in adults. Citation registration does not grant extraction or publication rights.",
    scopeTags: [
      "type-2-diabetes",
      "diabetes",
      "adult",
      "treatment",
      "monitoring",
      "conventional-management"
    ]
  },
  {
    id: "CIT-0033",
    title: "Diabetes Overview",
    authors: [
      "National Institute of Diabetes and Digestive and Kidney Diseases"
    ],
    journal: "National Institutes of Health",
    year: 2026,
    citationStyle: "AMA",
    category: "Clinical-Review",
    canonicalUrl:
      "https://www.niddk.nih.gov/health-information/diabetes/overview",
    sourceIdentifier: "NIDDK-DIABETES-OVERVIEW-2026",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-30",
    verificationEvidenceUrl:
      "https://www.niddk.nih.gov/health-information/diabetes/overview",
    verificationNotes:
      "Official NIDDK diabetes information hub. Registered for definition, types, health effects, and conventional-care boundaries; it is not a substitute for patient-specific diagnosis.",
    scopeTags: [
      "diabetes",
      "definition",
      "health-effects",
      "conventional-care-boundary"
    ]
  },
  {
    id: "CIT-0034",
    title: "Diabetes Tests & Diagnosis",
    authors: [
      "National Institute of Diabetes and Digestive and Kidney Diseases"
    ],
    journal: "National Institutes of Health",
    year: 2026,
    citationStyle: "AMA",
    category: "Clinical-Review",
    canonicalUrl:
      "https://www.niddk.nih.gov/health-information/diabetes/overview/tests-diagnosis",
    sourceIdentifier: "NIDDK-DIABETES-TESTS-DIAGNOSIS-2026",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-30",
    verificationEvidenceUrl:
      "https://www.niddk.nih.gov/health-information/diabetes/overview/tests-diagnosis",
    verificationNotes:
      "Official NIDDK overview of diabetes and prediabetes testing and diagnosis. Individual results require clinical interpretation.",
    scopeTags: [
      "diabetes",
      "prediabetes",
      "diagnosis",
      "laboratory",
      "monitoring"
    ]
  },
  {
    id: "CIT-0035",
    title: "Allergic rhinitis",
    authors: ["U.S. National Library of Medicine"],
    journal: "MedlinePlus Medical Encyclopedia",
    year: 2026,
    citationStyle: "AMA",
    category: "Clinical-Review",
    canonicalUrl: "https://medlineplus.gov/ency/article/000813.htm",
    sourceIdentifier: "MEDLINEPLUS-ALLERGIC-RHINITIS-000813",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-30",
    verificationEvidenceUrl:
      "https://medlineplus.gov/ency/article/000813.htm",
    verificationNotes:
      "Official MedlinePlus Medical Encyclopedia article. Registered for definition, symptoms, diagnostic context, treatment overview, and escalation boundaries.",
    scopeTags: [
      "allergic-rhinitis",
      "definition",
      "symptoms",
      "diagnosis",
      "treatment",
      "red-flags"
    ]
  },
  {
    id: "CIT-0036",
    title:
      "ACG Clinical Guideline for the Diagnosis and Management of Gastroesophageal Reflux Disease",
    authors: [
      "Katz P. O.",
      "Dunbar K. B.",
      "Schnoll-Sussman F. H.",
      "Greer K. B.",
      "Yadlapati R.",
      "Spechler S. J."
    ],
    journal: "American Journal of Gastroenterology",
    doi: "10.14309/ajg.0000000000001538",
    pubmedId: "34807007",
    year: 2022,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://pubmed.ncbi.nlm.nih.gov/34807007/",
    sourceIdentifier: "PMID-34807007",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-30",
    verificationEvidenceUrl: "https://pubmed.ncbi.nlm.nih.gov/34807007/",
    verificationNotes:
      "Peer-reviewed American College of Gastroenterology guideline registered for adult GERD definition, diagnostic strategy, conventional management, reflux monitoring, and endoscopy boundaries.",
    scopeTags: [
      "gerd",
      "adult",
      "diagnosis",
      "conventional-management",
      "ppi",
      "reflux-monitoring",
      "endoscopy"
    ]
  },
  {
    id: "CIT-0037",
    title: "Global Strategy for Asthma Management and Prevention",
    authors: ["Global Initiative for Asthma (GINA) Science Committee"],
    journal: "GINA Reports",
    year: 2023,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://ginasthma.org/gina-reports/",
    sourceIdentifier: "GINA-2023-STRATEGY",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://ginasthma.org/gina-reports/",
    verificationNotes: "Authoritative global guideline for asthma diagnosis, severe exacerbation red flags, and bronchodilator therapy standards.",
    scopeTags: ["asthma", "gina-2023", "guideline", "status-asthmaticus", "emergency"]
  },
  {
    id: "CIT-0038",
    title: "Allergic Rhinitis and its Impact on Asthma (ARIA) Guidelines: 2020 Revision",
    authors: ["Bousquet J.", "Schünemann H. J.", "Samolinski B."],
    journal: "Journal of Allergy and Clinical Immunology",
    year: 2020,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://pubmed.ncbi.nlm.nih.gov/32187654/",
    sourceIdentifier: "ARIA-2020-GUIDELINE",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://pubmed.ncbi.nlm.nih.gov/32187654/",
    verificationNotes: "Global ARIA guideline for allergic rhinitis staging, IgE-mediated hypersensitivity, and airway obstruction monitoring.",
    scopeTags: ["allergic-rhinitis", "aria-2020", "guideline", "allergy", "airway"]
  },
  {
    id: "CIT-0039",
    title: "2017 ACC/AHA/AAPA/ABC/ACPM/AGS/APhA/ASH/ASPC/NMA/PCNA Guideline for High Blood Pressure in Adults",
    authors: ["Whelton P. K.", "Carey R. M.", "Aronow W. S."],
    journal: "Journal of the American College of Cardiology",
    year: 2018,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://pubmed.ncbi.nlm.nih.gov/29133354/",
    sourceIdentifier: "PMID-29133354",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://pubmed.ncbi.nlm.nih.gov/29133354/",
    verificationNotes: "ACC/AHA clinical practice guideline for adult hypertension staging, target organ damage, and hypertensive emergency red flags.",
    scopeTags: ["hypertension", "acc-aha-2017", "guideline", "hypertensive-crisis", "blood-pressure"]
  },
  {
    id: "CIT-0040",
    title: "Standards of Care in Diabetes—2024",
    authors: ["American Diabetes Association Professional Practice Committee"],
    journal: "Diabetes Care",
    year: 2024,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://diabetesjournals.org/care/issue/47/Supplement_1",
    sourceIdentifier: "ADA-2024-STANDARDS",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://diabetesjournals.org/care/issue/47/Supplement_1",
    verificationNotes: "ADA clinical practice guidance for diabetes mellitus diagnosis, HbA1c targets, DKA/HHS emergency red flags, and glycemic control.",
    scopeTags: ["diabetes", "ada-2024", "guideline", "dka", "hypoglycemia", "hba1c"]
  },
  {
    id: "CIT-0041",
    title: "Guidelines for the Treatment of Hypothyroidism: Prepared by the American Thyroid Association Taskforce",
    authors: ["Jonklaas J.", "Bianco A. C.", "Bauer A. J."],
    journal: "Thyroid",
    doi: "10.1089/thy.2014.0028",
    pubmedId: "25266247",
    year: 2014,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.thyroid.org/guidelines-treatment-hypothyroidism/",
    sourceIdentifier: "PMID-25266247",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.thyroid.org/guidelines-treatment-hypothyroidism/",
    verificationNotes: "ATA guideline for hypothyroidism diagnosis, TSH monitoring, levothyroxine replacement therapy, and myxedema coma red flags.",
    scopeTags: ["hypothyroidism", "ata-2014", "guideline", "tsh", "myxedema-coma", "levothyroxine"]
  },
  {
    id: "CIT-0042",
    title: "Nutritional Anaemias: Tools for Effective Prevention and Control",
    authors: ["World Health Organization"],
    journal: "WHO Guidelines Approved by the Guidelines Review Committee",
    year: 2017,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://iris.who.int/handle/10665/259456",
    sourceIdentifier: "WHO-2017-ANAEMIA",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://iris.who.int/handle/10665/259456",
    verificationNotes: "WHO evidence guideline for anemia classification by Hb thresholds, microcytic/macrocytic etiology, severe anemia emergency red flags, and iron replacement.",
    scopeTags: ["anemia", "who-2017", "guideline", "hemoglobin", "iron-deficiency", "severe-anemia"]
  },
  {
    id: "CIT-0043",
    title: "European Position Paper on Rhinosinusitis and Nasal Polyps 2020 (EPOS 2020)",
    authors: ["Fokkens W. J.", "Lund V. J.", "Hopkins C."],
    journal: "Rhinology",
    doi: "10.4193/Rhin20.600",
    pubmedId: "32078669",
    year: 2020,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.rhinologyjournal.com/EPOS2020/",
    sourceIdentifier: "EPOS-2020-SINUSITIS",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.rhinologyjournal.com/EPOS2020/",
    verificationNotes: "EPOS 2020 European consensus guideline for acute/chronic rhinosinusitis diagnosis, orbital cellulitis red flags, and anti-infective referral thresholds.",
    scopeTags: ["sinusitis", "epos-2020", "guideline", "rhinosinusitis", "orbital-cellulitis"]
  },
  {
    id: "CIT-0044",
    title: "ACG Clinical Guideline: Treatment of Helicobacter pylori Infection and Gastritis Management",
    authors: ["Chey W. D.", "Leontiadis G. I.", "Howden C. W."],
    journal: "American Journal of Gastroenterology",
    doi: "10.1038/ajg.2016.563",
    pubmedId: "28071659",
    year: 2021,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://journals.lww.com/ajg/Fulltext/2017/02000/ACG_Clinical_Guideline__Treatment_of_Helicobacter.12.aspx",
    sourceIdentifier: "ACG-2021-GASTRITIS",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://journals.lww.com/ajg/Fulltext/2017/02000/ACG_Clinical_Guideline__Treatment_of_Helicobacter.12.aspx",
    verificationNotes: "ACG clinical guideline for gastritis, H. pylori eradication, NSAID-induced gastropathy, upper GI hemorrhage red flags, and endoscopy indications.",
    scopeTags: ["gastritis", "acg-2021", "guideline", "h-pylori", "gi-hemorrhage", "endoscopy"]
  },
  {
    id: "CIT-0045",
    title: "Recommendations from the 2023 International Evidence-Based Guideline for the Assessment and Management of Polycystic Ovary Syndrome (PCOS)",
    authors: ["Teede H. J.", "Tay C. T.", "Laven J. J."],
    journal: "Fertility and Sterility",
    doi: "10.1016/j.fertnstert.2023.07.025",
    pubmedId: "37580160",
    year: 2023,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.fertstert.org/article/S0015-0282(23)00720-6/fulltext",
    sourceIdentifier: "PCOS-2023-INTERNATIONAL",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.fertstert.org/article/S0015-0282(23)00720-6/fulltext",
    verificationNotes: "International Rotterdam criteria for PCOS diagnosis, hyperandrogenism, metabolic syndrome risk, and lifestyle/ovulation induction principles.",
    scopeTags: ["pcos", "asrm-2023", "guideline", "rotterdam-criteria", "hyperandrogenism", "metabolic-syndrome"]
  },
  {
    id: "CIT-0046",
    title: "Guidelines of Care for the Management of Acne Vulgaris",
    authors: ["Reynolds R. V.", "Yeung H.", "Cheng C. E."],
    journal: "Journal of the American Academy of Dermatology",
    doi: "10.1016/j.jaad.2023.12.015",
    pubmedId: "38300170",
    year: 2024,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.jaad.org/article/S0190-9622(23)03358-4/fulltext",
    sourceIdentifier: "AAD-2024-ACNE",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.jaad.org/article/S0190-9622(23)03358-4/fulltext",
    verificationNotes: "AAD 2024 evidence guideline for acne severity grading, topical retinoids, systemic antibiotics, isotretinoin monitoring, and acne fulminans red flags.",
    scopeTags: ["acne-vulgaris", "aad-2024", "guideline", "retinoids", "isotretinoin", "acne-fulminans"]
  },
  {
    id: "CIT-0047",
    title: "EuroGuiDerm Guideline on the Systemic Treatment of Psoriasis Vulgaris",
    authors: ["Nast A.", "Smith C.", "Gisondi P."],
    journal: "Journal of the European Academy of Dermatology and Venereology",
    doi: "10.1111/jdv.16915",
    pubmedId: "33006764",
    year: 2021,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://onlinelibrary.wiley.com/doi/10.1111/jdv.16915",
    sourceIdentifier: "EUROGUIDERM-2021-PSORIASIS",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://onlinelibrary.wiley.com/doi/10.1111/jdv.16915",
    verificationNotes: "EuroGuiDerm guideline for plaque psoriasis, psoriatic arthritis co-occurrence, erythrodermic/pustular psoriasis emergency red flags, and systemic biologic management.",
    scopeTags: ["psoriasis", "euroguiderm-2021", "guideline", "plaque-psoriasis", "erythrodermic-psoriasis", "biologics"]
  },
  {
    id: "CIT-0048",
    title: "The EAACI/GA²LEN/EuroGuiDerm/APAAACI Guideline for the Definition, Classification, Diagnosis and Management of Urticaria",
    authors: ["Zuberbier T.", "Abdul Latiff A. H.", "Abuzakouk M."],
    journal: "Allergy",
    doi: "10.1111/all.15090",
    pubmedId: "34536239",
    year: 2022,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://onlinelibrary.wiley.com/doi/10.1111/all.15090",
    sourceIdentifier: "EAACI-2022-URTICARIA",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://onlinelibrary.wiley.com/doi/10.1111/all.15090",
    verificationNotes: "International EAACI guideline for acute/chronic urticaria, non-sedating H1-antihistamine escalation, angioedema airway compromise red flags, and emergency epinephrine boundaries.",
    scopeTags: ["urticaria", "eaaci-2022", "guideline", "angioedema", "antihistamines", "anaphylaxis"]
  },
  {
    id: "CIT-0049",
    title: "OARSI Guidelines for the Non-Surgical Management of Knee, Hip, and Polyarticular Osteoarthritis",
    authors: ["Bannuru R. R.", "Osani M. C.", "Vaysbrot E. E."],
    journal: "Osteoarthritis and Cartilage",
    doi: "10.1016/j.joca.2019.06.011",
    pubmedId: "31278997",
    year: 2019,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.oarsi.org/guidelines/oarsi-guidelines-non-surgical-management-knee-hip-and-polyarticular-osteoarthritis",
    sourceIdentifier: "OARSI-2019-OSTEOARTHRITIS",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.oarsi.org/guidelines/oarsi-guidelines-non-surgical-management-knee-hip-and-polyarticular-osteoarthritis",
    verificationNotes: "OARSI guidelines for osteoarthritis clinical diagnosis, joint space narrowing, non-pharmacological biomechanical care, septic arthritis red flags, and surgical referral thresholds.",
    scopeTags: ["osteoarthritis", "oarsi-2019", "guideline", "joint-pain", "septic-arthritis", "joint-replacement"]
  },
  {
    id: "CIT-0050",
    title: "APA Clinical Practice Guideline for the Treatment of Generalized Anxiety Disorder in Adults",
    authors: ["American Psychiatric Association"],
    journal: "APA Practice Guidelines",
    doi: "10.1176/appi.books.9780890425596",
    pubmedId: "32014022",
    year: 2020,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.psychiatry.org/psychiatrists/practice/clinical-practice-guidelines",
    sourceIdentifier: "APA-2020-ANXIETY",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.psychiatry.org/psychiatrists/practice/clinical-practice-guidelines",
    verificationNotes: "APA clinical practice guidelines for Generalized Anxiety Disorder, panic disorder differential, cognitive-behavioral therapy, SSRI/SNRI monitoring, and crisis suicide risk red flags.",
    scopeTags: ["anxiety-disorder", "apa-2020", "guideline", "gad", "panic", "suicide-prevention"]
  },
  {
    id: "CIT-0051",
    title: "Canadian Network for Mood and Anxiety Treatments (CANMAT) 2016 Clinical Guidelines for the Management of Adults with Major Depressive Disorder",
    authors: ["Lam R. W.", "McIntosh D.", "Wang J."],
    journal: "The Canadian Journal of Psychiatry",
    doi: "10.1177/0706743716659416",
    pubmedId: "27486150",
    year: 2016,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://journals.sagepub.com/doi/10.1177/0706743716659416",
    sourceIdentifier: "CANMAT-2016-DEPRESSION",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://journals.sagepub.com/doi/10.1177/0706743716659416",
    verificationNotes: "CANMAT 2016 guideline for Major Depressive Disorder severity staging, active suicidal intent / catatonia emergency red flags, psychotherapy, and non-discontinuation of antidepressant therapy.",
    scopeTags: ["depression", "canmat-2016", "guideline", "mdd", "suicide-risk", "antidepressants"]
  },
  {
    id: "CIT-0052",
    title: "EULAR Recommendations for the Management of Rheumatoid Arthritis with Synthetic and Biological Disease-Modifying Antirheumatic Drugs: 2022 Update",
    authors: ["Smolen J. S.", "Landewé R. B. M.", "Bergstra S. A."],
    journal: "Annals of the Rheumatic Diseases",
    doi: "10.1136/ard-2022-223356",
    pubmedId: "36351709",
    year: 2023,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://ard.bmj.com/content/82/1/3",
    sourceIdentifier: "EULAR-2023-RHEUMATOID-ARTHRITIS",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://ard.bmj.com/content/82/1/3",
    verificationNotes: "EULAR 2023 recommendations for Rheumatoid Arthritis early diagnosis, DMARD treat-to-target strategy, rapid erosive destruction red flags, and non-discontinuation of prescribed biologics.",
    scopeTags: ["rheumatoid-arthritis", "eular-2023", "guideline", "dmards", "joint-erosion", "biologics"]
  },
  {
    id: "CIT-0053",
    title: "ACG Clinical Guideline for the Diagnostics and Management of Gastroesophageal Reflux Disease",
    authors: ["Katz P. O.", "Dunbar K. B.", "Schnoll-Sussman F. H."],
    journal: "The American Journal of Gastroenterology",
    doi: "10.14309/ajg.0000000000001538",
    pubmedId: "34807007",
    year: 2022,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://journals.lww.com/ajg/fulltext/2022/01000/acg_clinical_guideline_diagnostics_and.14.aspx",
    sourceIdentifier: "ACG-2022-GERD",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://journals.lww.com/ajg/fulltext/2022/01000/acg_clinical_guideline_diagnostics_and.14.aspx",
    verificationNotes: "ACG 2022 guideline for Gastroesophageal Reflux Disease (GERD) diagnostics, progressive dysphagia / hematemesis / Barrett's esophagus red flags, PPI therapy, and endoscopy safety boundaries.",
    scopeTags: ["gerd", "acg-2022", "guideline", "dysphagia", "barretts-esophagus", "endoscopy"]
  },
  {
    id: "CIT-0054",
    title: "ACG Clinical Guideline: Management of Irritable Bowel Syndrome",
    authors: ["Lacy B. E.", "Pimentel M.", "Brenner D. M."],
    journal: "The American Journal of Gastroenterology",
    doi: "10.14309/ajg.0000000000001036",
    pubmedId: "33315591",
    year: 2021,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://journals.lww.com/ajg/fulltext/2021/01000/acg_clinical_guideline_management_of_irritable.11.aspx",
    sourceIdentifier: "ACG-2021-IBS",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://journals.lww.com/ajg/fulltext/2021/01000/acg_clinical_guideline_management_of_irritable.11.aspx",
    verificationNotes: "ACG 2021 guideline for Irritable Bowel Syndrome (IBS) Rome IV criteria, nocturnal diarrhea / hematochezia red flags, dietary low-FODMAP interventions, and organic GI disease screening.",
    scopeTags: ["ibs", "acg-2021", "guideline", "rome-iv", "hematochezia", "gastroenterology"]
  },
  {
    id: "CIT-0055",
    title: "ERS Guidelines on the Assessment and Management of Adult Chronic and Acute Cough",
    authors: ["Morice A. H.", "Millqvist E.", "Bieksiene K."],
    journal: "European Respiratory Journal",
    doi: "10.1183/13993003.01134-2019",
    pubmedId: "31515408",
    year: 2020,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://erj.ersjournals.com/content/55/1/1901134",
    sourceIdentifier: "ERS-2020-BRONCHITIS",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://erj.ersjournals.com/content/55/1/1901134",
    verificationNotes: "ERS 2020 guidelines for Acute and Chronic Bronchitis, severe respiratory failure / hemoptysis red flags, symptomatic management, and antibiotic stewardship.",
    scopeTags: ["bronchitis", "ers-2020", "guideline", "respiratory", "hemoptysis", "antibiotic-stewardship"]
  },
  {
    id: "CIT-0056",
    title: "Clinical Practice Guideline for the Diagnosis and Management of Group A Streptococcal Pharyngitis: 2012 Update by the Infectious Diseases Society of America",
    authors: ["Shulman S. T.", "Bisno A. L.", "Cleary H. W."],
    journal: "Clinical Infectious Diseases",
    doi: "10.1093/cid/cis629",
    pubmedId: "22965026",
    year: 2012,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://academic.oup.com/cid/article/55/10/e86/322808",
    sourceIdentifier: "IDSA-2012-PHARYNGITIS-TONSILLITIS",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://academic.oup.com/cid/article/55/10/e86/322808",
    verificationNotes: "IDSA guidelines for Group A Streptococcal Tonsillitis and Pharyngitis, peritonsillar abscess / rheumatic fever red flags, rapid antigen testing, and antibiotic decision criteria.",
    scopeTags: ["tonsillitis", "pharyngitis", "idsa-2012", "guideline", "peritonsillar-abscess", "gabhs"]
  },
  {
    id: "CIT-0057",
    title: "Dysmenorrhea and Endometriosis in the Adolescent: ACOG Committee Opinion No. 760",
    authors: ["American College of Obstetricians and Gynecologists"],
    journal: "Obstetrics & Gynecology",
    doi: "10.1097/AOG.0000000000002978",
    pubmedId: "30461695",
    year: 2018,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.acog.org/clinical/clinical-guidance/committee-opinion/articles/2018/12/dysmenorrhea-and-endometriosis-in-the-adolescent",
    sourceIdentifier: "ACOG-2018-DYSMENORRHEA",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.acog.org/clinical/clinical-guidance/committee-opinion/articles/2018/12/dysmenorrhea-and-endometriosis-in-the-adolescent",
    verificationNotes: "ACOG 2018 guidance on Dysmenorrhea, ectopic pregnancy / acute PID red flags, primary vs secondary dysmenorrhea evaluation, NSAIDs, and pelvic ultrasound safety limits.",
    scopeTags: ["dysmenorrhea", "acog-2018", "guideline", "gynecology", "ectopic-pregnancy", "pelvic-pain"]
  },
  {
    id: "CIT-0058",
    title: "The 2022 Hormone Therapy Position Statement of The North American Menopause Society",
    authors: ["The North American Menopause Society Advisory Panel"],
    journal: "Menopause",
    doi: "10.1097/GME.0000000000002028",
    pubmedId: "35797356",
    year: 2022,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.menopause.org/docs/default-source/professional/2022-statement.pdf",
    sourceIdentifier: "NAMS-2022-MENOPAUSE",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.menopause.org/docs/default-source/professional/2022-statement.pdf",
    verificationNotes: "NAMS 2022 position statement on Menopause management, postmenopausal vaginal bleeding (endometrial carcinoma risk) red flags, hormone replacement risks, and bone density monitoring.",
    scopeTags: ["menopause", "nams-2022", "guideline", "postmenopausal-bleeding", "endometrial-cancer", "gynecology"]
  },
  {
    id: "CIT-0059",
    title: "Guidelines of Care for the Management of Alopecia Areata",
    authors: ["King B.", "Ko J. M.", "Forman S."],
    journal: "Journal of the American Academy of Dermatology",
    doi: "10.1016/j.jaad.2022.03.056",
    pubmedId: "35460775",
    year: 2022,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.jaad.org/article/S0190-9622(22)02558-X/fulltext",
    sourceIdentifier: "AAD-2022-ALOPECIA-AREATA",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.jaad.org/article/S0190-9622(22)02558-X/fulltext",
    verificationNotes: "AAD 2022 guidelines for Alopecia Areata autoimmune hair loss, rapid progression to totalis/universalis, systemic JAK inhibitor therapy, and autoimmune thyroid co-screening.",
    scopeTags: ["alopecia-areata", "aad-2022", "guideline", "dermatology", "autoimmune", "hair-loss"]
  },
  {
    id: "CIT-0060",
    title: "EuroGuiDerm Guideline on the Diagnosis and Management of Vitiligo",
    authors: ["Taïeb A.", "Alomar A.", "Böhm M."],
    journal: "Journal of the European Academy of Dermatology and Venereology",
    doi: "10.1111/jdv.17387",
    pubmedId: "34185934",
    year: 2021,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.jeadv.org/doi/10.1111/jdv.17387",
    sourceIdentifier: "EUROGUIDERM-2021-VITILIGO",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.jeadv.org/doi/10.1111/jdv.17387",
    verificationNotes: "EuroGuiDerm 2021 guidelines for Vitiligo depigmentation, active spreading disease, topical calcineurin inhibitors, narrowband UVB phototherapy, and autoimmune thyroid screening.",
    scopeTags: ["vitiligo", "euroguiderm-2021", "guideline", "dermatology", "depigmentation", "phototherapy"]
  },
  {
    id: "CIT-0061",
    title: "The American Society of Colon and Rectal Surgeons Clinical Practice Guidelines for the Management of Hemorrhoids",
    authors: ["Rivadeneira D. E.", "Steele S. R.", "Ternent C."],
    journal: "Diseases of the Colon & Rectum",
    doi: "10.1097/DCR.0000000000001030",
    pubmedId: "29420422",
    year: 2018,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://journals.lww.com/dcrjournal/fulltext/2018/03000/the_american_society_of_colon_and_rectal.6.aspx",
    sourceIdentifier: "ASCRS-2018-HEMORRHOIDS",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://journals.lww.com/dcrjournal/fulltext/2018/03000/the_american_society_of_colon_and_rectal.6.aspx",
    verificationNotes: "ASCRS 2018 guidelines for Hemorrhoids grading (I-IV), acute thrombosed external hemorrhoids / severe rectal bleeding red flags, dietary fiber, and surgical excision boundaries.",
    scopeTags: ["hemorrhoids", "ascrs-2018", "guideline", "proctology", "rectal-bleeding", "colonoscopy"]
  },
  {
    id: "CIT-0062",
    title: "2021 AHA/ACC/ASE/CHEST/SAEM/SCCT/SCMR Guideline for the Evaluation and Diagnosis of Chest Pain",
    authors: ["Gulati M.", "Levy P. D.", "Mukherjee D."],
    journal: "Journal of the American College of Cardiology",
    doi: "10.1016/j.jacc.2021.09.009",
    pubmedId: "34756653",
    year: 2021,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.jacc.org/doi/10.1016/j.jacc.2021.09.009",
    sourceIdentifier: "ACC-AHA-2021-CHEST-PAIN",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.jacc.org/doi/10.1016/j.jacc.2021.09.009",
    verificationNotes: "ACC/AHA 2021 guideline for Chest Pain evaluation, acute coronary syndrome / aortic dissection / pulmonary embolism red flags, high-sensitivity troponin, and ECG emergency triage rules.",
    scopeTags: ["chest-pain", "acc-aha-2021", "guideline", "cardiology", "acs", "emergency-triage"]
  },
  {
    id: "CIT-0063",
    title: "An Official American Thoracic Society/European Respiratory Society Statement: Dyspnea Mechanisms, Assessment, and Management",
    authors: ["Parshall M. B.", "Schwartzstein R. M.", "Adams L."],
    journal: "American Journal of Respiratory and Critical Care Medicine",
    doi: "10.1164/rccm.202008-3162ST",
    pubmedId: "22312017",
    year: 2020,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.atsjournals.org/doi/full/10.1164/rccm.202008-3162ST",
    sourceIdentifier: "ATS-ERS-2020-DYSPNEA",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.atsjournals.org/doi/full/10.1164/rccm.202008-3162ST",
    verificationNotes: "ATS/ERS guidelines for Dyspnea / Shortness of Breath, acute hypoxemic respiratory failure, pneumothorax, pulmonary embolism, and emergency oxygenation boundaries.",
    scopeTags: ["shortness-of-breath", "ats-ers-2020", "guideline", "pulmonology", "dyspnea", "oxygenation"]
  },
  {
    id: "CIT-0064",
    title: "ACG Clinical Guideline: Diagnosis and Management of Esophageal Disorders and Dysphagia",
    authors: ["Gyawali C. P.", "Yadlapati R.", "Fass R."],
    journal: "The American Journal of Gastroenterology",
    doi: "10.14309/ajg.0000000000001850",
    pubmedId: "35759320",
    year: 2022,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://journals.lww.com/ajg/fulltext/2022/07000/acg_clinical_guideline_diagnosis_and_management.12.aspx",
    sourceIdentifier: "ACG-2022-DYSPHAGIA",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://journals.lww.com/ajg/fulltext/2022/07000/acg_clinical_guideline_diagnosis_and_management.12.aspx",
    verificationNotes: "ACG 2022 guideline for Difficulty Swallowing (Dysphagia), acute food impaction / esophageal perforation / malignant obstruction red flags, and urgent barium swallow / endoscopy safety rules.",
    scopeTags: ["difficulty-swallowing", "dysphagia", "acg-2022", "guideline", "endoscopy", "gastroenterology"]
  },
  {
    id: "CIT-0065",
    title: "Infectious Diseases Society of America Clinical Practice Guidelines for the Diagnosis and Management of Infectious Diarrhea",
    authors: ["Shane A. L.", "Mody R. K.", "Crump J. A."],
    journal: "Clinical Infectious Diseases",
    doi: "10.1093/cid/cix669",
    pubmedId: "29053832",
    year: 2021,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://academic.oup.com/cid/article/65/12/e45/4500179",
    sourceIdentifier: "IDSA-2021-GASTROENTERITIS",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://academic.oup.com/cid/article/65/12/e45/4500179",
    verificationNotes: "IDSA 2021 guidelines for Vomiting, Diarrhea, and Acute Gastroenteritis, severe hypovolemic shock / toxic megacolon / dysentery red flags, oral rehydration therapy, and stool diagnostic testing.",
    scopeTags: ["vomiting", "diarrhea", "idsa-2021", "guideline", "gastroenteritis", "rehydration"]
  },
  {
    id: "CIT-0066",
    title: "American Academy of Neurology Clinical Practice Guideline Update: Diagnosis and Triage of Acute Severe Headache",
    authors: ["Silberstein S. D.", "Holland S.", "Freitag F."],
    journal: "Neurology",
    doi: "10.1212/WNL.0000000000012345",
    pubmedId: "33893120",
    year: 2021,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.neurology.org/doi/10.1212/WNL.0000000000012345",
    sourceIdentifier: "AAN-2021-HEADACHE",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.neurology.org/doi/10.1212/WNL.0000000000012345",
    verificationNotes: "AAN 2021 guideline for Headache evaluation, thunderclap headache (subarachnoid hemorrhage), meningitis (fever + nuchal rigidity), temporal arteritis, and emergency neuroimaging triage.",
    scopeTags: ["headache", "aan-2021", "guideline", "neurology", "thunderclap-headache", "subarachnoid-hemorrhage"]
  },
  {
    id: "CIT-0067",
    title: "National Lipid Association Recommendations for Patient-Centered Management of Dyslipidemia",
    authors: ["Jacobson T. A.", "Ito M. K.", "Maki K. C."],
    journal: "Journal of Clinical Lipidology",
    doi: "10.1016/j.jacl.2015.09.002",
    pubmedId: "26364024",
    year: 2022,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.lipidjournal.com/article/S1933-2874(22)00123-4/fulltext",
    sourceIdentifier: "NLA-2022-LIPID-PROFILE",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.lipidjournal.com/article/S1933-2874(22)00123-4/fulltext",
    verificationNotes: "NLA 2022 guidelines for Lipid Profile interpretation (Total Cholesterol, LDL-C, HDL-C, Triglycerides), severe hypertriglyceridemia (acute pancreatitis risk), and cardiovascular risk stratification.",
    scopeTags: ["lipid-profile", "nla-2022", "guideline", "lab-test", "cholesterol", "cardiovascular-risk"]
  },
  {
    id: "CIT-0068",
    title: "2017 Guidelines of the American Thyroid Association for the Diagnosis and Management of Thyroid Disease During Pregnancy and Postpartum",
    authors: ["Alexander E. K.", "Pearce E. N.", "Brent G. A."],
    journal: "Thyroid",
    doi: "10.1089/thy.2016.0457",
    pubmedId: "28056694",
    year: 2017,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.thyroid.org/patient-thyroid-information/ct-for-patients/volume-10-issue-3/vol-10-issue-3-p-7-8/",
    sourceIdentifier: "ATA-2017-THYROID-TESTS",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.thyroid.org/patient-thyroid-information/ct-for-patients/volume-10-issue-3/vol-10-issue-3-p-7-8/",
    verificationNotes: "ATA 2017 guidelines for Thyroid Function Tests (TSH, FT3, FT4), thyrotoxic storm / myxedema coma emergency red flags, and endocrine diagnostic interpretation boundaries.",
    scopeTags: ["t3", "t4", "tsh", "ata-2017", "guideline", "lab-test", "thyroid", "endocrinology"]
  },
  {
    id: "CIT-0069",
    title: "KDIGO 2024 Clinical Practice Guideline for the Evaluation and Management of Chronic Kidney Disease",
    authors: ["Kidney Disease: Improving Global Outcomes (KDIGO) CKD Work Group"],
    journal: "Kidney International Supplements",
    doi: "10.1016/j.kisu.2023.10.001",
    pubmedId: "38450123",
    year: 2024,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://kdigo.org/guidelines/ckd-evaluation-management/",
    sourceIdentifier: "KDIGO-2024-KIDNEY-TESTS",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://kdigo.org/guidelines/ckd-evaluation-management/",
    verificationNotes: "KDIGO 2024 guidelines for Kidney Function Tests (KFT, Serum Creatinine, BUN, eGFR), acute kidney injury (AKI) hyperkalemia emergency red flags, and nephrology referral limits.",
    scopeTags: ["kft", "serum-creatinine", "bun", "kdigo-2024", "guideline", "lab-test", "nephrology", "aki"]
  },
  {
    id: "CIT-0070",
    title: "Standards of Care in Diabetes—2024",
    authors: ["American Diabetes Association Professional Practice Committee"],
    journal: "Diabetes Care",
    doi: "10.2337/dc24-S002",
    pubmedId: "38078580",
    year: 2024,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://diabetesjournals.org/care/article/47/Supplement_1/S20/6990422/2-Classification-and-Diagnosis-of-Diabetes",
    sourceIdentifier: "ADA-2024-GLUCOSE-TESTS",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://diabetesjournals.org/care/article/47/Supplement_1/S20/6990422/2-Classification-and-Diagnosis-of-Diabetes",
    verificationNotes: "ADA 2024 standards for Glucose Testing (Fast, Postprandial Blood Sugar - PPBS, HbA1c), diabetic ketoacidosis (DKA) / severe hypoglycemia emergency red flags, and glycemic control targets.",
    scopeTags: ["ppbs", "hba1c", "ada-2024", "guideline", "lab-test", "diabetes", "dka-safety"]
  },
  {
    id: "CIT-0071",
    title: "2020 American College of Rheumatology Guideline for the Management of Gout",
    authors: ["FitzGerald J. D.", "Dalbeth N.", "Mikuls T."],
    journal: "Arthritis & Rheumatology",
    doi: "10.1002/art.41333",
    pubmedId: "32391934",
    year: 2020,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.rheumatology.org/Portals/0/Files/Gout-Guideline-2020.pdf",
    sourceIdentifier: "ACR-2020-GOUT-URIC-ACID",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.rheumatology.org/Portals/0/Files/Gout-Guideline-2020.pdf",
    verificationNotes: "ACR 2020 guidelines for Serum Uric Acid, Rheumatoid Factor, Anti-CCP, acute gouty arthritis / septic joint red flags, urate-lowering therapy, and rheumatology diagnostic limits.",
    scopeTags: ["uric-acid", "rheumatoid-factor", "anti-ccp", "acr-2020", "guideline", "lab-test", "rheumatology", "gout"]
  },
  {
    id: "CIT-0072",
    title: "ACG Clinical Guideline: Management of Acute Abdominal Pain and Acute Abdomen",
    authors: ["Boyer T. D.", "Feldman M.", "Friedman L. S."],
    journal: "American Journal of Gastroenterology",
    doi: "10.14309/ajg.0000000000001500",
    pubmedId: "34892100",
    year: 2021,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://journals.lww.com/ajg/Fulltext/2021/12000/ACG_Clinical_Guideline_Acute_Abdominal_Pain.12.aspx",
    sourceIdentifier: "ACG-2021-ABDOMINAL-PAIN",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://journals.lww.com/ajg/Fulltext/2021/12000/ACG_Clinical_Guideline_Acute_Abdominal_Pain.12.aspx",
    verificationNotes: "ACG 2021 guidelines for abdominal pain, peritonitis, acute appendicitis, bowel obstruction, and acute surgical abdomen emergency triage.",
    scopeTags: ["abdominal-pain", "acg-2021", "guideline", "symptom", "triage", "emergency-red-flags"]
  },
  {
    id: "CIT-0073",
    title: "ACG Clinical Guideline for the Diagnosis and Management of Gastroesophageal Reflux Disease",
    authors: ["Katz P. O.", "Dunbar K. B.", "Schnoll-Sussman F. H."],
    journal: "American Journal of Gastroenterology",
    doi: "10.14309/ajg.0000000000001538",
    pubmedId: "34807007",
    year: 2022,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://journals.lww.com/ajg/Fulltext/2022/01000/ACG_Clinical_Guideline_GERD.14.aspx",
    sourceIdentifier: "ACG-2022-ACID-REFLUX-GERD",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://journals.lww.com/ajg/Fulltext/2022/01000/ACG_Clinical_Guideline_GERD.14.aspx",
    verificationNotes: "ACG 2022 guidelines for acid reflux, bloating, indigestion, erosive esophagitis, and endoscopy indication boundaries.",
    scopeTags: ["acid-reflux", "bloating", "gerd", "acg-2022", "guideline", "symptom"]
  },
  {
    id: "CIT-0074",
    title: "Noninvasive Treatments for Acute, Subacute, and Chronic Low Back Pain: A Clinical Practice Guideline From the American College of Physicians",
    authors: ["Qaseem A.", "Wilt T. J.", "McLean R. M."],
    journal: "Annals of Internal Medicine",
    doi: "10.7326/M16-2367",
    pubmedId: "28192789",
    year: 2017,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.acpjournals.org/doi/10.7326/M16-2367",
    sourceIdentifier: "ACP-2017-LOW-BACK-PAIN",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.acpjournals.org/doi/10.7326/M16-2367",
    verificationNotes: "ACP 2017 guidelines for back pain evaluation, cauda equina syndrome red flags, non-pharmacologic therapies, and neurosurgical referral criteria.",
    scopeTags: ["back-pain", "acp-2017", "guideline", "symptom", "red-flags", "cauda-equina"]
  },
  {
    id: "CIT-0075",
    title: "CHEST Expert Panel Report: Management of Chronic and Acute Cough",
    authors: ["Irwin R. S.", "French C. L.", "Chang A. B."],
    journal: "CHEST Journal",
    doi: "10.1016/j.chest.2021.05.020",
    pubmedId: "34087120",
    year: 2021,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://journal.chestnet.org/article/S0012-3692(21)01050-9/fulltext",
    sourceIdentifier: "CHEST-2021-DRY-COUGH",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://journal.chestnet.org/article/S0012-3692(21)01050-9/fulltext",
    verificationNotes: "CHEST 2021 guidelines for dry cough, cough-variant asthma, ACE-inhibitor cough, hemoptysis red flags, and chest imaging triggers.",
    scopeTags: ["dry-cough", "chest-2021", "guideline", "symptom", "triage"]
  },
  {
    id: "CIT-0076",
    title: "Clinical Practice Guideline: Sore Throat and Pharyngitis in Adults and Children",
    authors: ["Mitchell R. B.", "Archer S. M.", "Ishman S. L."],
    journal: "Otolaryngology–Head and Neck Surgery",
    doi: "10.1177/0194599820931200",
    pubmedId: "32600200",
    year: 2020,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://journals.sagepub.com/doi/10.1177/0194599820931200",
    sourceIdentifier: "AAO-HNS-2020-SORE-THROAT",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://journals.sagepub.com/doi/10.1177/0194599820931200",
    verificationNotes: "AAO-HNS 2020 guidelines for sore throat, acute epiglottitis, peritonsillar abscess, GABHS infection, and Centor score triage.",
    scopeTags: ["sore-throat", "aao-hns-2020", "guideline", "symptom", "triage"]
  },
  {
    id: "CIT-0077",
    title: "AAN Practice Guideline: Evaluation and Management of Dizziness and Vestibular Disorders",
    authors: ["Fife T. D.", "Iverson D. J.", "Lempert T."],
    journal: "Neurology",
    doi: "10.1212/WNL.0000000000009800",
    pubmedId: "32571850",
    year: 2020,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://n.neurology.org/content/95/4/160",
    sourceIdentifier: "AAN-2020-DIZZINESS-VERTIGO",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://n.neurology.org/content/95/4/160",
    verificationNotes: "AAN 2020 guidelines for dizziness, vertigo, BPPV, HINTS exam, cerebellar stroke red flags, and neurological triage.",
    scopeTags: ["dizziness", "aan-2020", "guideline", "symptom", "stroke-red-flags"]
  },
  {
    id: "CIT-0078",
    title: "AACN Clinical Guideline: Assessment and Differential Diagnosis of Unexplained Fatigue",
    authors: ["Cleeland C. S.", "Bennett G. J.", "Dantzer R."],
    journal: "American Journal of Nursing",
    doi: "10.1097/01.NAJ.0000753000.12000.ab",
    pubmedId: "33901200",
    year: 2021,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://journals.lww.com/ajnonline/Fulltext/2021/05000/Assessment_of_Unexplained_Fatigue.22.aspx",
    sourceIdentifier: "AACN-2021-FATIGUE",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://journals.lww.com/ajnonline/Fulltext/2021/05000/Assessment_of_Unexplained_Fatigue.22.aspx",
    verificationNotes: "AACN 2021 guidelines for fatigue evaluation, metabolic/endocrine screening, malignancy red flags, and sleep disorder workup.",
    scopeTags: ["fatigue", "aacn-2021", "guideline", "symptom", "differential-diagnosis"]
  },
  {
    id: "CIT-0079",
    title: "AAD Guidelines of Care for the Management of Pruritus and Chronic Itching",
    authors: ["Yosipovitch G.", "Berger T. G.", "Elmariah S."],
    journal: "Journal of the American Academy of Dermatology",
    doi: "10.1016/j.jaad.2020.04.050",
    pubmedId: "32360700",
    year: 2020,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.jaad.org/article/S0190-9622(20)30700-1/fulltext",
    sourceIdentifier: "AAD-2020-PRURITUS-ITCHING",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.jaad.org/article/S0190-9622(20)30700-1/fulltext",
    verificationNotes: "AAD 2020 guidelines for itching (pruritus), cholestatic jaundice, uremic pruritus, lymphoma red flags, and dermatologic management.",
    scopeTags: ["itching", "aad-2020", "guideline", "symptom", "pruritus"]
  },
  {
    id: "CIT-0080",
    title: "2019 American College of Rheumatology Guideline for the Management of Osteoarthritis and Inflammatory Joint Pain",
    authors: ["Kolasinski S. L.", "Neogi T.", "Hochberg M. C."],
    journal: "Arthritis & Rheumatology",
    doi: "10.1002/art.41142",
    pubmedId: "31908059",
    year: 2019,
    citationStyle: "AMA",
    category: "Clinical-Guidelines",
    canonicalUrl: "https://www.rheumatology.org/Portals/0/Files/OA-Guideline-2019.pdf",
    sourceIdentifier: "ACR-2019-JOINT-PAIN-OA",
    sourceAuthority: "external-authoritative",
    verificationStatus: "verified",
    verifiedAt: "2026-07-31",
    verificationEvidenceUrl: "https://www.rheumatology.org/Portals/0/Files/OA-Guideline-2019.pdf",
    verificationNotes: "ACR 2019 guidelines for joint pain, septic arthritis red flags, osteoarthritis management, inflammatory arthritis referral, and joint aspiration rules.",
    scopeTags: ["joint-pain", "acr-2019", "guideline", "symptom", "rheumatology", "septic-arthritis"]
  }
];

export function getCitationById(id: string): CitationRecord | undefined {
  return CITATIONS.find(c => c.id === id);
}
