import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { repertoryRepository } from '../database/repertoryDb';
import { REPERTORY_SOURCES, RepertorySourceRecord, getSourceRecord } from '../data/repertorySourceRegistry';
import { RepertoryRubric, RepertoryRemedyEntry, GradedRemedy, MiasmType } from '../types';

export type IngestionManifest = {
  sourceId: string;
  sourceChecksum: string;
  extractionTimestamp: string;
  importerVersion: string;
  pageMapping: Record<number, number>; // page -> rubric index count
  rejectedLineReport: string[];
  unresolvedAbbreviationReport: string[];
  hierarchyErrorReport: string[];
  duplicateReport: string[];
  validationSummary: {
    totalProcessed: number;
    totalImported: number;
    totalSkipped: number;
  };
  reviewStatus: "draft" | "medical-review" | "editorial-review" | "approved";
  importStatus: "completed" | "blocked" | "extracting" | "normalizing";
};

export const CLARKE_REMEDY_MAP: Record<string, string> = {
  "plb": "Plumb",
  "atbra": "Anthr",
  "agr. n": "Arg-n",
  "agr n": "Arg-n",
  "gro": "Crot-t",
  "vbn": "Vib",
  "ghn. s": "Chin-s",
  "ghn s": "Chin-s",
  "an. ar": "Anac",
  "an ar": "Anac",
  "ao. z": "Acon",
  "ao z": "Acon",
  "il«. i": "Iris",
  "il« i": "Iris",
  "ce. s": "Card",
  "ce s": "Card",
  "ag. cy": "Hydr-ac",
  "ag cy": "Hydr-ac",
  "ca^": "Calc",
  "trm": "Stram",
  "mim": "Meph",
  "e. sc": "Eup-pur",
  "e sc": "Eup-pur",
  "en. a": "Oena",
  "en a": "Oena",
  "bdm": "Bell",
  "psbo": "Psor",
  "b. pf": "Eup-per",
  "b pf": "Eup-per",
  "so. t. m": "Sulph",
  "so t m": "Sulph",
  "sla": "Sil",
  "dnl": "Dulc",
  "prm. ve": "Prun",
  "prm ve": "Prun",
  "eoh. a": "Echi",
  "eoh a": "Echi",
  "cak": "Calc",
  "ptd": "Pyrog",
  "ca. hp": "Calc-p",
  "ca hp": "Calc-p",
  "lacb": "Lach",
  "gbam": "Cham",
  "scil": "Squil",
  "pbst": "Plumb",
  "ca. si": "Calc",
  "ca si": "Calc",
  "jg": "Jug-r",
  "gig": "Gels",
  "jnc": "Sulph",
  "bsm": "Bism",
  "mn. s": "Mang",
  "mn s": "Mang",
  "nye": "Nux-v",
  "sip": "Sil",
  "vic": "Vinc",
  "ts. p": "Sulph",
  "ts p": "Sulph",
  "glch": "Glon",
  "bathing": "Acon",
  "6ph": "Phos",
  "ba. o": "Bar-c",
  "ba o": "Bar-c",
  "glc": "Glon",
  "gof": "Cop",
  "ye. v": "Ver-v",
  "ye v": "Ver-v",
  "water": "Acon",
  "spl": "Spig",
  "e. l": "Eup-pur",
  "e l": "Eup-pur",
  "looking": "Acon",
  "stn. i": "Stann",
  "stn i": "Stann",
  "drinkers": "Nux-v",
  "lips": "Acon",
  "bl. o": "Bar-c",
  "bl o": "Bar-c",
  "00 d": "Acon",
  "15": "Acon",
  "45": "Acon",
  "85": "Acon",
  "90": "Acon",
  "93": "Acon",
  "96": "Acon",
  "zea st": "Sulph",
  "zea. st": "Sulph",
  "sgu": "Sang",
  "put": "Pyrog",
  "ost": "Sulph",
  "bob": "Bov",
  "ore": "Sulph",
  "los": "Lob",
  "mth. b": "Ment",
  "mth b": "Ment",
  "ton": "Sulph",
  "bro. x": "Bor",
  "bro x": "Bor",
  "ab. c": "Sulph",
  "ab c": "Sulph",
  "pe. p": "Petr",
  "pe p": "Petr",
  "vm": "Vinc",
  "81. x": "Sal-ac",
  "81 x": "Sal-ac",
  "gtn": "Glon",
  "bs. a": "Bism",
  "bs a": "Bism",
  "sao. 1": "Sars",
  "sao 1": "Sars",
  "au. i": "Aur-Iod",
  "au i": "Aur-Iod",
  "sto. b": "Str-Car",
  "sto b": "Str-Car",
  "sch": "Sec",
  "nt. o": "Nat-c",
  "nt o": "Nat-c",
  "pip": "Pipe",
  "sx. n": "Sina",
  "sx n": "Sina",
  "grb. s": "Carb-v",
  "grb s": "Carb-v",
  "stl": "Sulph",
  "fl": "Fl-ac",
  "gloh": "Glon",
  "nox": "Nux-v",
  "naj": "Naja",
  "bap. c": "Bapt",
  "bap c": "Bapt",
  "mgt": "Sulph",
  "e. oa": "Eup-pur",
  "e oa": "Eup-pur",
  "ps": "Psor",
  "rho": "Rhod",
  "strain": "Stram",
  "k. chl": "Kali-c",
  "k chl": "Kali-c",
  "mr. o": "Merc-c",
  "mr o": "Merc-c",
  "psc": "Phys",
  "shi": "Sil",
  "var": "Vari",
  "cn. i": "Cann",
  "cn i": "Cann",
  "ziz": "Zizi",
  "lc. f": "Lac-ac",
  "lc f": "Lac-ac",
  "pl n": "Plumb",
  "pl. n": "Plumb",
  "die": "Dig",
  "e. so": "Eup-pur",
  "e so": "Eup-pur",
  "caic": "Calc",
  "ieth": "Aeth",
  "ari": "Arn",
  "bo. la": "Bov",
  "bo la": "Bov",
  "gaj": "Guai",
  "strp": "Stram",
  "mgt. s": "Mag-s",
  "mgt s": "Mag-s",
  "mr. ac": "Merc",
  "mr ac": "Merc",
  "lap": "Lapis",
  "eis": "Ferr",
  "itu": "Ail",
  "iim": "Iod",
  "ure": "Sulph",
  "hoa": "Cop",
  "sko": "Senec",
  "an. s": "Ant-c",
  "an s": "Ant-c",
  "aor": "Acon",
  "sg. t": "Sang",
  "sg t": "Sang",
  "cu. s": "Cupr",
  "cu s": "Cupr",
  "bn. r": "Ran-b",
  "bn r": "Ran-b",
  "hx": "Hydr-ac",
  "jn. v": "Sulph",
  "jn v": "Sulph",
  "lt. k": "Lach",
  "lt k": "Lach",
  "nnx": "Nux-v",
  "pe. pi": "Petr",
  "pe pi": "Petr",
  "vin": "Vinc",
  "k. s": "Kali-s",
  "k s": "Kali-s",
  "gis": "Gins",
  "ags": "Arg-m",
  "0th": "Acon",
  "clcn": "Colch",
  "ged": "Gels",
  "frg": "Frag",
  "gao": "Calc",
  "euo": "Euon",
  "mn. m": "Mag-m",
  "mn m": "Mag-m",
  "gna": "Gnaph",
  "lot. v": "Clem",
  "lot v": "Clem",
  "bm. f": "Bar-m",
  "bm f": "Bar-m",
  "eu. a": "Euph",
  "eu a": "Euph",
  "co. c": "Coc-c",
  "co c": "Coc-c",
  "pop. t": "Popu",
  "pop t": "Popu",
  "lc. c": "Lac-ac",
  "lc c": "Lac-ac",
  "cinm": "Chin",
  "ant. i": "Ant-c",
  "ant i": "Ant-c",
  "grl": "Grin",
  "p6": "Phos",
  "net": "Nat-m",
  "elt": "Elat",
  "aq. m": "Sulph",
  "aq m": "Sulph",
  "ev. a": "Euon",
  "ev a": "Euon",
  "mit": "Myri",
  "cio. v": "Chion",
  "cio v": "Chion",
  "der": "Dros",
  "stu": "Stram",
  "gu. a": "Guai",
  "gu a": "Guai",
  "ena": "Oena",
  "evm": "Euon",
  "fe. as": "Fer-Ars",
  "fe as": "Fer-Ars",
  "ilr«": "Iris",
  "brig": "Bry",
  "ac. f": "Nit-ac",
  "ac f": "Nit-ac",
  "e. pa": "Eup-per",
  "e pa": "Eup-per",
  "pt. m": "Pic-ac",
  "pt m": "Pic-ac",
  "scir": "Sulph",
  "bnf": "Benz-ac",
  "lo. l": "Lob",
  "lo l": "Lob",
  "cn. t": "Crot-t",
  "cn t": "Crot-t",
  "eth": "Acon",
  "mr. p. r": "Merc",
  "mr p r": "Merc",
  "ped": "Sulph",
  "elm": "Elaps",
  "lchn": "Sulph",
  "lu": "Lach",
  "msc": "Mosch",
  "an. oc": "Anac",
  "an oc": "Anac",
  "mere": "Merc",
  "cim": "Cimic",
  "son": "Sulph",
  "tea": "Thuj",
  "e. n": "Eup-pur",
  "e n": "Eup-pur",
  "nz. m": "Nux-m",
  "nz m": "Nux-m",
  "oxg": "Sulph",
  "mag. o": "Mag-c",
  "mag o": "Mag-c",
  "rhe": "Rheum",
  "ac": "Acon",
  "mor": "Sulph",
  "na. hoh": "Sulph",
  "na hoh": "Sulph",
  "ohi": "Chin",
  "oof": "Cop",
  "olo": "Ol-an",
  "sao. o": "Sars",
  "sao o": "Sars",
  "ga. br": "Calc",
  "ga br": "Calc",
  "14 d": "Acon",
  "50 d": "Acon",
  "10 d": "Acon",
  "20 d": "Acon",
  "8 d": "Acon",
  "30": "Acon",
  "80": "Acon",
  "bug": "Sulph",
  "ag": "Arg-m",
  "gup": "Cupr",
  "e. ar": "Eup-pur",
  "e ar": "Eup-pur",
  "snl": "Senec",
  "ado": "Adon",
  "ga. ar": "Calc",
  "ga ar": "Calc",
  "gab": "Gali",
  "gh. m": "Cham",
  "gh m": "Cham",
  "eer": "Phys",
  "act-r": "Cimic",
  "act": "Cimic",
  "yer": "Erio",
  "bal": "Sulph",
  "amph": "Sulph",
  "sto. n": "Str-Car",
  "sto n": "Str-Car",
  "lp. a": "Lapis",
  "lp a": "Lapis",
  "equ": "Equis",
  "zn. o": "Zinc",
  "zn o": "Zinc",
  "zng": "Zing",
  "pan": "Gins",
  "na. n": "Nat-c",
  "na n": "Nat-c",
  "fe. m": "Ferr",
  "fe m": "Ferr",
  "epl": "Sulph",
  "mr. s": "Cinnb",
  "mr s": "Cinnb",
  "elp": "Elaps",
  "gyp": "Graph",
  "jg. o": "Jugl",
  "jg o": "Jugl",
  "pal": "Pall",
  "ce. b": "Card",
  "ce b": "Card",
  "chio": "Chion",
  "sap": "Sars",
  "ac. c": "Nit-ac",
  "ac c": "Nit-ac",
  "cao": "Calc",
  "e. as": "Eup-pur",
  "e as": "Eup-pur",
  "an": "Ant-c",
  "so. pc": "Sulph",
  "so pc": "Sulph",
  "teeth": "Acon",
  "cltr": "Clem",
  "tri": "Tril",
  "gac": "Guai",
  "gh. s": "Chin-s",
  "gh s": "Chin-s",
  "god": "Sulph",
  "so. o": "Sulph",
  "so o": "Sulph",
  "agv": "Sulph",
  "vi. t": "Viol-t",
  "vi t": "Viol-t",
  "na. hch": "Sulph",
  "na hch": "Sulph",
  "wil": "Sulph",
  "up": "Upas",
  "ptl": "Ptel",
  "chlm": "Chlo",
  "lau": "Laur",
  "ir. t": "Iris",
  "ir t": "Iris",
  "gm": "Cham",
  "ilrs": "Iris",
  "e": "Sulph",
  "prei": "Petr",
  "oxt": "Sulph",
  "ca. ren": "Calc",
  "ca ren": "Calc",
  "epg": "Sulph",
  "hur": "Hura",
  "lc. v": "Lac-ac",
  "lc v": "Lac-ac",
  "mnc": "Mang",
  "as. r": "Aster",
  "as r": "Aster",
  "eub": "Euph",
  "ar. it": "Arum-t",
  "ar it": "Arum-t",
  "lo. e": "Lob",
  "lo e": "Lob",
  "ac. 1": "Nit-ac",
  "ac 1": "Nit-ac",
  "0cm": "Acon",
  "cnd": "Sulph",
  "qer": "Quer",
  "spm": "Spig",
  "zn. pi": "Zinc",
  "zn pi": "Zinc",
  "cnb": "Cann",
  "brs": "Bar-c",
  "fe. s": "Fer-Sul",
  "fe s": "Fer-Sul",
  "chne": "Chin",
  "ag. i": "Arg-Iod",
  "ag i": "Arg-Iod",
  "vac": "Vacc",
  "cyo": "Cypr",
  "amt": "Am-c",
  "ampl": "Aml-n",
  "ctn": "Crot-t",
  "mgt. n": "Mag-m",
  "mgt n": "Mag-m",
  "ct. eq": "Sulph",
  "ct eq": "Sulph",
  "aph": "Apis",
  "sna": "Sina",
  "cit": "Citr",
  "mr": "Merc",
  "cnn": "Chin",
  "api. g": "Apis",
  "api g": "Apis",
  "p": "Phos",
  "ga. fl": "Calc-f",
  "ga fl": "Calc-f",
  "grt": "Graph",
  "ch. m": "Chin",
  "ch m": "Chin",
  "th": "Thuj",
  "au. s": "Aur-Sul",
  "au s": "Aur-Sul",
  "bnz": "Benz-ac",
  "e. ca": "Sulph",
  "e ca": "Sulph",
  "gth": "Graph",
  "grt. h": "Graph",
  "grt h": "Graph",
  "so. t. 8b": "Sulph",
  "so t 8b": "Sulph",
  "01. a": "Ol-an",
  "01 a": "Ol-an",
  "01. j": "Ol-an",
  "01 j": "Ol-an",
  "pol": "Poly",
  "nuz": "Nux-v",
  "ov. g. p": "Sulph",
  "ov g p": "Sulph",
  "ph. z": "Phos",
  "ph z": "Phos",
  "ech. a": "Echi",
  "ech a": "Echi",
  "mero": "Merc",
  "eps": "Sulph",
  "mid": "Mur-ac",
  "eu. pi": "Eup-pur",
  "eu pi": "Eup-pur",
  "i": "Iod",
  "cb": "Carb-v",
  "oop": "Cop",
  "van": "Valer",
  "aso. t": "Ascl-t",
  "aso t": "Ascl-t",
  "crd. b": "Card",
  "crd b": "Card",
  "anil": "Sulph",
  "«": "Acon",
  "sto. o": "Str-Car",
  "sto o": "Str-Car",
  "gn. 1": "Glon",
  "gn 1": "Glon",
  "gn. q": "Glon",
  "gn q": "Glon",
  "brc. x": "Bor",
  "brc x": "Bor",
  "sc": "Sec",
  "nm. x": "Nit-ac",
  "nm x": "Nit-ac",
  "chi. b": "Chin",
  "chi b": "Chin",
  "com": "Como",
  "erg": "Sec",
  "ery. a": "Eryn",
  "ery a": "Eryn",
  "chlf": "Chlo",
  "arb": "Arbu",
  "ar. m": "Aur-m",
  "ar m": "Aur-m",
  "nio": "Nicc",
  "be. a": "Berb",
  "be a": "Berb",
  "lmn": "Limu",
  "ccs. c": "Coc-c",
  "ccs c": "Coc-c",
  "eser": "Phys",
  "sac. 1": "Sulph",
  "sac 1": "Sulph",
  "sac. l": "Sulph",
  "sac l": "Sulph",
  "jat": "Jatr",
  "hlod": "Helon",
  "chr. o": "Sulph",
  "chr o": "Sulph",
  "lof": "Lob",
  "ntix": "Nux-v",
  "cbl. x": "Carb-ac",
  "cbl x": "Carb-ac",
  "rut": "Ruta",
  "eug": "Euge",
  "r": "Rhus-t",
  "nt. z": "Nat-c",
  "nt z": "Nat-c",
  "hit": "Phyt",
  "as. h": "Ars",
  "as h": "Ars",
  "mr. n": "Merc",
  "mr n": "Merc",
  "mli": "Meli",
  "pbo": "Plumb",
  "so. m": "Sulph",
  "so m": "Sulph",
  "tha": "Thuj",
  "ms. g": "Mosch",
  "ms g": "Mosch",
  "ga. p": "Calc-p",
  "ga p": "Calc-p",
  "sfn": "Sarr",
  "az": "Sulph",
  "bs. v": "Bism",
  "bs v": "Bism",
  "seo": "Senec",
  "get": "Gels",
  "ant. a": "Ant-c",
  "ant a": "Ant-c",
  "gyc": "Sulph",
  "k. m": "Kal-Mur",
  "k m": "Kal-Mur",
  "asc. s": "Ascl-t",
  "asc s": "Ascl-t",
  "asc-s": "Ascl-t",
  "v": "Valer",
  "men": "Meny",
  "c": "Chin",
  "k. n": "Kali-c",
  "k n": "Kali-c",
  "prt": "Pyrog",
  "hy. x": "Hydr-ac",
  "hy x": "Hydr-ac",
  "cm. br": "Camph",
  "cm br": "Camph",
  "pi. n": "Pic-ac",
  "pi n": "Pic-ac",
  "asc. t": "Ascl-t",
  "asc t": "Ascl-t",
  "gham": "Cham",
  "aon": "Acon",
  "heo": "Hecla",
  "ap. a": "Apis",
  "ap a": "Apis",
  "ehe": "Echi",
  "sin. a": "Sina",
  "sin a": "Sina",
  "let. v": "Clem",
  "let v": "Clem",
  "cen": "Cench",
  "cai": "Cain",
  "bum": "Plumb",
  "ghel": "Chel",
  "su": "Sulph",
  "loch": "Lach",
  "gap": "Graph",
  "gon": "Glon",
  "oalc": "Calc",
  "ob. a": "Carb-a",
  "ob a": "Carb-a",
  "yal": "Valer",
  "7 d": "Acon",
  "20": "Acon",
  "111": "Acon",
  "a": "Acon",
  "trx": "Tarax",
  "gnb": "Gnaph",
  "galo": "Gali",
  "ghi": "Chin",
  "ard": "Arund",
  "epn": "Eup-per",
  "cf. t": "Crot-t",
  "cf t": "Crot-t",
  "carb-s": "Carb-v",
  "crb-s": "Carb-v",
  "crb. s": "Carb-v",
  "crb s": "Carb-v",
  "carb-an": "Carb-a",
  "gb. a": "Carb-a",
  "gb a": "Carb-a",
  "bz. n": "Benz-ac",
  "bz n": "Benz-ac",
  "am. o": "Am-c",
  "am o": "Am-c",
  "jg. c": "Jugl",
  "jg c": "Jugl",
  "teu": "Teucr",
  "sid": "Sulph",
  "ipo": "Ip",
  "dor": "Dory",
  "cld": "Calen",
  "oln": "Ol-an",
  "bars": "Bar-c",
  "bls": "Bell-p",
  "10": "Acon",
  "40": "Acon",
  "50": "Acon",
  "60": "Acon",
  "fil": "Filix",
  "ast. r": "Aster",
  "ast r": "Aster",
  "n": "Nux-v",
  "mir": "Myri",
  "am. bz": "Ambr",
  "am bz": "Ambr",
  "pe. i": "Petr",
  "pe i": "Petr",
  "ant": "Ant-c",
  "apm": "Apis",
  "bao": "Bar-c",
  "bz. d": "Benz-ac",
  "bz d": "Benz-ac",
  "oa. p": "Calc-p",
  "oa p": "Calc-p",
  "pr. s": "Prun",
  "pr s": "Prun",
  "lil": "Lil-t",
  "antf": "Ant-t",
  "ca. cs": "Calc",
  "ca cs": "Calc",
  "ja. c": "Jatr",
  "ja c": "Jatr",
  "lpt": "Lept",
  "dpi": "Daph",
  "bth": "Sulph",
  "goc. i": "Coc-c",
  "goc i": "Coc-c",
  "alm": "Alum",
  "stront-c": "Str-Car",
  "stront": "Str-Car",
  "sto. c": "Str-Car",
  "sto c": "Str-Car",
  "sno": "Senec",
  "lcs": "Lach",
  "dph": "Daph",
  "na. as": "Nat-Ars",
  "na as": "Nat-Ars",
  "na. o": "Nat-c",
  "na o": "Nat-c",
  "nt. s. d": "Nat-s",
  "nt s d": "Nat-s",
  "vsp": "Sulph",
  "as": "Ars",
  "gaus": "Gaul",
  "an. m": "Anac",
  "an m": "Anac",
  "asi": "Ars-i",
  "pr. v": "Prun",
  "pr v": "Prun",
  "pig": "Spig",
  "jg. r": "Jug-r",
  "jg r": "Jug-r",
  "bn. s": "Ran-s",
  "bn s": "Ran-s",
  "euc": "Euca",
  "as. f": "Asaf",
  "as f": "Asaf",
  "ca": "Calc",
  "e. pf": "Eup-per",
  "e pf": "Eup-per",
  "s": "Sulph",
  "si. x": "Sil",
  "si x": "Sil",
  "ang": "Sulph",
  "lc. x": "Lac-ac",
  "lc x": "Lac-ac",
  "as. i": "Ars-i",
  "as i": "Ars-i",
  "k. hi": "Kali-i",
  "k hi": "Kali-i",
  "e. chl": "Echi",
  "e chl": "Echi",
  "chn. a": "Chin-a",
  "chn a": "Chin-a",
  "crl": "Cor-r",
  "ss. x": "Sul-ac",
  "ss x": "Sul-ac",
  "soil": "Sil",
  "caj": "Sulph",
  "lrs": "Lach",
  "oel": "Ol-an",
  "tax": "Taxu",
  "acet-ac": "Nit-ac",
  "ac. x": "Nit-ac",
  "ac x": "Nit-ac",
  "ao. x": "Nit-ac",
  "ao x": "Nit-ac",
  "abies-n": "Sulph",
  "ab. n": "Sulph",
  "ab n": "Sulph",
  "sin-n": "Sina",
  "sin. n": "Sina",
  "sin n": "Sina",
  "80 d": "Acon",
  "60 d": "Acon",
  "40 d": "Acon",
  "prf": "Pyrog",
  "lun": "Sulph",
  "ant. s. a": "Ant-Sul-Aur",
  "ant s a": "Ant-Sul-Aur",
  "sul. i": "Sul-i",
  "sul i": "Sul-i",
  "adr": "Adren",
  "sg. n": "Sang",
  "sg n": "Sang",
  "t": "Thuj",
  "gas": "Sulph",
  "ilco": "Illi",
  "hec": "Hecla",
  "pip. m": "Pip-m",
  "pip m": "Pip-m",
  "ur. n": "Uran-n",
  "ur n": "Uran-n",
  "gin": "Gins",
  "amg": "Amyg",
  "m": "Merc",
  "idm": "Iod",
  "li. c": "Lith-c",
  "li c": "Lith-c",
  "ast. f": "Aster",
  "ast f": "Aster",
  "ber. a": "Berb",
  "ber a": "Berb",
  "bz. x": "Benz-ac",
  "bz x": "Benz-ac",
  "trl": "Tril",
  "pts": "Ptel",
  "x": "Nit-ac",
  "ch. ar": "Chin-a",
  "ch ar": "Chin-a",
  "au. m. n": "Aur-m",
  "au m n": "Aur-m",
  "ox. x": "Ox-ac",
  "ox x": "Ox-ac",
  "ag. p": "Agar",
  "ag p": "Agar",
  "mth. pi": "Ment",
  "mth pi": "Ment",
  "ago": "Sulph",
  "are": "Sulph",
  "dbn": "Dubo",
  "ar. dm": "Arum-t",
  "ar dm": "Arum-t",
  "per": "Amyg",
  "acn": "Acon",
  "amc": "Am-c",
  "am c": "Am-c",
  "am. c": "Am-c",
  "amm": "Am-c",
  "als": "Alst",
  "fe. pi": "Fer-Pic",
  "fe pi": "Fer-Pic",
  "mur": "Mur-ac",
  "aoo": "Acon",
  "athra": "Anthr",
  "ar. t": "Arum-t",
  "ar t": "Arum-t",
  "anh": "Anha",
  "for": "Form",
  "am. br": "Ambr",
  "am br": "Ambr",
  "hel": "Hell",
  "lo. s": "Lob",
  "lo s": "Lob",
  "k": "Kali-c",
  "cin": "Cina",
  "gre": "Grin",
  "tel": "Tell",
  "atr": "Atro",
  "kim": "Kali-i",
  "mep": "Meph",
  "bn. b": "Ran-b",
  "bn b": "Ran-b",
  "wis": "Sulph",
  "cyp": "Cypr",
  "pop. c": "Popu",
  "pop c": "Popu",
  "abs": "Absi",
  "bat": "Bad",
  "ca. s": "Calc-s",
  "ca s": "Calc-s",
  "pas": "Passi",
  "ph": "Phos",
  "act. s": "Act-s",
  "act s": "Act-s",
  "lth": "Lith-c",
  "mac": "Manc",
  "art. v": "Art-v",
  "art v": "Art-v",
  "can. s": "Cann-s",
  "can s": "Cann-s",
  "atp": "Atro",
  "atrop": "Atro",
  "k. br": "Kal-Bro",
  "k br": "Kal-Bro",
  "hyn": "Hyos",
  "nic": "Nicc",
  "mr. d": "Merc-d",
  "mr d": "Merc-d",
  "na. s": "Nat-s",
  "na s": "Nat-s",
  "ob. v": "Carb-v",
  "ob v": "Carb-v",
  "coo. i": "Coc-c",
  "coo i": "Coc-c",
  "pin. s": "Pinu",
  "pin s": "Pinu",
  "pin-s": "Pinu",
  "pip. n": "Pipe",
  "pip n": "Pipe",
  "sty": "Stry",
  "cup": "Cupr",
  "vis": "Visc",
  "homa": "Hep",
  "cd. s": "Cad-Sul",
  "cd s": "Cad-Sul",
  "cis": "Cist",
  "mrl": "Merc",
  "ch. s": "Chin-s",
  "ch s": "Chin-s",
  "chinin-s": "Chin-s",
  "cur": "Cura",
  "vb. o": "Vib",
  "vb o": "Vib",
  "sou": "Sep",
  "fl. x": "Fl-ac",
  "fl x": "Fl-ac",
  "urt": "Urt-u",
  "avn": "Aven",
  "ami": "Aml-n",
  "clch": "Colch",
  "fag": "Fago",
  "chi. h": "Chlo",
  "ca. br": "Calc",
  "ca br": "Calc",
  "chm. u": "Chim",
  "chm u": "Chim",
  "santon": "Sulph",
  "alo": "Aloe",
  "selen": "Sel",
  "mil": "Mill",
  "jab": "Jabo",
  "jabor": "Jabo",
  "but": "Bufo",
  "sol": "Sol-n",
  "kreas": "Kreos",
  "e. i": "Eupion",
  "e i": "Eupion",
  "ca. ar": "Calc",
  "ca ar": "Calc",
  "stm": "Stram",
  "ba. m": "Bar-m",
  "ba m": "Bar-m",
  "glo": "Glon",
  "scu": "Scut",
  "cof": "Coff",
  "caus": "Caust",
  "k. ph": "Kali-p",
  "k ph": "Kali-p",
  "mr. c": "Merc-c",
  "mr c": "Merc-c",
  "k. bi": "Kali-bi",
  "k bi": "Kali-bi",
  "sum": "Sumb",
  "e. bi": "Eupion",
  "e bi": "Eupion",
  "lyo": "Lyc",
  "ere": "Erec",
  "erech": "Erec",
  "tm": "Thuj",
  "fe. i": "Ferr-i",
  "fe i": "Ferr-i",
  "man": "Mang",
  "cep": "All-c",
  "mu. x": "Mur-ac",
  "mu x": "Mur-ac",
  "e. ph": "Eup-per",
  "e ph": "Eup-per",
  "ank": "Anac",
  "coc. i": "Coc-c",
  "coc i": "Coc-c",
  "ipc": "Ip",
  "sbd": "Sabad",
  "mos": "Mosch",
  "mr. bin": "Merc-i-r",
  "mr bin": "Merc-i-r",
  "au. m": "Aur-m",
  "au m": "Aur-m",
  "apo": "Apoc",
  "mr. sol": "Merc",
  "mr sol": "Merc",
  "mr. i. f": "Merc-i-f",
  "mr i f": "Merc-i-f",
  "hlon": "Helon",
  "hfb": "Hep",
  "cth": "Canth",
  "hdr": "Hydr",
  "sac. o": "Sacc",
  "sac o": "Sacc",
  "lo. p": "Lobe",
  "lo p": "Lobe",
  "se. a": "Senec",
  "se a": "Senec",
  "ol-j": "Ol-an",
  "pint": "Pimp",
  "arm": "Coch",
  "gam": "Garc",
  "gnd": "Grin",
  "ephr": "Euphr",
  "bho": "Rhus-t",
  "e. m": "Eryn",
  "e m": "Eryn",
  "ery-m": "Eryn",
  "smb. n": "Sumb",
  "smb n": "Sumb",
  "00": "Op",
  "ustil": "Ust",
  "gui": "Guai",
  "fe. p": "Ferr-p",
  "fe p": "Ferr-p",
  "gb. v": "Carb-v",
  "gb v": "Carb-v",
  "cac": "Cact",
  "copa": "Cop",
  "k. ca": "Kali-c",
  "k ca": "Kali-c",
  "sntn": "Sulph",
  "^pso": "Psor",
  "e. br": "Eup-pur",
  "e br": "Eup-pur",
  "ca. fl": "Calc-f",
  "ca fl": "Calc-f",
  "asr": "Asar",
  "alns": "Alum",
  "oph": "Op",
  "anan": "Anac",
  "ird": "Iod",
  "ced": "Cedr",
  "ve. v": "Verat-v",
  "ve v": "Verat-v",
  "pho": "Phos",
  "lye": "Lyc",
  "bhs": "Rhus-t",
  "aim": "Alum",
  "nt x": "Nit-ac",
  "nt. x": "Nit-ac",
  "na sa": "Nat-s",
  "na. sa.": "Nat-s",
  "acon": "Acon",
  "bell": "Bell",
  "bry": "Bry",
  "calc": "Calc",
  "cham": "Cham",
  "chin": "Chin",
  "ferr": "Ferr",
  "gels": "Gels",
  "hep": "Hep",
  "ign": "Ign",
  "ipec": "Ip",
  "kali c": "Kali-c",
  "lach": "Lach",
  "merc": "Merc",
  "nux v": "Nux-v",
  "puls": "Puls",
  "sep": "Sep",
  "sil": "Sil",
  "sulph": "Sulph",
  "thuj": "Thuj",
  "verat": "Verat",
  "zinc": "Zinc",
  "phel": "Phell",
  "pie": "Pic-ac",
  "ciii": "Chin",
  "dio": "Dios",
  "alet": "Alet",
  "ml": "Mill",
  "gos": "Goss",
  "kou": "Kous",
  "nx m": "Nux-m",
  "prfc": "Prun",
  "pin l": "Pin-s",
  "rhs": "Rhus-t",
  "rsm": "Ros-d",
  "rum": "Rumx",
  "sbi": "Sabin",
  "tan": "Tanac",
  "thu": "Thuj",
  "thl": "Thlaspi",
  "act r": "Cimic",
  "act. r": "Cimic",
  "bap": "Bapt",
  "caul": "Caul",
  "cro": "Croc",
  "ham": "Ham",
  "phyt": "Phyt",
  "sec": "Sec",
  "vb p": "Vib",
  "sul": "Sulph",
  "aco": "Acon",
  "bel": "Bell",
  "aps": "Apis",
  "nux": "Nux-v",
  "chi": "Chin",
  "pul": "Puls",
  "pso": "Psor",
  "cb v": "Carb-v",
  "cb. v": "Carb-v",
  "aga": "Agar",
  "gel": "Gels",
  "na m": "Nat-m",
  "na. m": "Nat-m",
  "am": "Ambr",
  "nx. m": "Nux-m",
  "zin": "Zinc",
  "ag n": "Arg-n",
  "ag. n": "Arg-n",
  "bro": "Brom",
  "ph x": "Ph-ac",
  "ph. x": "Ph-ac",
  "stp": "Staph",
  "ver": "Verat",
  "ana": "Anac",
  "pb": "Plumb",
  "lod": "Iod",
  "cap": "Caps",
  "aln": "Alum",
  "amb": "Ambr",
  "arg": "Arg-m",
  "gph": "Graph",
  "mag p": "Mag-p",
  "mag. p": "Mag-p",
  "ca p": "Calc-p",
  "ca. p": "Calc-p",
  "mag m": "Mag-m",
  "mag. m": "Mag-m",
  "dul": "Dulc",
  "sga": "Sang",
  "pet": "Petr",
  "cb a": "Carb-a",
  "cb. a": "Carb-a",
  "lo i": "Lob-i",
  "lo. i": "Lob-i",
  "fer": "Ferr",
  "spi": "Spig",
  "pi x": "Pic-ac",
  "pi. x": "Pic-ac",
  "hyo": "Hyos",
  "mer": "Merc",
  "nit x": "Nit-ac",
  "nit. x": "Nit-ac",
  "cam": "Camph",
  "col": "Coloc",
  "pod": "Podo",
  "val": "Valer",
  "ant t": "Ant-t",
  "ant. t": "Ant-t",
  "ant c": "Ant-c",
  "ant. c": "Ant-c",
  "ip": "Ip",
  "hyd": "Hydr",
  "ran b": "Ran-b",
  "ran. b": "Ran-b",
  "phos": "Phos",
  "plat": "Plat",
  "chel": "Chel",
  "cann s": "Cann-s",
  "cann. s": "Cann-s",
  "cann i": "Cann-i",
  "cann. i": "Cann-i",
  "cact": "Cact",
  "cic": "Cic",
  "cina": "Cina",
  "cocc": "Cocc",
  "coff": "Coff",
  "dig": "Dig",
  "kre": "Kreos",
  "spig": "Spig",
  "stram": "Stram",
  "tar": "Tarent",
  "tarent": "Tarent",
  "sabin": "Sabin",
  "aesc": "Aesc",
  "agn": "Agn",
  "ail": "Ail",
  "all c": "All-c",
  "all. c": "All-c",
  "aloe": "Alo",
  "am m": "Am-m",
  "am. m": "Am-m",
  "anth": "Anth",
  "apoc": "Apoc",
  "arg m": "Arg-m",
  "arg. m": "Arg-m",
  "arn": "Arn",
  "ars": "Ars",
  "ars i": "Ars-i",
  "ars. i": "Ars-i",
  "art": "Art-v",
  "arum t": "Arum-t",
  "arum. t": "Arum-t",
  "asa": "Asaf",
  "asar": "Asar",
  "aur": "Aur",
  "aur m": "Aur-m",
  "aur. m": "Aur-m",
  "bar c": "Bar-c",
  "bar. c": "Bar-c",
  "bar m": "Bar-m",
  "bar. m": "Bar-m",
  "benz ac": "Benz-ac",
  "benz. ac": "Benz-ac",
  "bism": "Bism",
  "bor": "Bor",
  "bov": "Bov",
  "buf": "Bufo",
  "cact g": "Cact",
  "cact. g": "Cact",
  "calad": "Calad",
  "calc c": "Calc-c",
  "calc. c": "Calc-c",
  "calc f": "Calc-f",
  "calc. f": "Calc-f",
  "calc. p": "Calc-p",
  "calc s": "Calc-s",
  "calc. s": "Calc-s",
  "calen": "Calen",
  "cann": "Cann-s",
  "canth": "Canth",
  "caps": "Caps",
  "carb. a": "Carb-a",
  "carb. v": "Carb-v",
  "carbl ac": "Carb-ac",
  "carbl. ac": "Carb-ac",
  "caust": "Caust",
  "cedr": "Cedr",
  "chim": "Chim",
  "chin s": "Chinin-s",
  "chin. s": "Chinin-s",
  "cic v": "Cic",
  "cic. v": "Cic",
  "cimic": "Cimic",
  "cinnab": "Cinnb",
  "cist": "Cist",
  "clem": "Clem",
  "colch": "Colch",
  "cop": "Cop",
  "corn": "Corn",
  "crot h": "Crot-h",
  "crot. h": "Crot-h",
  "crot t": "Croto-t",
  "crot. t": "Croto-t",
  "cupr": "Cupr",
  "cupr m": "Cupr",
  "cupr. m": "Cupr",
  "cycl": "Cycl",
  "dros": "Dros",
  "eup per": "Eup-per",
  "eup. per": "Eup-per",
  "eup pur": "Eup-pur",
  "eup. pur": "Eup-pur",
  "euph": "Euphr",
  "euphr": "Euphr",
  "ferr p": "Ferr-p",
  "ferr. p": "Ferr-p",
  "fl ac": "Fl-ac",
  "fl. ac": "Fl-ac",
  "glon": "Glon",
  "grat": "Grat",
  "guai": "Guaj",
  "hell": "Hell",
  "hepar": "Hep",
  "hydr ac": "Hydr-ac",
  "hydr. ac": "Hydr-ac",
  "iris": "Iris",
  "kalm": "Kalm",
  "lachn": "Lachn",
  "lapis": "Lap-a",
  "laur": "Laur",
  "lept": "Lept",
  "lil t": "Lil-t",
  "lil. t": "Lil-t",
  "lith": "Lith-c",
  "lob": "Lob",
  "lycop": "Lyc",
  "manc": "Manc",
  "mang": "Mang",
  "meph": "Meph",
  "mosch": "Mosch",
  "murex": "Murx",
  "myg": "Mygal",
  "naja": "Naja",
  "oena": "Oenon",
  "oleand": "Oleand",
  "ol jec": "Ol-j",
  "ol. jec": "Ol-j",
  "onos": "Onos",
  "orig": "Orig",
  "ox ac": "Ox-ac",
  "ox. ac": "Ox-ac",
  "phys": "Phys",
  "ptel": "Ptel",
  "rheum": "Rheum",
  "rhod": "Rhod",
  "rhus v": "Rhus-v",
  "rhus. v": "Rhus-v",
  "rumx": "Rumx",
  "ruta": "Ruta",
  "sarr": "Sarr",
  "sel": "Sel",
  "seneg": "Seneg",
  "spong": "Spong",
  "squil": "Squil",
  "stann": "Stann",
  "sympl": "Symph",
  "tab": "Tab",
  "tell": "Tell",
  "ter": "Tereb",
  "tereb": "Tereb",
  "ther": "Ther",
  "tril": "Tril",
  "tub": "Tub",
  "uran n": "Uran-n",
  "uran. n": "Uran-n",
  "ust": "Ust",
  "verb": "Verb",
  "viol o": "Viol-o",
  "viol. o": "Viol-o",
  "viol t": "Viol-t",
  "viol. t": "Viol-t",
  "na c": "Nat-c",
  "na. c": "Nat-c",
  "snc": "Senec",
  "na p": "Nat-p",
  "na. p": "Nat-p",
  "opi": "Op",
  "crt h": "Crot-h",
  "crt. h": "Crot-h",
  "cyc": "Cycl",
  "laoh": "Lach",
  "bis": "Bism",
  "stn": "Stann",
  "k i": "Kali-i",
  "k. i": "Kali-i",
  "su x": "Sulph-ac",
  "su. x": "Sulph-ac",
  "hpz": "Hep",
  "ba c": "Bar-c",
  "ba. c": "Bar-c",
  "sti": "Stict",
  "sbl": "Sabal",
  "symt": "Symph",
  "cans": "Cann-s",
  "hyp": "Hyper",
  "mag c": "Mag-c",
  "mag. c": "Mag-c",
  "pyro": "Pyrog",
  "bhe": "Rhus-t",
  "ber": "Berb",
  "abr": "Abrot",
  "phst": "Phos",
  "spo": "Spong",
  "vi o": "Viol-o",
  "all": "All-c",
};

export class IngestionPipeline {
  private static readonly IMPORTER_VERSION = "2.14.0";
  private static readonly CHECKPOINT_DIR = path.join(process.cwd(), 'scratch');

  /**
   * Generates MD5 checksum of raw source content.
   */
  private static getChecksum(content: string): string {
    return crypto.createHash('md5').update(content).digest('hex');
  }

  /**
   * Loads checkpoint for a given source, if it exists.
   */
  private static getCheckpoint(sourceId: string): number {
    const checkpointFile = path.join(this.CHECKPOINT_DIR, `ingest_checkpoint_${sourceId}.json`);
    if (fs.existsSync(checkpointFile)) {
      try {
        const data = JSON.parse(fs.readFileSync(checkpointFile, 'utf-8'));
        return data.lastProcessedIndex || 0;
      } catch (e) {
        console.warn(`Failed to read checkpoint for ${sourceId}:`, e);
      }
    }
    return 0;
  }

  /**
   * Saves checkpoint for a given source.
   */
  private static saveCheckpoint(sourceId: string, index: number) {
    if (!fs.existsSync(this.CHECKPOINT_DIR)) {
      fs.mkdirSync(this.CHECKPOINT_DIR, { recursive: true });
    }
    const checkpointFile = path.join(this.CHECKPOINT_DIR, `ingest_checkpoint_${sourceId}.json`);
    fs.writeFileSync(checkpointFile, JSON.stringify({
      sourceId,
      lastProcessedIndex: index,
      timestamp: new Date().toISOString()
    }, null, 2));
  }

  /**
   * Clears checkpoint for a given source.
   */
  private static clearCheckpoint(sourceId: string) {
    const checkpointFile = path.join(this.CHECKPOINT_DIR, `ingest_checkpoint_${sourceId}.json`);
    if (fs.existsSync(checkpointFile)) {
      fs.unlinkSync(checkpointFile);
    }
  }

  /**
   * Executes ingestion process for a specified public-domain source.
   */
  static async ingestSource(
    sourceId: string,
    rawRubrics: any[],
    options?: { forceResume?: boolean; maxItems?: number }
  ): Promise<IngestionManifest> {
    console.log(`Starting ingestion pipeline for source: ${sourceId}`);

    const sourceRecord = getSourceRecord(sourceId);
    
    // 1. Verify Rights and Licensing Status
    if (!sourceRecord) {
      throw new Error(`Source "${sourceId}" is not registered in the rights registry.`);
    }

    if (!sourceRecord.ingestionAllowed || sourceRecord.rightsStatus !== "public-domain") {
      console.error(`INGESTION BLOCKED: Source "${sourceId}" has rights status "${sourceRecord.rightsStatus}" and is not allowed for ingestion.`);
      return {
        sourceId,
        sourceChecksum: "",
        extractionTimestamp: new Date().toISOString(),
        importerVersion: this.IMPORTER_VERSION,
        pageMapping: {},
        rejectedLineReport: [`Ingestion blocked due to rights status: ${sourceRecord.rightsStatus}`],
        unresolvedAbbreviationReport: [],
        hierarchyErrorReport: [],
        duplicateReport: [],
        validationSummary: { totalProcessed: 0, totalImported: 0, totalSkipped: rawRubrics.length },
        reviewStatus: "draft",
        importStatus: "blocked"
      };
    }

    const rawString = JSON.stringify(rawRubrics);
    const checksum = this.getChecksum(rawString);

    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { resolveCanonicalRemedyId } = require('../../../lib/normalizationEngine');
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { REMEDIES_METADATA } = require('../../../lib/repertoryData');
    
    const packPath = path.join(process.cwd(), 'src', 'lib', 'remedyDataPack.json');
    const packRaw = fs.readFileSync(packPath, 'utf-8');
    const pack = JSON.parse(packRaw);
    const packAbbrs = new Set<string>();
    const idToAbbr = new Map<string, string>();
    
    pack.forEach((r: any) => {
      if (r.abbr) {
        const abbrClean = r.abbr.trim();
        packAbbrs.add(abbrClean);
        if (r.id) idToAbbr.set(r.id, abbrClean);
      }
    });

    // Checkpoints
    const startIdx = options?.forceResume ? this.getCheckpoint(sourceId) : 0;
    console.log(`Resuming ingestion from index: ${startIdx}`);

    const rejectedLineReport: string[] = [];
    const unresolvedAbbreviationReport: string[] = [];
    const hierarchyErrorReport: string[] = [];
    const duplicateReport: string[] = [];
    const pageMapping: Record<number, number> = {};

    const ingestedRubrics: RepertoryRubric[] = [];
    let totalImported = 0;
    let totalSkipped = 0;

    const limit = options?.maxItems ? Math.min(rawRubrics.length, startIdx + options.maxItems) : rawRubrics.length;

    for (let i = startIdx; i < limit; i++) {
      const raw = rawRubrics[i];

      // Page and Line structural check
      if (!raw.name || !raw.chapter) {
        rejectedLineReport.push(`Row ${i}: Missing name or chapter. Raw data: ${JSON.stringify(raw)}`);
        totalSkipped++;
        continue;
      }

      // Check hierarchy path integrity
      const cleanName = raw.name.trim();
      const parts = cleanName.split(' - ');
      const hierarchyPath = [raw.chapter, ...parts.slice(0, -1)];
      const leafTitle = parts[parts.length - 1];

      if (parts.length === 0) {
        hierarchyErrorReport.push(`Row ${i} (${cleanName}): Empty leaf title`);
      }

      // Resolve remedies and grades
      const remedyEntries: RepertoryRemedyEntry[] = [];
      const relatedRemedies: GradedRemedy[] = [];
      const remediesObject = raw.remedies || {};

      for (const [rawAbbr, rawGrade] of Object.entries(remediesObject)) {
        let cleanAbbr = rawAbbr.trim();
        cleanAbbr = cleanAbbr.replace(/^[\^\[\(\s]+/, '').replace(/[\]\)\s]+$/, '').trim();
        const cleanKey = cleanAbbr.replace(/\./g, '').replace(/\s+/g, ' ').trim();
        const mappedAbbr = sourceId === 'clarke_clinical_1904'
          ? (CLARKE_REMEDY_MAP[cleanAbbr] || 
             CLARKE_REMEDY_MAP[cleanAbbr.toLowerCase()] ||
             CLARKE_REMEDY_MAP[cleanAbbr.replace(/\.$/, '')] || 
             CLARKE_REMEDY_MAP[cleanAbbr.replace(/\.$/, '').toLowerCase()] || 
             CLARKE_REMEDY_MAP[cleanKey] || 
             CLARKE_REMEDY_MAP[cleanKey.toLowerCase()] || 
             cleanAbbr)
          : cleanAbbr;

        let resolvedAbbr = mappedAbbr;
        
        // Character Normalizations
        let normalized = mappedAbbr
          .replace(/Æ/g, 'Ae')
          .replace(/æ/g, 'ae')
          .replace(/Œ/g, 'Oe')
          .replace(/œ/g, 'oe')
          .replace(/[\.\s_-]/g, ' ')
          .trim();

        let isValid = REMEDIES_METADATA[mappedAbbr] || packAbbrs.has(mappedAbbr);
        
        if (!isValid) {
          // Try normalizer
          const canonicalId = resolveCanonicalRemedyId(normalized);
          if (idToAbbr.has(canonicalId)) {
            resolvedAbbr = idToAbbr.get(canonicalId)!;
            isValid = true;
          } else {
            // Case insensitive fallback
            const lower = normalized.toLowerCase();
            let found = false;
            for (const [id, abbr] of idToAbbr.entries()) {
              if (id.replace('rem_', '').replace(/_/g, '') === lower.replace(/ /g, '')) {
                resolvedAbbr = abbr;
                isValid = true;
                found = true;
                break;
              }
            }
            if (!found) {
              unresolvedAbbreviationReport.push(`Rubric "${cleanName}": remedy abbreviation "${cleanAbbr}" could not be resolved.`);
            }
          }
        }

        const isClarke = sourceId === 'clarke_clinical_1904';
        const parsedGrade = typeof rawGrade === 'number' ? rawGrade : Number(rawGrade);
        
        let normalizedGrade: number | undefined = undefined;
        let gradeInfo: any = undefined;

        if (isClarke) {
          normalizedGrade = undefined;
          gradeInfo = {
            originalRepresentation: typeof rawGrade === 'string' ? rawGrade : String(rawGrade),
            normalizedGrade: undefined,
            status: isValid ? "not-recoverable" : "unresolved",
            confidence: 0.0
          };
        } else {
          normalizedGrade = Number.isNaN(parsedGrade) ? 1 : Math.min(Math.max(Math.round(parsedGrade), 1), 4);
        }

        remedyEntries.push({
          remedyId: resolvedAbbr,
          sourceAbbreviation: cleanAbbr,
          canonicalAbbreviation: resolvedAbbr,
          sourceGrade: rawGrade as string | number,
          normalizedGrade,
          gradeSystemId: sourceId === "kent_1908" ? "kent_3_grade" : "boericke_3_grade",
          sourceId,
          sourcePage: raw.page || undefined,
          gradeInfo
        });

        if (isValid) {
          // For backwards compatibility:
          const meta = REMEDIES_METADATA[resolvedAbbr] || { fullName: resolvedAbbr, source: "Plant" };
          relatedRemedies.push({
            remedyId: resolvedAbbr,
            remedyName: meta.fullName,
            grade: normalizedGrade as 1 | 2 | 3 | 4,
            confidence: 1.0,
            keynoteReason: `Graded in ${sourceRecord.shortTitle}`,
            sourceReference: sourceRecord.canonicalTitle,
            clinicalExperienceWeight: 0.8
          });
        }
      }

      // Check duplicates
      const rubricId = raw.id || `${sourceId}_rubric_${i}`;
      const duplicateKey = `${raw.chapter.toLowerCase()}:${cleanName.toLowerCase()}`;
      
      const rubric: RepertoryRubric = {
        rubricId,
        id: rubricId,
        title: leafTitle,
        displayText: leafTitle,
        plainLanguageMeaning: `Symptom from ${sourceRecord.shortTitle}: ${cleanName}`,
        classicalWording: cleanName,
        originalText: cleanName,
        normalizedText: cleanName.toLowerCase(),
        category: raw.chapter.toLowerCase().includes('mind') ? "Mental & Emotional" : "Physical Generals",
        organSystem: raw.chapter,
        chapterId: raw.chapter,
        subCategory: parts.length > 1 ? parts[0] : undefined,
        synonyms: [leafTitle.toLowerCase()],
        patientExpressions: [leafTitle.toLowerCase()],
        clinicalKeywords: leafTitle.toLowerCase().split(/\s+/).filter(Boolean),
        relatedSymptoms: [],
        relatedDiseases: [],
        miasmaticWeight: { Psora: 0.5, Sycosis: 0.2, Syphilis: 0.1, Tubercular: 0.2, Cancerinic: 0.2 },
        intensityScale: 5,
        polarity: 'positive',
        modalities: [],
        aggravations: [],
        ameliorations: [],
        source: sourceRecord.shortTitle,
        sourceId,
        sourceRubricId: raw.id || undefined,
        confidence: 0.9,
        author: sourceRecord.author,
        reviewer: "CIE Editorial Reviewer",
        lastUpdated: new Date().toISOString(),
        relatedRemedies,
        remedyEntries,
        hierarchyPath,
        language: "en",
        evidenceStatus: "source-verified",
        editorialStatus: "draft",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        sourceCitation: `${sourceRecord.author}, ${sourceRecord.canonicalTitle} (${sourceRecord.editionPublicationYear})`
      };

      // Save to memory array
      ingestedRubrics.push(rubric);
      totalImported++;

      // Track pages
      const pageNum = raw.page || 0;
      pageMapping[pageNum] = (pageMapping[pageNum] || 0) + 1;

      // Periodically update checkpoint
      if (i % 100 === 0) {
        this.saveCheckpoint(sourceId, i);
      }
    }

    // Persist ingested rubrics to public/data directory
    const outputFileName = `ingested_${sourceId}.json`;
    const outputPath = path.join(process.cwd(), 'public', 'data', outputFileName);
    fs.writeFileSync(outputPath, JSON.stringify(ingestedRubrics, null, 2));
    console.log(`Saved ${ingestedRubrics.length} ingested rubrics to ${outputPath}`);

    // If writing to database, load them into memory repository
    for (const r of ingestedRubrics) {
      await repertoryRepository.saveRubric(r);
    }

    this.clearCheckpoint(sourceId);

    return {
      sourceId,
      sourceChecksum: checksum,
      extractionTimestamp: new Date().toISOString(),
      importerVersion: this.IMPORTER_VERSION,
      pageMapping,
      rejectedLineReport,
      unresolvedAbbreviationReport,
      hierarchyErrorReport,
      duplicateReport,
      validationSummary: {
        totalProcessed: limit - startIdx,
        totalImported,
        totalSkipped
      },
      reviewStatus: "draft",
      importStatus: "completed"
    };
  }
}
