import { KnowledgeEntity } from "../../types";

export const AthletesFootTineaPedisDisease: KnowledgeEntity = {
  id: "D0078",
  slug: "athletes-foot-tinea-pedis",
  entityType: "disease",
  editorialStatus: "published",
  reviewStatus: "owner-authorization-required",
  versionInfo: {
    version: "1.1.0",
    created: "2026-09-21T00:00:00Z",
    updated: "2026-09-24T00:00:00Z",
    reviewed: "2026-09-21T00:00:00Z",
  },
  title: {
    en: "Athlete’s Foot",
    hi: "एथलीट्स फुट: पैर की उंगलियों के बीच खुजली और छिलती त्वचा",
    gu: "એથ્લીટ્સ ફૂટ: પગની આંગળીઓ વચ્ચે ખંજવાળ અને છાલ ઉતરવી",
    mr: "अॅथलीट्स फूट: पायाच्या बोटांमध्ये खाज आणि त्वचा सोलणे",
    es: "Pie de Atleta: Piel con Picor y Descamación entre los Dedos",
    ar: "قدم الرياضي: حكة وتقشر بين أصابع القدم",
  },
  summary: {
    en: "Athlete’s foot is a common fungal infection of the feet. It often causes itching, peeling, or cracking between the toes and is more likely when feet stay warm and damp.",
    hi: "एथलीट्स फुट पैरों का एक आम फंगल संक्रमण है। इसमें उंगलियों के बीच खुजली, त्वचा छिलना या फटना हो सकता है।",
    gu: "એથ્લીટ્સ ફૂટ પગનો સામાન્ય ફંગલ ચેપ છે. તેમાં આંગળીઓ વચ્ચે ખંજવાળ, છાલ ઉતરવી અથવા ત્વચા ફાટવી થઈ શકે છે.",
    mr: "अॅथलीट्स फूट हा पायांचा सामान्य बुरशीजन्य संसर्ग आहे. बोटांमध्ये खाज, त्वचा सोलणे किंवा भेगा पडणे होऊ शकते.",
    es: "El pie de atleta es una infección fúngica común de los pies. Puede causar picor, descamación o grietas entre los dedos.",
    ar: "قدم الرياضي عدوى فطرية شائعة في القدمين قد تسبب حكة أو تقشرًا أو تشققًا بين الأصابع.",
  },
  content: {
    overview: "Athlete’s foot, also called tinea pedis, is a fungal infection of foot skin. It often begins between the toes, particularly the smaller toes, and can also affect the sole or heel. It can be confused with eczema, psoriasis, bacterial infection, or simple dry skin, so an uncertain or persistent rash deserves assessment.",
    definition: "A superficial fungal infection of foot skin caused by dermatophytes; it is one form of ringworm and is not caused by a worm.",
    causes: [
      "Dermatophyte fungi that grow well in warm, dark, moist environments",
      "Contact with contaminated floors, towels, socks, shoes, or sports equipment, or contact with an infected person",
      "Feet remaining damp after sweating, bathing, or wearing tight non-breathable footwear",
    ],
    riskFactors: [
      "Sweaty feet, tight shoes, wet socks, or not drying carefully between the toes",
      "Walking barefoot in shared changing rooms, pools, public showers, or locker rooms",
      "Sharing footwear, socks, towels, or sports gear; diabetes or reduced immune defenses can make foot problems more important to assess",
    ],
    symptoms: [
      "Itchy, peeling, scaly, or cracked skin between the toes; this is often most noticeable between the smaller toes",
      "Redness, swelling, or a burning sensation; on darker skin, colour changes may look purple, brown, grey, or black",
      "Scaling on the sole or heel, or small blisters in more severe cases",
    ],
    diagnosis: "A clinician, pharmacist, dermatologist, or podiatrist may recognise athlete’s foot from the pattern. A skin scraping or fungal testing can help when the diagnosis is unclear, infection is widespread, nails are involved, or a first treatment has not worked.",
    differentialDiagnosis: "Eczema, psoriasis, contact dermatitis, bacterial infection, pitted keratolysis, and other causes of peeling or itchy feet can look similar. Do not assume that every itchy foot rash is fungal.",
    labTests: ["Skin scraping with microscopy or fungal testing may be used for an uncertain, recurrent, or treatment-resistant rash."],
    imaging: "Imaging is not used for uncomplicated athlete’s foot.",
    redFlags: [
      "Rapidly spreading redness, warmth, swelling, pain, pus, fever, or open sores",
      "Diabetes, poor circulation, numbness, or reduced immune defenses with any new foot rash or skin breakdown",
      "Nail involvement, recurrent infection, extensive blisters, or no improvement after appropriate pharmacist or clinician advice",
    ],
    conventionalManagement: "A pharmacist or clinician can advise on an appropriate antifungal treatment and how long to use it. The suitable treatment depends on the pattern, severity, other health conditions, and whether nails are involved. Do not use a steroid cream alone on a rash that might be fungal, because it can make ringworm worse.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for athlete’s foot. It should not replace antifungal care or delay assessment of a painful, spreading, persistent, or high-risk foot problem.",
    lifestyleAdvice: "Wash and dry feet thoroughly, especially between the toes; change socks daily and after sweating; alternate and air shoes; use breathable footwear; wear sandals in shared showers and changing rooms; and do not share towels, socks, or shoes. Clean sports gear and seek advice before returning to close-contact sport if a rash is suspected.",
    references: ["CIT-0083", "CIT-0082", "CIT-0023"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" },
  reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" },
  evidenceLevel: "Consensus-Guidance",
  tags: ["Athlete’s Foot", "Tinea Pedis", "Foot Fungus", "Itchy Toes", "Dermatology"],
  canonicalUrl: "https://homeo.healthcare/knowledge/diseases/athletes-foot-tinea-pedis",
  readingTimeMinutes: 4,
  audience: "patient",
  license: "CC BY-NC-ND 4.0",
  changeLog: ["1.0.0: Added patient-first athlete’s foot guide with practical prevention and treatment boundaries.", "1.1.0: Simplified the title and added focused condition and symptom connections."],
  quickFacts: { "Cause": "A fungal infection of foot skin", "Often starts": "Between the toes", "Helpful habit": "Keep feet and toe spaces clean and dry", "When to seek advice": "If it is painful, spreading, recurrent, involves nails, or you have diabetes" },
  aiReadiness: {
    retrievalSummary: "Athlete’s foot, or tinea pedis, is a common fungal infection of the foot that often causes itchy, peeling or cracked skin between the toes and needs appropriate antifungal assessment or treatment.",
    clinicalSummary: "Consider fungal testing when presentation is unclear, infection is recurrent or extensive, nails are involved, or first treatment fails; assess promptly for bacterial infection and foot-risk conditions.",
    patientSummary: "Athlete’s foot is a fungal foot infection. Keep feet dry, change socks, avoid sharing footwear, and ask a pharmacist or clinician about the right antifungal treatment.",
    studentSummary: "Tinea pedis commonly affects interdigital skin but can involve the sole or heel; distinguish dermatophyte infection from inflammatory dermatoses and assess coexistent onychomycosis.",
    keywords: ["athlete’s foot", "athletes foot", "tinea pedis", "foot fungus", "itchy toes", "peeling between toes"],
    semanticKeywords: ["dermatophyte", "interdigital fungal infection", "fungal foot rash"],
    icd: "B35.3",
    bodySystem: "Dermatology & Integumentary",
    urgency: "monitor",
  },
};
