import { KnowledgeEntity } from "../../types";

export const BadBreathDisease: KnowledgeEntity = {
  id: "D0096", slug: "bad-breath", entityType: "disease", editorialStatus: "published", reviewStatus: "owner-authorization-required",
  versionInfo: { version: "1.0.0", created: "2026-09-22T00:00:00Z", updated: "2026-09-22T00:00:00Z", reviewed: "2026-09-22T00:00:00Z" },
  title: { en: "Bad Breath (Halitosis): Common Causes and What Helps", hi: "मुंह की बदबू: आम कारण और क्या मदद करता है", gu: "મોઢાની દુર્ગંધ: સામાન્ય કારણો અને શું મદદ કરે", mr: "तोंडाची दुर्गंधी: सामान्य कारणे आणि काय मदत करते", es: "Mal Aliento (Halitosis): Causas Comunes y Qué Ayuda", ar: "رائحة الفم الكريهة: الأسباب الشائعة وما يساعد" },
  summary: { en: "Bad breath, also called halitosis, is common and often starts in the mouth—from plaque, the tongue surface, food, smoking, dry mouth, tooth decay, or gum disease. A simple oral-care routine often helps. Persistent bad breath, especially with bleeding or swollen gums, tooth pain, loose teeth, or a dry mouth, deserves a dental check.", hi: "मुंह की बदबू आम है और अक्सर प्लाक, जीभ, सूखे मुंह, दांत या मसूड़ों की समस्या से होती है।", gu: "મોઢાની દુર્ગંધ સામાન્ય છે અને ઘણીવાર પ્લાક, જીભ, સૂકા મોં, દાંત અથવા પેઢાની સમસ્યાથી થાય છે.", mr: "तोंडाची दुर्गंधी सामान्य असून ती प्लाक, जीभ, कोरडे तोंड, दात किंवा हिरड्यांच्या समस्येमुळे होऊ शकते.", es: "El mal aliento es común y suele originarse en la boca, por placa, la lengua, boca seca o problemas dentales.", ar: "رائحة الفم الكريهة شائعة وغالبًا ما تبدأ في الفم بسبب اللويحة أو اللسان أو جفاف الفم أو مشكلات الأسنان." },
  content: {
    overview: "Bad breath is an ongoing unpleasant smell from the mouth. It is common and is not a personal failing. It often improves when the teeth, gums, tongue, and spaces between teeth are cleaned consistently. Strong-smelling foods, smoking, alcohol, fasting, dry mouth, gum disease, tooth decay, infection, tonsillitis, and reflux can all contribute. Persistent bad breath is worth discussing with a dentist because the cause is often visible and treatable in the mouth.",
    definition: "Halitosis is the clinical term for bad breath that is noticeable or persistent. Temporary odour after certain foods is different from a recurring problem linked to oral hygiene, dry mouth, dental disease, tobacco, or a medical condition.",
    causes: ["Plaque, food debris, and bacteria on the teeth, gums, tongue, or between teeth", "Gum disease, tooth decay, dental infection, or poorly cleaned dentures", "Dry mouth from dehydration, mouth breathing, medicines, tobacco, alcohol, or some health conditions", "Strong-smelling foods and drinks, smoking, fasting, or crash dieting", "Tonsillitis, reflux, sinus or throat conditions, or less commonly another medical condition"],
    riskFactors: ["Infrequent brushing, tongue cleaning, cleaning between teeth, or dental check-ups", "Bleeding or swollen gums, loose teeth, untreated cavities, or dentures that are not cleaned nightly", "Tobacco use, frequent alcohol, or frequent sugary foods and drinks", "Persistent dry mouth, mouth breathing, or medicines that reduce saliva", "Fasting, restrictive dieting, or a chronic nose, throat, digestive, or metabolic condition"],
    symptoms: ["A persistent unpleasant smell or taste in the mouth", "A coated tongue, dry mouth, or food trapped between teeth", "Bleeding, sore, red, swollen, or receding gums", "Tooth sensitivity, toothache, a loose tooth, or problems with dentures", "A dry throat, cracked lips, difficulty swallowing dry foods, or frequent thirst suggesting dry mouth"],
    diagnosis: "A dentist can check the teeth, gums, tongue, restorations, dentures, and saliva flow, and ask about hygiene routines, diet, tobacco, medicines, dry mouth, and general health. They may look for plaque, gum disease, decay, infection, or a poorly fitting appliance. If the mouth appears healthy but symptoms continue, they may recommend review by a doctor or another clinician.",
    differentialDiagnosis: "Temporary food-related odour, gum disease, tooth decay or infection, dry mouth, tonsillitis, postnasal drip, reflux, tobacco use, and medicine effects can overlap. Persistent mouth pain, bleeding, loose teeth, ulcers, lumps, unexplained weight loss, or severe dry mouth should not be assumed to be simple bad breath.",
    labTests: ["No test is usually needed when the dental cause is clear", "Dental examination and X-rays may be used when decay, infection, or gum disease is suspected", "A doctor may consider tests for dry mouth, infection, reflux, diabetes, or another condition if dental assessment does not explain persistent symptoms"],
    imaging: "Imaging is not needed for ordinary bad breath. Dental X-rays may help a dentist assess suspected decay, infection, or gum and bone disease.",
    redFlags: ["Bad breath that does not improve after a few weeks of careful oral care", "Painful, bleeding, red, or swollen gums; toothache; a loose adult tooth; or trouble with dentures", "A persistent mouth ulcer, red or white patch, lump, unexplained bleeding, or unexplained weight loss", "Significant dry mouth, trouble swallowing, recurrent mouth infections, or a sudden change in breath odour with feeling unwell", "Facial swelling, fever, rapidly worsening dental pain, or trouble breathing or swallowing—seek urgent dental or emergency care"],
    conventionalManagement: "The right treatment depends on the cause. A dentist can remove plaque and tartar, treat gum disease, decay, infection, or a dental appliance problem, and advise on cleaning technique. If dry mouth or a non-dental cause is suspected, a doctor or dentist can review medicines and health conditions. Mouthwash, mints, or gum may temporarily mask odour but do not replace treating the cause.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for persistent bad breath or its dental causes. It must not replace dental assessment for gum disease, tooth decay, infection, or warning signs.",
    lifestyleAdvice: "Gently brush teeth and gums twice daily with fluoride toothpaste, clean the tongue once daily, and clean between teeth daily with floss or an interdental brush suitable for you. Keep dentures clean and remove them at night if advised. Drink water regularly, avoid tobacco, limit alcohol and frequent sugary snacks, and schedule regular dental checks. Sugar-free gum or mints can be a short-term aid after strongly scented foods, but recurring bad breath needs the underlying cause addressed.",
    references: ["CIT-0117", "CIT-0118"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" }, reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" }, evidenceLevel: "Consensus-Guidance", tags: ["Bad Breath", "Halitosis", "Oral Hygiene", "Dry Mouth", "Gum Disease"], canonicalUrl: "https://homeo.healthcare/knowledge/diseases/bad-breath", readingTimeMinutes: 5, audience: "patient", license: "CC BY-NC-ND 4.0", changeLog: ["1.0.0: Added non-stigmatizing patient guide to bad breath, common oral causes, and review triggers."], quickFacts: { "Often starts in": "The mouth, tongue, teeth, or gums", "Common contributors": "Plaque, dry mouth, food, tobacco, decay, or gum disease", "First step": "Clean teeth, tongue, and between teeth consistently", "Get a check": "If it persists or comes with gum or tooth symptoms" },
  aiReadiness: { retrievalSummary: "Bad breath, or halitosis, commonly comes from the mouth and often improves with consistent cleaning of teeth, tongue, gums, and between teeth. Persistent symptoms or gum, tooth, dry-mouth, or mouth-change symptoms need dental review.", clinicalSummary: "Assess duration, hygiene, tongue coating, gum bleeding, caries, dental appliances, tobacco, diet, dry mouth, medicines, upper-airway and reflux symptoms, systemic illness, and oral-cancer warning signs.", patientSummary: "Bad breath is common and not something to feel ashamed about. Improve daily oral care and arrange a dentist check if it lasts a few weeks or comes with bleeding gums, tooth pain, loose teeth, a dry mouth, or mouth changes.", studentSummary: "Halitosis is predominantly oral in origin, often involving tongue coating, plaque, periodontal disease, caries, or xerostomia. Evaluate oral factors first, then consider ENT, gastrointestinal, metabolic, medication, and systemic causes when appropriate.", keywords: ["bad breath", "halitosis", "smelly breath", "bad taste in mouth", "persistent bad breath"], semanticKeywords: ["tongue coating", "gum disease bad breath", "dry mouth breath", "oral hygiene routine", "halitosis dentist"], icd: "R19.6", bodySystem: "Oral Health", urgency: "routine" },
};
