import { KnowledgeEntity } from "../../types";

export const ChickenpoxVaricellaDisease: KnowledgeEntity = {
  id: "D0086", slug: "chickenpox-varicella", entityType: "disease", editorialStatus: "published", reviewStatus: "owner-authorization-required",
  versionInfo: { version: "1.0.0", created: "2026-09-22T00:00:00Z", updated: "2026-09-22T00:00:00Z", reviewed: "2026-09-22T00:00:00Z" },
  title: { en: "Chickenpox", hi: "चिकनपॉक्स: खुजली वाले फफोले जो पपड़ी बन जाते हैं", gu: "ચિકનપૉક્સ: ખંજવાળવાળા ફોલ્લા જે પોપડી બને છે", mr: "कांजिण्या: खाज येणारे फोड जे खपली बनतात", es: "Varicela: Ampollas con Picor que Forman Costras", ar: "جدري الماء: بثور حاكة تتحول إلى قشور" },
  summary: { en: "Chickenpox is a highly contagious viral illness that causes an itchy rash of spots and blisters, often with fever or tiredness. It is usually mild in healthy children but needs prompt advice in babies, adults, pregnancy, and reduced immunity.", hi: "चिकनपॉक्स एक बहुत संक्रामक वायरल बीमारी है जिसमें खुजली वाले दाने और फफोले हो सकते हैं।", gu: "ચિકનપૉક્સ ખૂબ ચેપી વાયરલ બીમારી છે જેમાં ખંજવાળવાળા દાણા અને ફોલ્લા થઈ શકે છે.", mr: "कांजिण्या हा अतिसंसर्गजन्य विषाणूजन्य आजार आहे ज्यात खाज येणारे पुरळ आणि फोड येऊ शकतात.", es: "La varicela es una enfermedad viral muy contagiosa que causa una erupción con manchas y ampollas que pican.", ar: "جدري الماء مرض فيروسي شديد العدوى يسبب طفحًا من البقع والبثور المسببة للحكة." },
  content: {
    overview: "Chickenpox, also called varicella, is caused by varicella-zoster virus. It can begin with fever, tiredness, appetite change, or headache, followed by an itchy rash that changes from spots to clear blisters and then scabs. New spots may appear over several days, so different stages can be present together. The rash often starts on the chest, back, or face before spreading.",
    definition: "A highly contagious viral illness. It can spread from 1 to 2 days before rash onset until all lesions have crusted, so avoid deliberate exposure and protect people at higher risk of severe illness.",
    causes: ["Varicella-zoster virus spread through close contact, respiratory droplets, and fluid from blisters", "Exposure to a person with chickenpox or, less commonly, shingles", "Lack of prior immunity; vaccinated people can still occasionally develop a usually milder breakthrough illness"],
    riskFactors: ["No prior chickenpox or vaccination", "Household, school, or childcare exposure", "Infancy, adolescence, adulthood, pregnancy, chronic lung or skin disease, or reduced immune defenses increase the importance of early clinical advice"],
    symptoms: ["Itchy spots that become fluid-filled blisters and then crust; the pattern may be subtler on darker skin, so notice texture, new raised spots, or blisters", "Fever, tiredness, headache, poor appetite, or feeling unwell before or with the rash", "Mouth, eyelid, or genital sores in some people; scratching can lead to a bacterial skin infection"],
    diagnosis: "A clinician can often recognise the typical rash and timeline. Testing may be useful if the rash is atypical, mild after vaccination, or the diagnosis affects a vulnerable person or outbreak response. Measles, hand-foot-and-mouth disease, impetigo, insect bites, eczema, scabies, and herpes can resemble parts of the rash.",
    differentialDiagnosis: "Measles, hand-foot-and-mouth disease, impetigo, herpes simplex, insect bites, scabies, eczema, medicine reactions, and other viral rashes may need to be considered.",
    labTests: ["Testing is not always needed; a clinician may take a blister or scab sample for varicella-zoster testing in atypical or high-risk situations."],
    imaging: "Imaging is not used for typical chickenpox.",
    redFlags: ["Breathing difficulty, severe cough, confusion, difficulty waking, stiff neck, difficulty walking, repeated vomiting, severe abdominal pain, or a rash with bleeding or bruising", "Fever lasting more than four days, or skin that becomes very red, hot, painful, swollen, or leaks pus", "A baby under one year, age over 12, pregnancy, reduced immune defenses, or exposure during pregnancy without known immunity—contact a clinician promptly"],
    conventionalManagement: "A clinician or pharmacist can advise on age-appropriate comfort care and whether early antiviral treatment matters for higher-risk people. Offer fluids, use cool baths or soothing measures if suitable, keep nails short, and reduce scratching. Do not give aspirin to children with chickenpox. Ask before using ibuprofen or topical products, especially in children. Vaccination is the best way to prevent severe chickenpox; ask a local clinician about eligibility and schedules.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for chickenpox. It should not replace vaccination, hydration, treatment for high-risk people, or urgent care for serious symptoms or a possible skin infection.",
    lifestyleAdvice: "Stay home and avoid close contact until all lesions have crusted, following local school, nursery, and public-health advice. Avoid contact with pregnant people, newborns, and people with weakened immune systems unless a clinician confirms they are protected. Wash hands, keep blisters clean, do not share towels or cups, and tell close contacts who may be at higher risk so they can seek timely advice.",
    references: ["CIT-0097", "CIT-0098"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" }, reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" }, evidenceLevel: "Consensus-Guidance", tags: ["Chickenpox", "Varicella", "Itchy Blisters", "Child Rash", "Viral Illness"], canonicalUrl: "https://homeo.healthcare/knowledge/diseases/chickenpox-varicella", readingTimeMinutes: 5, audience: "patient", license: "CC BY-NC-ND 4.0",
  changeLog: ["1.0.0: Added patient-first chickenpox guide with rash-stage clarity, comfort care, and urgent-risk boundaries."], quickFacts: { "Cause": "Varicella-zoster virus", "Typical pattern": "Spots, blisters, and scabs can appear together", "Contagious period": "From before rash onset until all lesions crust", "Important to know": "Babies, adults, pregnancy, and reduced immunity need early clinical advice" },
  aiReadiness: { retrievalSummary: "Chickenpox is a highly contagious varicella-zoster infection causing an itchy rash that progresses from spots to blisters and scabs. It is usually mild in healthy children but can be serious in babies, adults, pregnancy, and immunocompromise.", clinicalSummary: "Assess rash stage, immunity, age, pregnancy, immunocompromise, respiratory or neurologic symptoms, skin superinfection, and dehydration. Consider early antiviral guidance in high-risk people.", patientSummary: "Chickenpox commonly causes fever and itchy blisters. Help with fluids and avoiding scratching, keep away from vulnerable contacts, and seek early advice for babies, adults, pregnancy, immune problems, or severe symptoms.", studentSummary: "Primary VZV infection is a contagious vesicular eruption with lesions at different stages simultaneously. Bacterial skin infection is a common complication in children and pneumonia is an important adult complication.", keywords: ["chickenpox", "chicken pox", "varicella", "itchy blisters", "chickenpox rash", "spots turning to scabs"], semanticKeywords: ["varicella-zoster virus", "vesicular rash", "breakthrough varicella", "varicella complications"], icd: "B01.9", bodySystem: "Infectious Disease & Dermatology", urgency: "monitor" },
};
