import { KnowledgeEntity } from "../../types";

export const ChikungunyaDisease: KnowledgeEntity = {
  id: "D0090", slug: "chikungunya", entityType: "disease", editorialStatus: "published", reviewStatus: "owner-authorization-required",
  versionInfo: { version: "1.1.0", created: "2026-09-22T00:00:00Z", updated: "2026-09-24T00:00:00Z", reviewed: "2026-09-22T00:00:00Z" },
  title: { en: "Chikungunya", hi: "चिकनगुनिया: बुखार, तेज जोड़ों का दर्द, जांच और रिकवरी", gu: "ચિકનગુનિયા: તાવ, તીવ્ર સાંધાનો દુખાવો, તપાસ અને સાજા થવું", mr: "चिकनगुनिया: ताप, तीव्र सांधेदुखी, चाचणी आणि बरे होणे", es: "Chikungunya: Fiebre, Dolor Articular Intenso, Pruebas y Recuperación", ar: "الشيكونغونيا: حمى وألم شديد في المفاصل وفحوص وتعافٍ" },
  summary: { en: "Chikungunya is a viral illness spread by infected mosquitoes. Sudden fever with prominent joint pain, swelling, headache, fatigue, or rash can overlap with dengue and other infections, so clinical testing matters. Joint pain can outlast the fever.", hi: "चिकनगुनिया संक्रमित मच्छरों से फैलने वाला वायरल रोग है। अचानक बुखार के साथ तेज जोड़ों का दर्द, सूजन, सिरदर्द, थकान या रैश डेंगू और अन्य संक्रमणों से मिल सकता है; जांच जरूरी है। जोड़ों का दर्द बुखार के बाद भी रह सकता है।", gu: "ચિકનગુનિયા સંક્રમિત મચ્છરોથી ફેલાતો વાયરલ રોગ છે. અચાનક તાવ સાથે તીવ્ર સાંધાનો દુખાવો, સોજો, માથાનો દુખાવો, થાક અથવા ચકામો ડેન્ગ્યુ અને અન્ય ચેપ જેવો હોઈ શકે છે; તપાસ મહત્વની છે. સાંધાનો દુખાવો તાવ પછી પણ રહી શકે છે.", mr: "चिकनगुनिया हा संक्रमित डासांमुळे पसरणारा विषाणूजन्य आजार आहे. अचानक तापासोबत तीव्र सांधेदुखी, सूज, डोकेदुखी, थकवा किंवा पुरळ डेंग्यूसारखा असू शकतो; तपासणी महत्त्वाची आहे. सांधेदुखी तापानंतरही टिकू शकते.", es: "El chikungunya es una infección viral transmitida por mosquitos infectados. La fiebre súbita con dolor articular importante, hinchazón, dolor de cabeza, cansancio o sarpullido puede confundirse con dengue y otras infecciones; las pruebas clínicas importan. El dolor articular puede durar más que la fiebre.", ar: "الشيكونغونيا عدوى فيروسية ينقلها البعوض المصاب. قد تتشابه الحمى المفاجئة مع ألم مفاصل بارز أو تورم أو صداع أو إرهاق أو طفح مع الضنك وغيره، لذلك يهم الفحص السريري. قد يستمر ألم المفاصل بعد الحمى." },
  content: {
    overview: "Chikungunya is a mosquito-borne viral illness that often begins suddenly with fever and marked joint pain. Headache, muscle pain, joint swelling, nausea, fatigue, and rash can also occur. The symptoms overlap with dengue, Zika, and other fever illnesses, so it is not safe to distinguish them at home from symptoms alone.",
    definition: "An infection caused by chikungunya virus and transmitted mainly by infected Aedes mosquitoes. The illness is not spread by casual contact, but mosquitoes can pick up virus from a person during the first week of illness and pass it to others.",
    causes: ["A bite from an infected Aedes mosquito", "Living in or recently travelling to an area with chikungunya transmission", "Exposure around places where mosquitoes breed, including containers with collected water"],
    riskFactors: ["Older age, particularly 65 years or above", "Newborns and infants, pregnancy, or major long-term health conditions such as diabetes, high blood pressure, or heart disease", "Being unable to drink enough, walk safely, or arrange clinical follow-up during an acute fever"],
    symptoms: ["Abrupt fever with severe or disabling joint pain, sometimes with joint swelling", "Headache, muscle pain, rash, nausea, fatigue, or weakness", "Symptoms often improve within a week, but joint pain and tiredness can persist for weeks or months in some people", "Symptoms can resemble dengue or Zika; prominent joint pain may suggest chikungunya but does not confirm it"],
    diagnosis: "A clinician considers symptoms, residence or travel, and local outbreaks, then orders blood tests when appropriate. During the first week, molecular testing can detect virus in blood; antibody tests are generally more useful later. Testing may include dengue and other similar mosquito-borne viruses because the illnesses overlap.",
    differentialDiagnosis: "Dengue, Zika, malaria, enteric fever, influenza, COVID-19, rheumatoid or other inflammatory arthritis, and other viral infections can overlap. Fever with aches must not be self-labelled as chikungunya.",
    labTests: ["Chikungunya molecular testing such as RT-PCR during the first week of illness, where available", "Chikungunya antibody testing after the first week when clinically appropriate", "Tests for dengue and other causes of acute fever as directed by a clinician"], imaging: "Imaging is not routinely needed during uncomplicated chikungunya. A clinician may arrange joint imaging only if prolonged pain, injury, or another joint condition needs assessment.",
    redFlags: ["A newborn, older adult, pregnant person, or someone with significant heart disease, diabetes, high blood pressure, kidney disease, or immune suppression who develops fever and joint pain", "Confusion, fainting, breathing difficulty, severe weakness, signs of dehydration, inability to drink, or symptoms that are worsening rather than settling", "Bleeding, severe belly pain, repeated vomiting, or marked drowsiness—these may indicate dengue or another urgent illness", "Persistent, severe, or progressively swollen painful joints, especially if daily movement becomes difficult"],
    conventionalManagement: "There is no specific antiviral treatment. Medical care focuses on rest, fluids, and safe fever and pain relief. Paracetamol/acetaminophen may be recommended if appropriate for the person. Avoid aspirin, ibuprofen, and other anti-inflammatory medicines until dengue has been ruled out by a clinician because they can increase bleeding risk in dengue. If pain persists after the acute illness, a clinician can assess recovery and discuss a gradual, tailored mobility plan.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for chikungunya. It must not replace diagnostic testing, safe fever and pain management, hydration, mosquito-bite prevention, or urgent assessment for concerning symptoms.",
    lifestyleAdvice: "Rest during the acute fever, drink fluids regularly if you can, and seek a personalised plan before restarting strenuous activity. Use mosquito screens or nets, covering clothing when practical, and locally approved repellents as directed—especially during the first week of illness so mosquitoes do not carry virus onward. Around the home, cover water-storage containers and empty or scrub containers that collect water. For lingering joint symptoms, choose gentle movement only after clinical advice; do not push through severe pain.", references: ["CIT-0105", "CIT-0106"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" }, reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" }, evidenceLevel: "Consensus-Guidance", tags: ["Chikungunya", "Fever and Joint Pain", "Mosquito-Borne Disease", "Joint Swelling", "Viral Fever"], canonicalUrl: "https://homeo.healthcare/knowledge/diseases/chikungunya", readingTimeMinutes: 6, audience: "patient", license: "CC BY-NC-ND 4.0", changeLog: ["1.1.0: Simplified the title and added focused fever and joint-pain connections.", "1.0.0: Added patient-first chikungunya guide with dengue-safe medication boundaries and prolonged joint-pain advice."], quickFacts: { "Cause": "Chikungunya virus spread by infected mosquitoes", "Typical pattern": "Sudden fever with prominent joint pain", "Testing": "Blood tests vary by day of illness", "Important safety step": "Avoid anti-inflammatory pain medicines until dengue is ruled out" },
  aiReadiness: { retrievalSummary: "Chikungunya is an Aedes mosquito-borne viral illness with abrupt fever and prominent joint pain; joint symptoms can persist after the fever. It overlaps clinically with dengue and other febrile illnesses.", clinicalSummary: "Assess local exposure/travel, age, pregnancy, comorbidities, hydration, ability to return, bleeding or abdominal symptoms suggestive of dengue, and functional effect of joint pain. Use day-of-illness-appropriate molecular or serologic testing and avoid NSAIDs until dengue is excluded.", patientSummary: "Fever with severe joint pain may be chikungunya but can look like dengue. Seek medical advice for testing, rest and hydrate, and do not take aspirin or ibuprofen until dengue is ruled out. Get prompt help for red flags or high-risk people.", studentSummary: "CHIKV typically causes abrupt fever and symmetric debilitating polyarthralgia, with headache, rash, fatigue, and joint swelling. Viral RNA is detectable early; serology is more useful later. Management is supportive and NSAIDs are deferred until dengue is excluded.", keywords: ["chikungunya", "fever joint pain", "joint swelling", "mosquito fever", "chikungunya test"], semanticKeywords: ["chikungunya virus", "Aedes mosquito", "polyarthralgia", "dengue differential", "persistent joint pain"], icd: "A92.0", bodySystem: "Infectious Disease", urgency: "urgent" },
};
