import { KnowledgeEntity } from "../../types";

export const ConjunctivitisPinkEyeDisease: KnowledgeEntity = {
  id: "D0088", slug: "conjunctivitis-pink-eye", entityType: "disease", editorialStatus: "published", reviewStatus: "owner-authorization-required",
  versionInfo: { version: "1.1.0", created: "2026-09-22T00:00:00Z", updated: "2026-09-24T00:00:00Z", reviewed: "2026-09-22T00:00:00Z" },
  title: { en: "Conjunctivitis (Pink Eye)", hi: "कंजंक्टिवाइटिस: लाल, पानी वाली, खुजली या चिपचिपी आंखें", gu: "કન્જક્ટિવાઇટિસ: લાલ, પાણીવાળી, ખંજવાળવાળી અથવા ચીકણી આંખો", mr: "डोळे येणे: लाल, पाणावलेले, खाजरे किंवा चिकट डोळे", es: "Conjuntivitis: Ojos Rojos, Llorosos, con Picor o Pegajosos", ar: "التهاب الملتحمة: عين حمراء أو دامعة أو حاكة أو لزجة" },
  summary: { en: "Conjunctivitis, often called pink eye, can make one or both eyes red, gritty, watery, itchy, or sticky. Viruses, bacteria, allergies, and irritants can overlap, so pain, light sensitivity, vision change, or a red eye in a contact-lens wearer needs prompt eye assessment.", hi: "कंजंक्टिवाइटिस या पिंक आई में आंख लाल, किरकिराहट वाली, पानीदार, खुजली या चिपचिपी हो सकती है। दर्द, रोशनी से परेशानी या दृष्टि बदलने पर तुरंत आंख की जांच कराएं।", gu: "કન્જક્ટિવાઇટિસમાં એક કે બંને આંખ લાલ, કરકરી, પાણીવાળી, ખંજવાળવાળી અથવા ચીકણી થઈ શકે છે. દુખાવો, પ્રકાશથી તકલીફ અથવા દ્રષ્ટિમાં ફેરફાર માટે તાત્કાલિક આંખની તપાસ કરાવો.", mr: "डोळे येणे किंवा पिंक आयमध्ये एक किंवा दोन्ही डोळे लाल, किरकिरे, पाणावलेले, खाजरे किंवा चिकट होऊ शकतात. वेदना, प्रकाशाची संवेदनशीलता किंवा दृष्टी बदलल्यास त्वरित तपासणी करा.", es: "La conjuntivitis puede causar ojos rojos, arenosos, llorosos, con picor o pegajosos. El dolor, la sensibilidad a la luz o cambios de visión requieren una revisión ocular pronta.", ar: "قد يسبب التهاب الملتحمة احمرارًا أو إحساسًا بالرمل أو دموعًا أو حكة أو إفرازات لزجة. يحتاج الألم أو الحساسية للضوء أو تغير الرؤية إلى تقييم سريع للعين." },
  content: {
    overview: "Conjunctivitis is inflammation of the thin membrane lining the white of the eye and inner eyelid. It can make one or both eyes look pink or red and feel gritty, watery, itchy, or sticky. Viruses, bacteria, allergies, and irritants can cause similar symptoms, so a red eye is not something to diagnose from discharge colour alone.",
    definition: "Often called pink eye, conjunctivitis is a common eye-surface condition. Viral and bacterial forms can spread between people; allergy- and irritant-related forms are not contagious.",
    causes: ["Viruses, sometimes alongside a cold or respiratory illness", "Bacteria", "Allergens such as pollen, dust, or animal dander", "Irritants, a foreign body, chemicals, or contact-lens-related irritation"],
    riskFactors: ["Close contact with someone with viral or bacterial conjunctivitis", "Seasonal allergies, eczema, or asthma", "Touching the eyes after contaminated hands or personal items", "Contact-lens wear, especially if a red eye is painful or vision is affected"],
    symptoms: ["Redness of the white of one or both eyes, eyelid swelling, tears, or a gritty/burning feeling", "Crusting of lashes or eyelids, especially on waking, and clear, mucus, or pus-like discharge", "Itching, often prominent when allergy is involved", "Temporary blur from tears or discharge that clears when blinking or gently cleaned away"],
    diagnosis: "A clinician, optometrist, or eye-care professional can usually assess a red eye from the symptoms, history, and eye examination. Tests are not routine, but a swab may be considered for severe, recurrent, newborn, or unusual infection. Because symptoms overlap, eye pain, light sensitivity, persistent blur, intense redness, injury, or contact-lens use deserves prompt assessment.",
    differentialDiagnosis: "Dry eye, blepharitis, a corneal infection or ulcer, foreign body, uveitis, glaucoma, and other causes of a red eye can resemble conjunctivitis and may need urgent treatment.",
    labTests: ["Eye swab or laboratory testing may be used for severe, recurrent, newborn, or atypical cases."], imaging: "Imaging is not normally needed for uncomplicated conjunctivitis.",
    redFlags: ["Eye pain, marked light sensitivity, intense redness, or blurred vision that does not clear after discharge is gently cleaned away", "A red or painful eye in a contact-lens wearer, eye injury, chemical splash, or possible foreign body", "A newborn with red, watery, or sticky eyes—seek medical care right away", "Symptoms that are worsening, not improving, or occur with reduced immune defenses, fever, facial swelling, or feeling very unwell"],
    conventionalManagement: "Treatment depends on the cause. Viral conjunctivitis often improves with time; antibiotics do not treat viruses or allergies. A clinician may prescribe treatment for selected bacterial infections or allergy-related symptoms. Until an eye professional says it is safe, stop wearing contact lenses. Cool compresses and preservative-free artificial tears may help mild discomfort, but do not delay assessment for any red flag.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for conjunctivitis. It must not replace an eye examination, prescribed treatment, infection-control measures, or urgent care for pain, light sensitivity, vision changes, or contact-lens-related red eye.",
    lifestyleAdvice: "Wash hands often and avoid rubbing the eyes. Gently clean discharge using clean water and a fresh clean cloth or pad, then wash hands again. Do not share towels, pillows, eye makeup, eye drops, contact lenses, or lens cases. Pause contact lenses until symptoms have resolved and an eye-care professional advises it is safe; clean, store, and replace lenses and cases as directed.", references: ["CIT-0101", "CIT-0102"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" }, reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" }, evidenceLevel: "Consensus-Guidance", tags: ["Conjunctivitis", "Pink Eye", "Red Eye", "Eye Discharge", "Eye Care"], canonicalUrl: "https://homeo.healthcare/knowledge/diseases/conjunctivitis-pink-eye", readingTimeMinutes: 5, audience: "patient", license: "CC BY-NC-ND 4.0", changeLog: ["1.0.0: Added patient-first conjunctivitis guide with red-eye safety boundaries and symptom-first search terms.", "1.1.0: Simplified the title and added a focused allergy connection."], quickFacts: { "Also called": "Pink eye", "Common causes": "Viruses, bacteria, allergies, and irritants", "Can it spread?": "Viral and bacterial forms can be contagious; allergy-related forms are not", "Urgent check": "Pain, light sensitivity, vision change, intense redness, or contact-lens-related red eye" },
  aiReadiness: { retrievalSummary: "Conjunctivitis is inflammation of the conjunctiva causing redness, tears, discharge, itch, or irritation. Viral, bacterial, allergic, and irritant causes overlap; red flags require prompt eye assessment.", clinicalSummary: "Assess pain, photophobia, persistent visual change, intensity of redness, trauma/chemical exposure, contact-lens use, newborn age, immune status, and systemic illness. Do not infer aetiology solely from discharge. Exclude corneal disease, uveitis, glaucoma, and foreign body when indicated.", patientSummary: "A red, watery, itchy, or sticky eye can have several causes. Avoid rubbing it and do not share towels or eye products. Get prompt care for pain, light sensitivity, vision change, intense redness, a contact-lens-related red eye, or any red eye in a newborn.", studentSummary: "Conjunctivitis presents with conjunctival injection, tearing, irritation, discharge, and sometimes chemosis. Aetiologies include viral, bacterial, allergic, and irritant causes; red-flag symptoms mandate evaluation for keratitis, uveitis, glaucoma, trauma, or foreign body.", keywords: ["conjunctivitis", "pink eye", "red watery eye", "sticky eyes", "itchy eyes"], semanticKeywords: ["eye redness", "conjunctival inflammation", "contact lens red eye", "eye discharge", "photophobia"], icd: "H10.9", bodySystem: "Eye", urgency: "routine" },
};
