import { KnowledgeEntity } from "../../types";

export const ContactDermatitisDisease: KnowledgeEntity = {
  id: "D0076",
  slug: "contact-dermatitis",
  entityType: "disease",
  editorialStatus: "published",
  reviewStatus: "owner-authorization-required",
  versionInfo: {
    version: "1.1.0",
    created: "2026-09-21T00:00:00Z",
    updated: "2026-09-24T00:00:00Z",
    reviewed: "2026-09-21T00:00:00Z",
  },
  title: {
    en: "Contact Dermatitis",
    hi: "कॉन्टैक्ट डर्मेटाइटिस: त्वचा को छूने वाली किसी चीज़ से रैश",
    gu: "કોન્ટેક્ટ ડર્મેટાઇટિસ: ત્વચાને અડતી વસ્તુથી થતો ચકામો",
    mr: "कॉन्टॅक्ट डर्मेटायटिस: त्वचेला लागणाऱ्या वस्तूमुळे पुरळ",
    es: "Dermatitis de Contacto: ¿Algo Está Irritando Tu Piel?",
    ar: "التهاب الجلد التماسي: هل هناك شيء يلامس جلدك؟",
  },
  summary: {
    en: "Contact dermatitis is an itchy or sore rash that can develop after skin touches an irritant or allergen. Learn what to notice, how to investigate a trigger, and when to seek care.",
    hi: "यह खुजली या जलन वाला रैश है जो किसी चीज़ के त्वचा को छूने पर हो सकता है। ट्रिगर पहचानने और मदद लेने के संकेत जानें।",
    gu: "ત્વચાને ચીડવનારી અથવા એલર્જી કરાવતી વસ્તુના સંપર્ક પછી ખંજવાળવાળો ચકામો થઈ શકે છે. ટ્રિગર અને ક્યારે મદદ લેવી તે જાણો.",
    mr: "त्वचेला त्रासदायक किंवा अॅलर्जी निर्माण करणारी वस्तू लागल्यानंतर खाज किंवा जळजळ असलेला पुरळ येऊ शकतो.",
    es: "Una erupción con picor o dolor puede aparecer después de tocar un irritante o alérgeno. Aprende qué observar y cuándo buscar ayuda.",
    ar: "قد يظهر طفح يسبب الحكة أو الألم بعد ملامسة الجلد لمادة مهيجة أو مسببة للحساسية. تعرّف على ما يجب ملاحظته ومتى تطلب المساعدة.",
  },
  content: {
    overview: "Contact dermatitis happens when something that touches the skin either irritates it or causes an allergic skin reaction. It is not contagious. The most useful first question is often: what was newly touching this area before the rash began?",
    definition: "An inflammatory skin reaction caused by direct contact with an irritant or allergen.",
    causes: [
      "Irritants such as frequent wet work, soaps, detergents, solvents, hair dyes, or cleaning products",
      "Allergens such as fragrance, preservatives, metals including nickel, rubber, plants, or topical medicines",
      "Repeated exposure at work, during hobbies, or through personal-care products",
    ],
    riskFactors: [
      "A history of eczema or a weakened skin barrier",
      "Work involving frequent handwashing, chemicals, gloves, food preparation, gardening, hair care, or health care",
      "Regular use of scented or multi-ingredient skin and hair products",
    ],
    symptoms: [
      "Itch, burning, stinging, tenderness, redness, or swelling where the product or material touched the skin",
      "Dry, scaly, cracked, or thickened skin with ongoing exposure",
      "In some cases, small fluid-filled blisters, oozing, or crusting",
    ],
    diagnosis: "Diagnosis is based on the rash pattern, timing, and a careful review of products, work, hobbies, and new exposures. A dermatologist may use patch testing when allergic contact dermatitis is suspected.",
    differentialDiagnosis: "Eczema, hives, psoriasis, fungal infection, scabies, and other medicine-related or infectious rashes can look similar. A persistent rash needs assessment rather than repeated trial-and-error treatment.",
    labTests: ["Patch testing may be considered by a dermatologist when an allergy trigger is unclear or rashes recur."],
    imaging: "Imaging is not used for uncomplicated contact dermatitis.",
    redFlags: [
      "Trouble breathing or swallowing, or swelling of the lips, tongue, eyes, or face — seek emergency care",
      "Rapidly spreading rash, severe pain, fever, widespread blisters, or rash involving the eyes, mouth, or genital skin",
      "Pus, increasing warmth, swelling, or severe tenderness suggesting infection",
    ],
    conventionalManagement: "The key treatment is identifying and avoiding the trigger. A clinician may recommend a suitable moisturiser, protective measures, and prescription treatment for significant inflammation. Avoid using multiple new products at once, which can make the trigger harder to identify.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for contact dermatitis. It should not delay trigger avoidance, dermatologist-led assessment, or treatment for severe reactions or infection.",
    lifestyleAdvice: "Stop using a clearly new or irritating non-prescription product if it is safe to do so. Keep a simple exposure diary, choose fragrance-free skin care, use protective equipment appropriate to the task, and reintroduce products one at a time only after the skin has settled.",
    references: ["CIT-0081", "CIT-0023", "CIT-0024"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" },
  reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" },
  evidenceLevel: "Consensus-Guidance",
  tags: ["Contact Dermatitis", "Allergy Rash", "Irritant Rash", "Skin Allergy", "Dermatology"],
  canonicalUrl: "https://homeo.healthcare/knowledge/diseases/contact-dermatitis",
  readingTimeMinutes: 4,
  audience: "patient",
  license: "CC BY-NC-ND 4.0",
  changeLog: ["1.0.0: Added patient-first contact dermatitis guide with trigger-based discovery and safety boundaries.", "1.1.0: Simplified the title and added focused condition and symptom connections."],
  quickFacts: { "Main question": "What newly touched this part of the skin?", "Not contagious": "Yes", "Common pattern": "Itch or burning where an irritant or allergen made contact", "When to seek urgent care": "Breathing symptoms, facial swelling, widespread blistering, fever, or severe pain" },
  aiReadiness: {
    retrievalSummary: "Contact dermatitis is a non-contagious rash caused by direct contact with an irritant or allergen; review new exposures and seek care for severe or persistent symptoms.",
    clinicalSummary: "Diagnosis depends on morphology, timing, distribution, exposure history, and sometimes patch testing. Severe reactions, infection, mucosal involvement, or airway symptoms need prompt assessment.",
    patientSummary: "A new itchy or burning rash may come from something touching your skin. Pause the likely trigger, keep notes, and seek help for serious symptoms.",
    studentSummary: "Differentiate irritant from allergic contact dermatitis using exposure history and delayed pattern; patch testing supports allergic-contact evaluation.",
    keywords: ["contact dermatitis", "allergic rash", "irritant rash", "skin allergy", "nickel allergy", "fragrance allergy"],
    semanticKeywords: ["allergic contact dermatitis", "irritant contact dermatitis", "patch testing"],
    icd: "L23-L25",
    bodySystem: "Dermatology & Integumentary",
    urgency: "monitor",
  },
};
