import { KnowledgeEntity } from "../../types";

export const DengueFeverDisease: KnowledgeEntity = {
  id: "D0089", slug: "dengue-fever", entityType: "disease", editorialStatus: "published", reviewStatus: "owner-authorization-required",
  versionInfo: { version: "1.1.0", created: "2026-09-22T00:00:00Z", updated: "2026-09-24T00:00:00Z", reviewed: "2026-09-22T00:00:00Z" },
  title: { en: "Dengue", hi: "डेंगू: बुखार, बदन दर्द, जांच और चेतावनी संकेत", gu: "ડેન્ગ્યુ: તાવ, શરીરનો દુખાવો, તપાસ અને ચેતવણીના સંકેતો", mr: "डेंग्यू: ताप, अंगदुखी, चाचणी आणि धोक्याची लक्षणे", es: "Dengue: Fiebre, Dolor Corporal, Pruebas y Señales de Alarma", ar: "حمى الضنك: الحمى وآلام الجسم والفحوص وعلامات الخطر" },
  summary: { en: "Dengue is a viral illness spread by infected mosquitoes. Fever with headache, pain behind the eyes, body aches, nausea, or rash can be dengue, but only a blood test can confirm it. Urgent warning signs can begin as the fever goes away.", hi: "डेंगू संक्रमित मच्छरों से फैलने वाला वायरल रोग है। बुखार के साथ सिरदर्द, आंखों के पीछे दर्द, बदन दर्द, मतली या रैश हो सकता है। पुष्टि के लिए रक्त जांच जरूरी है; बुखार उतरने पर भी चेतावनी संकेत देखें।", gu: "ડેન્ગ્યુ સંક્રમિત મચ્છરોથી ફેલાતો વાયરલ રોગ છે. તાવ સાથે માથાનો દુખાવો, આંખોની પાછળ દુખાવો, શરીરનો દુખાવો, ઊબકા અથવા ચકામો થઈ શકે છે. પુષ્ટિ માટે લોહીની તપાસ જરૂરી છે; તાવ ઉતર્યા પછી પણ ચેતવણીના સંકેતો જુઓ.", mr: "डेंग्यू हा संक्रमित डासांमुळे पसरणारा विषाणूजन्य आजार आहे. तापासोबत डोकेदुखी, डोळ्यांमागे दुखणे, अंगदुखी, मळमळ किंवा पुरळ येऊ शकतो. खात्रीसाठी रक्तचाचणी गरजेची आहे; ताप उतरल्यावरही धोक्याची लक्षणे पाहा.", es: "El dengue es una infección viral transmitida por mosquitos infectados. Fiebre con dolor de cabeza, dolor detrás de los ojos, malestar corporal, náuseas o sarpullido puede ser dengue; solo un análisis de sangre lo confirma. Las señales de alarma pueden empezar cuando la fiebre baja.", ar: "حمى الضنك عدوى فيروسية ينقلها البعوض المصاب. قد تكون الحمى مع الصداع أو الألم خلف العينين أو آلام الجسم أو الغثيان أو الطفح ضنكًا، ولا يؤكده إلا فحص الدم. قد تبدأ علامات الخطر بعد زوال الحمى." },
  content: {
    overview: "Dengue is a viral infection spread through the bite of an infected mosquito. Many infections cause no symptoms, while others cause sudden fever with headache, pain behind the eyes, muscle or joint aches, nausea, vomiting, or rash. It can look like other fever illnesses, so testing and clinical assessment matter. Most people recover, but severe dengue can become an emergency within hours.",
    definition: "A mosquito-borne illness caused by dengue viruses. It is not spread by casual person-to-person contact. A person with dengue can, however, pass virus to another mosquito during the early fever period, so bite prevention helps protect the household and community.",
    causes: ["A bite from an infected Aedes mosquito", "Living in or recently travelling to an area with dengue transmission", "Exposure around places where mosquitoes breed, including containers that collect water"],
    riskFactors: ["Previous dengue infection can increase the chance of severe disease during a later infection", "Pregnancy, infancy, older age, obesity, or conditions such as diabetes, kidney disease, or immune suppression may need closer clinical follow-up", "Not being able to drink enough, pass urine normally, return quickly for review, or monitor warning signs at home"],
    symptoms: ["Sudden fever with severe headache, pain behind the eyes, muscle, bone, or joint aches", "Nausea, vomiting, tiredness, swollen glands, or a rash", "Symptoms commonly last two to seven days; improvement in fever does not by itself mean the risk period is over", "Warning signs can appear in the 24–48 hours after fever settles"],
    diagnosis: "A clinician considers symptoms, recent residence or travel, and local outbreaks. A blood test is the only way to confirm dengue. During early illness, testing may include molecular or NS1 antigen tests with antibody testing; the best test depends on the day of illness and local laboratory guidance. A clinician may also order a complete blood count and repeat it when indicated, but platelet count alone should not be used to judge how unwell someone is.",
    differentialDiagnosis: "Malaria, chikungunya, enteric fever, influenza, COVID-19, leptospirosis, other viral fevers, and some bacterial illnesses can cause overlapping fever, aches, rash, or vomiting. Do not self-diagnose a fever as dengue.",
    labTests: ["Dengue NAAT/PCR or NS1 antigen testing during early illness, according to local availability", "Dengue IgM testing later in the illness when clinically appropriate", "Complete blood count and other blood tests to monitor illness when a clinician advises"], imaging: "Imaging is not needed to diagnose uncomplicated dengue, but hospital teams may use ultrasound or chest imaging if they suspect fluid leakage or another complication.",
    redFlags: ["Severe belly pain or tenderness, persistent or repeated vomiting, or inability to keep fluids down", "Bleeding from the gums or nose, blood in vomit or stool, unusual bruising, or black stools", "Extreme tiredness, restlessness, drowsiness, confusion, pale or cold skin, rapid breathing, or fainting", "Very little urine, severe thirst, worsening weakness, pregnancy, infancy, older age, or important long-term health conditions—seek prompt clinical advice"],
    conventionalManagement: "There is no specific antiviral treatment for dengue. A clinician may recommend close monitoring, oral fluids if safe, and paracetamol/acetaminophen for fever or pain if appropriate for the person. Avoid aspirin and ibuprofen unless a clinician specifically says they are safe, because they can increase bleeding risk. Seek urgent care for any warning sign—especially after the fever comes down. Hospital care may be needed for warning signs, severe dengue, dehydration, or people at higher risk.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for dengue. It must not replace diagnostic testing, hydration, monitoring, clinically recommended fever relief, or urgent hospital care for warning signs or severe dengue.",
    lifestyleAdvice: "Follow the hydration and review plan given by a clinician, rest, and keep track of fluids taken and urine passed if advised. Prevent mosquito bites while unwell and during recovery: use screens or nets, wear covering clothing when practical, and use locally approved repellents as directed. Around the home, cover water-storage containers and empty or scrub containers that can collect water. Do not rely on a falling fever as proof of recovery; keep watching for warning signs for the next two days.", references: ["CIT-0103", "CIT-0104"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" }, reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" }, evidenceLevel: "Consensus-Guidance", tags: ["Dengue", "Viral Fever", "Mosquito-Borne Disease", "Fever Warning Signs", "Dengue Test"], canonicalUrl: "https://homeo.healthcare/knowledge/diseases/dengue-fever", readingTimeMinutes: 6, audience: "patient", license: "CC BY-NC-ND 4.0", changeLog: ["1.1.0: Simplified the title and added focused fever and headache connections.", "1.0.0: Added patient-first dengue guide with testing, fever-phase safety advice, and mosquito prevention."], quickFacts: { "Cause": "Dengue virus spread by infected mosquitoes", "Confirmation": "A blood test", "Critical timing": "Warning signs can begin 24–48 hours after fever settles", "Emergency signs": "Belly pain, repeated vomiting, bleeding, severe weakness, restlessness, or very little urine" },
  aiReadiness: { retrievalSummary: "Dengue is a mosquito-borne viral illness causing fever with headache, retro-orbital pain, body aches, nausea, vomiting, or rash. Severe warning signs often emerge after fever resolves and require urgent care.", clinicalSummary: "Assess timing of fever, local exposure or travel, pregnancy, age, comorbidities, ability to drink and return, urine output, bleeding, abdominal pain, vomiting, mental status, and signs of shock. Confirm with appropriately timed laboratory testing and do not wait for results to manage suspected severe illness.", patientSummary: "If dengue is possible, seek clinical advice about testing and monitor closely even as fever improves. Go for urgent care with bad belly pain, repeated vomiting, bleeding, severe tiredness or restlessness, very little urine, fainting, or breathing difficulty.", studentSummary: "Dengue has febrile, critical, and recovery phases. Warning signs including abdominal pain, persistent vomiting, mucosal bleeding, lethargy/restlessness, fluid accumulation, and rising hematocrit indicate higher risk. Diagnostic strategy varies with day of illness and may combine NAAT/NS1 antigen with IgM testing.", keywords: ["dengue", "dengue fever", "mosquito fever", "fever body pain", "dengue warning signs"], semanticKeywords: ["Aedes mosquito", "dengue testing", "NS1 antigen", "critical phase", "hemorrhagic warning signs"], icd: "A90", bodySystem: "Infectious Disease", urgency: "urgent" },
};
