import { KnowledgeEntity } from "../../types";

export const DryMouthDisease: KnowledgeEntity = {
  id: "D0097", slug: "dry-mouth", entityType: "disease", editorialStatus: "published", reviewStatus: "owner-authorization-required",
  versionInfo: { version: "1.0.0", created: "2026-09-22T00:00:00Z", updated: "2026-09-22T00:00:00Z", reviewed: "2026-09-22T00:00:00Z" },
  title: { en: "Dry Mouth (Xerostomia): Why It Happens and What Helps", hi: "मुंह का सूखापन: कारण और क्या मदद करता है", gu: "સૂકું મોં: કારણો અને શું મદદ કરે", mr: "कोरडे तोंड: कारणे आणि काय मदत करते", es: "Boca Seca (Xerostomía): Por Qué Ocurre y Qué Ayuda", ar: "جفاف الفم: لماذا يحدث وما الذي يساعد" },
  summary: { en: "Dry mouth means there is not enough saliva to keep the mouth comfortably moist. It can happen temporarily with dehydration, anxiety, or mouth breathing, but persistent dryness may be linked to medicines, a blocked nose, oral thrush, diabetes, Sjögren's disease, or cancer treatment. It can raise the risk of tooth decay and mouth infections, so persistent symptoms deserve dental or medical advice.", hi: "मुंह का सूखापन तब होता है जब मुंह को नम रखने के लिए पर्याप्त लार नहीं बनती।", gu: "સૂકું મોં ત્યારે થાય છે જ્યારે મોં ભીનું રાખવા પૂરતી લાળ ન બને.", mr: "तोंड कोरडे पडते तेव्हा ते ओलसर ठेवण्यासाठी पुरेशी लाळ तयार होत नाही.", es: "La boca seca ocurre cuando no hay suficiente saliva para mantener la boca húmeda.", ar: "يحدث جفاف الفم عندما لا يكون هناك لعاب كافٍ لإبقاء الفم رطبًا." },
  content: {
    overview: "Saliva keeps the mouth comfortable, helps chewing, swallowing, taste, and speech, washes away food particles, and helps protect teeth against decay. Dry mouth can be occasional, such as during stress or dehydration, but a dry mouth that continues can make daily life difficult and increase the risk of cavities, fungal infections, mouth sores, and bad breath. It is not an inevitable part of getting older, and the cause is worth identifying.",
    definition: "Dry mouth, or xerostomia, is the feeling or effect of too little saliva to keep the mouth moist. It may reflect reduced saliva production, thicker saliva, mouth breathing, or an underlying oral, medical, or medication-related cause.",
    causes: ["Dehydration, fever, heavy sweating, anxiety, or temporary stress", "Medicines, including some used for blood pressure, depression, allergies, pain, or bladder symptoms", "Mouth breathing during sleep, often with a blocked nose or sleep-related breathing issue", "Oral thrush, tobacco, alcohol, caffeine, or cancer treatment affecting salivary glands", "Conditions such as diabetes or Sjögren's disease, or less commonly nerve damage after head or neck injury"],
    riskFactors: ["Taking more than one medicine that can reduce saliva", "Older age with multiple long-term conditions or medicines, though dry mouth itself is not a normal part of aging", "Diabetes, autoimmune disease, head and neck radiation, chemotherapy, or immune suppression", "Mouth breathing, smoking, alcohol, high caffeine intake, or dehydration", "Previous cavities, gum disease, dentures, oral thrush, or difficulty chewing and swallowing"],
    symptoms: ["A sticky, dry, or rough feeling in the mouth or throat", "Difficulty chewing, swallowing, tasting, speaking, or wearing dentures", "Cracked lips, a dry or fissured tongue, mouth soreness, or burning", "Bad breath, recurrent mouth or throat infections, or sore white patches from thrush", "More tooth decay, sensitivity, gum problems, or food sticking to teeth"],
    diagnosis: "A dentist or clinician will ask when dryness happens, whether it is worse at night, which medicines or treatments you use, nasal symptoms, thirst and urination, dry eyes, joint symptoms, and dental history. They examine the mouth, teeth, gums, tongue, and salivary glands. Depending on the history, they may measure saliva flow, review medicines, test for infection, or arrange blood tests for an underlying condition.",
    differentialDiagnosis: "Dehydration, mouth breathing, medicine effects, anxiety, oral thrush, diabetes, Sjögren's disease, salivary-gland dysfunction, reflux, and burning-mouth symptoms can overlap. A person who feels dry despite normal saliva production may also need assessment for other oral or sensory causes.",
    labTests: ["No test is needed for occasional mild dryness with an obvious temporary trigger", "Saliva-flow testing or oral swabs may be considered when symptoms persist or infection is suspected", "Blood tests may be considered for diabetes, autoimmune disease, nutritional issues, or another cause based on symptoms and examination"],
    imaging: "Imaging is not usually needed for uncomplicated dry mouth. Ultrasound, MRI, or other salivary-gland imaging may be considered only when a clinician suspects gland disease, obstruction, tumour, or a complex underlying condition.",
    redFlags: ["Dryness that makes eating, speaking, swallowing, or wearing dentures difficult, or persists despite a few weeks of self-care", "Painful, red, swollen, bleeding, or infected areas in the mouth; sore white patches; recurrent thrush; or frequent cavities", "Dry mouth together with persistent dry eyes, joint pain, fatigue, swollen glands, excessive thirst, or frequent urination", "A new mouth lump, persistent ulcer, unexplained weight loss, or a change after head and neck cancer treatment", "Trouble breathing or swallowing, significant dehydration, confusion, or rapidly worsening swelling—seek urgent medical care"],
    conventionalManagement: "Treatment targets the cause. A doctor or dentist may review medicines, treat oral thrush or nasal blockage, provide saliva substitutes or other moisture products, and increase preventive dental care. Do not stop or change a prescribed medicine on your own; ask the prescribing clinician whether a safer alternative or dose adjustment is appropriate. Regular dental checks are important because low saliva increases cavity and infection risk.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for persistent dry mouth or its underlying causes. It must not replace assessment of medication effects, diabetes, autoimmune disease, oral infection, or cancer-treatment complications.",
    lifestyleAdvice: "Take regular sips of water and keep water by the bed, choose sugar-free gum or lozenges if safe for you, and use a humidifier at night if the air is dry. Limit alcohol, tobacco, caffeine, and acidic, spicy, salty, or sugary foods and drinks if they irritate your mouth. Brush twice daily with fluoride toothpaste, use alcohol-free mouthwash if recommended, and keep dentures clean and out overnight when advised. Ask a pharmacist or dentist about products designed to keep the mouth moist.",
    references: ["CIT-0119", "CIT-0120"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" }, reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" }, evidenceLevel: "Consensus-Guidance", tags: ["Dry Mouth", "Xerostomia", "Saliva", "Oral Health", "Medication Side Effects"], canonicalUrl: "https://homeo.healthcare/knowledge/diseases/dry-mouth", readingTimeMinutes: 5, audience: "patient", license: "CC BY-NC-ND 4.0", changeLog: ["1.0.0: Added patient-first dry-mouth guide with medicine, dental, and systemic-care boundaries."], quickFacts: { "What saliva does": "Supports comfort, swallowing, and tooth protection", "Common causes": "Medicines, dehydration, mouth breathing, and health conditions", "Why it matters": "Low saliva raises cavity and infection risk", "Get advice": "If persistent or affecting eating, speech, or oral health" },
  aiReadiness: { retrievalSummary: "Dry mouth, or xerostomia, means there is not enough saliva to keep the mouth moist. Persistent symptoms can affect eating and speech and raise the risk of cavities and infection, so the cause should be reviewed.", clinicalSummary: "Assess onset, nocturnal symptoms, hydration, mouth breathing, medicines, cancer treatment, oral examination, dental disease, diabetes symptoms, dry eyes, joint symptoms, immune status, and salivary-gland red flags.", patientSummary: "A dry mouth can be temporary, but persistent dryness is worth discussing with a dentist or doctor. Sip water, protect teeth, and do not stop a prescribed medicine without advice; seek help if eating, swallowing, or speaking becomes difficult.", studentSummary: "Xerostomia arises from reduced or altered salivary flow, sensory dysfunction, or mouth breathing. Medicines are common causes; assess for oral candidiasis, caries, Sjögren's disease, diabetes, cancer-treatment injury, and other salivary-gland disease.", keywords: ["dry mouth", "xerostomia", "sticky mouth", "dry mouth at night", "not enough saliva"], semanticKeywords: ["salivary glands", "medication dry mouth", "mouth breathing dry mouth", "dry mouth cavities", "sjogren dry mouth"], icd: "R68.2", bodySystem: "Oral Health", urgency: "routine" },
};
