import { KnowledgeEntity } from "../../types";

export const HandFootMouthDisease: KnowledgeEntity = {
  id: "D0085", slug: "hand-foot-mouth-disease", entityType: "disease", editorialStatus: "published", reviewStatus: "owner-authorization-required",
  versionInfo: { version: "1.0.0", created: "2026-09-21T00:00:00Z", updated: "2026-09-21T00:00:00Z", reviewed: "2026-09-21T00:00:00Z" },
  title: { en: "Hand, Foot and Mouth Disease: Mouth Sores and Hand-Foot Rash", hi: "हैंड, फुट एंड माउथ डिज़ीज़: मुंह के छाले और हाथ-पैरों पर रैश", gu: "હેન્ડ, ફૂટ એન્ડ માઉથ ડિસીઝ: મોઢાના ચાંદા અને હાથ-પગ પર ચકામો", mr: "हँड, फूट अँड माउथ डिसीज: तोंडातील फोड आणि हात-पायांवरील पुरळ", es: "Mano, Pie y Boca: Llagas Bucales y Erupción", ar: "مرض اليد والقدم والفم: تقرحات الفم وطفح اليدين والقدمين" },
  summary: { en: "Hand, foot and mouth disease is a common, contagious viral illness. It usually causes fever, painful mouth sores, and a rash or blisters on hands and feet, and most people recover within 7 to 10 days.", hi: "यह बच्चों में आम वायरल बीमारी है जिसमें बुखार, मुंह के दर्द वाले छाले और हाथ-पैरों पर दाने हो सकते हैं।", gu: "આ સામાન્ય વાયરલ બીમારીમાં તાવ, મોઢાના દુખાવાવાળા ચાંદા અને હાથ-પગ પર દાણા થઈ શકે છે.", mr: "या सामान्य विषाणूजन्य आजारात ताप, तोंडात दुखरे फोड आणि हात-पायांवर पुरळ येऊ शकतो.", es: "Esta infección viral común puede causar fiebre, llagas dolorosas en la boca y una erupción en manos y pies.", ar: "هذا مرض فيروسي شائع قد يسبب حمى وتقرحات مؤلمة في الفم وطفحًا في اليدين والقدمين." },
  content: {
    overview: "Hand, foot and mouth disease (HFMD) is a common viral illness, particularly in children under five, though older children and adults can get it. A sore throat or fever may come first, followed by painful mouth sores and spots or blisters on hands, feet, buttocks, legs, or arms. It is not the same as foot-and-mouth disease in farm animals.",
    definition: "A contagious illness caused by enteroviruses. It usually settles on its own, but mouth pain can reduce drinking, so preventing dehydration is the most important home-care priority.",
    causes: ["Enteroviruses spread through coughs, sneezes, saliva, stool, fluid from blisters, and contaminated hands or surfaces", "Close contact in homes, nurseries, or childcare settings", "The virus can spread before symptoms are obvious and is often most contagious early in illness"],
    riskFactors: ["Infancy and childhood, especially under five", "Close-contact settings such as childcare and playgroups", "Reduced immune defenses or pregnancy exposure, which deserve individual clinical advice"],
    symptoms: ["Fever, sore throat, reduced appetite, tiredness, or feeling unwell", "Painful mouth spots or ulcers that can make swallowing difficult; extra drooling or refusing drinks can signal mouth pain", "Flat or raised spots and sometimes blisters on palms and soles; colours may look pink, red, darker, grey, or lighter than surrounding skin depending on skin tone"],
    diagnosis: "A clinician can often identify HFMD from the age, fever, mouth sores, and rash pattern. Testing is rarely needed, but other illnesses such as chickenpox, herpes, impetigo, strep throat, or medicine reactions may need to be considered when the pattern is unusual or severe.",
    differentialDiagnosis: "Chickenpox, herpes simplex, impetigo, strep throat, aphthous ulcers, allergic reactions, and other viral rashes can resemble part of the presentation.",
    labTests: ["Tests are not usually needed; a clinician may collect a throat or stool sample in unusual, severe, or outbreak-related cases."],
    imaging: "Imaging is not used for HFMD.",
    redFlags: ["A child who is drinking poorly, peeing less than usual, has a very dry mouth, unusual sleepiness, sunken eyes, or other signs of dehydration", "Breathing difficulty, severe headache, stiff neck, confusion, weakness, persistent high fever, or a child who seems much more unwell", "A baby under six months, reduced immune defenses, pregnancy exposure, fever lasting more than three days, or symptoms not improving after about 10 days"],
    conventionalManagement: "HFMD is viral, so antibiotics do not cure it. A clinician or pharmacist can advise on age-appropriate comfort measures for fever and mouth pain. Offer frequent cool fluids and soft foods; avoid foods and drinks that sting the mouth. Never give aspirin to children. Ask a clinician or pharmacist before using mouth gels, sprays, or pain medicines in young children.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for HFMD. It should not replace hydration, medical assessment for dehydration or serious symptoms, or age-appropriate comfort care.",
    lifestyleAdvice: "Wash hands often with soap and water, especially after toilet or nappy changes and before eating. Clean frequently touched surfaces, avoid sharing cups, cutlery, towels, and toys, and keep blisters clean. Children can usually return when fever-free and well enough to participate, but follow local school or nursery policy and avoid close contact while unwell.",
    references: ["CIT-0095", "CIT-0096"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" }, reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" }, evidenceLevel: "Consensus-Guidance", tags: ["Hand Foot Mouth Disease", "HFMD", "Mouth Ulcers", "Child Rash", "Viral Illness"], canonicalUrl: "https://homeo.healthcare/knowledge/diseases/hand-foot-mouth-disease", readingTimeMinutes: 4, audience: "patient", license: "CC BY-NC-ND 4.0",
  changeLog: ["1.0.0: Added a patient-first HFMD guide focused on hydration, mouth pain, and safe return to normal activity."], quickFacts: { "Cause": "A contagious virus", "Typical pattern": "Fever, mouth sores, then hand-and-foot rash", "Most important home priority": "Offer enough fluids to prevent dehydration", "Usual course": "Most people improve in 7 to 10 days" },
  aiReadiness: { retrievalSummary: "HFMD is a contagious viral illness causing fever, painful mouth sores, and a hand-and-foot rash. Most recover in 7 to 10 days; poor drinking and dehydration are key concerns.", clinicalSummary: "Assess hydration, age, fever duration, immune status, neurologic symptoms, and differential diagnoses. Management is supportive; antibiotics do not treat uncomplicated HFMD.", patientSummary: "HFMD usually improves on its own. Prioritise cool fluids, soft foods, and age-appropriate pain relief advice; seek help if a child drinks poorly or shows dehydration signs.", studentSummary: "HFMD is an enteroviral syndrome with fever, oral enanthem, and acral exanthem. Supportive care and infection-control measures are central; severe neurologic complications are rare.", keywords: ["hand foot mouth disease", "hfmd", "mouth ulcers and rash", "blisters on hands and feet", "child not drinking"], semanticKeywords: ["enterovirus", "oral enanthem", "acral exanthem", "dehydration"], icd: "B08.4", bodySystem: "Infectious Disease & Dermatology", urgency: "monitor" },
};
