import { KnowledgeEntity } from "../../types";

export const ImpetigoDisease: KnowledgeEntity = {
  id: "D0084",
  slug: "impetigo",
  entityType: "disease",
  editorialStatus: "published",
  reviewStatus: "owner-authorization-required",
  versionInfo: {
    version: "1.0.0",
    created: "2026-09-21T00:00:00Z",
    updated: "2026-09-21T00:00:00Z",
    reviewed: "2026-09-21T00:00:00Z",
  },
  title: {
    en: "Impetigo",
    hi: "इम्पेटाइगो: संक्रामक सुनहरी पपड़ी वाले घाव",
    gu: "ઇમ્પેટાઇગો: ચેપી, સોનેરી પોપડીવાળા ચાંદા",
    mr: "इम्पेटिगो: संसर्गजन्य, सोनेरी खपली असलेले घाव",
    es: "Impétigo: Llagas Contagiosas con Costras Doradas",
    ar: "القوباء: قروح معدية ذات قشور ذهبية",
  },
  summary: {
    en: "Impetigo is a common, contagious bacterial infection of the outer skin. It often begins as a sore or blister that breaks and leaves a golden-brown crust, commonly around the nose, mouth, hands, arms, or legs.",
    hi: "इम्पेटाइगो त्वचा की ऊपरी परत का आम, संक्रामक बैक्टीरियल संक्रमण है। इसमें घाव या फफोला फटकर सुनहरी-भूरी पपड़ी बन सकती है।",
    gu: "ઇમ્પેટાઇગો ત્વચાની બહારની સપાટીનો સામાન્ય, ચેપી બેક્ટેરિયલ ચેપ છે. તેમાં ચાંદો અથવા ફોલ્લો ફાટી સોનેરી-ભૂરી પોપડી બની શકે છે.",
    mr: "इम्पेटिगो हा त्वचेच्या बाहेरील थराचा सामान्य, संसर्गजन्य जिवाणूजन्य संसर्ग आहे. यात फोड किंवा फोडका फुटून सोनेरी-तपकिरी खपली तयार होऊ शकते.",
    es: "El impétigo es una infección bacteriana común y contagiosa de la capa externa de la piel. Suele comenzar como una llaga o ampolla que deja una costra dorada.",
    ar: "القوباء عدوى بكتيرية شائعة ومعدية تصيب الطبقة الخارجية من الجلد. غالبًا تبدأ كقرحة أو بثرة تنفجر وتترك قشرة ذهبية بنية.",
  },
  content: {
    overview: "Impetigo is a superficial bacterial skin infection. It often begins as small sore-looking areas or blisters that break and leave a golden or honey-coloured crust. It is common in young children but can affect anyone, and it spreads easily through skin contact or items that have touched the affected skin. Early assessment and the right treatment reduce spread and help prevent a deeper skin infection.",
    definition: "A contagious bacterial infection of the outer skin, most often associated with Staphylococcus aureus, Streptococcus pyogenes, or both. Non-bullous impetigo is the more common form; a blistering form can also occur.",
    causes: [
      "Bacteria entering through already irritated or broken skin, such as a scratch, insect bite, eczema patch, or shaving cut",
      "Direct contact with an affected sore or with fluid from a lesion",
      "Sharing towels, bedding, clothing, toys, or personal items that have contacted affected skin",
    ],
    riskFactors: [
      "Young childhood, close contact settings, and warm or humid weather",
      "Eczema, scabies, insect bites, cuts, or other skin damage that makes the barrier easier for bacteria to enter",
      "A weakened immune system, recurrent skin infection, or repeated close contact with an untreated infection",
    ],
    symptoms: [
      "Small red, itchy, or tender sores or blisters that can break and form golden-brown crusts",
      "Patches that get larger or spread, often around the nose and mouth, or on exposed arms and legs",
      "On brown or black skin, redness may be harder to see; watch for new crusting, weeping, texture change, tenderness, or spread",
    ],
    diagnosis: "A clinician can often diagnose impetigo by examining the skin. A swab may be considered when infection keeps returning, is widespread, is not responding as expected, or a different diagnosis is possible. Cold sores, eczema, scabies, insect bites, fungal infection, and deeper bacterial infection can look similar.",
    differentialDiagnosis: "Cold sores, eczema with secondary infection, scabies, insect bites, fungal infection, chickenpox, herpes simplex, contact dermatitis, and cellulitis can resemble impetigo or coexist with it.",
    labTests: ["A skin swab is not always needed but may be used for recurrent, widespread, severe, or treatment-resistant infection."],
    imaging: "Imaging is not used for typical impetigo.",
    redFlags: [
      "Fever, rapidly spreading redness, warmth, swelling, significant pain, red streaks, or feeling unwell—these can suggest a deeper infection such as cellulitis",
      "A very young baby, a person with a weakened immune system, or sores on breast skin during breastfeeding",
      "Widespread blistering, infection around the eyes, recurrence, or worsening despite a complete clinician- or pharmacist-guided treatment plan",
    ],
    conventionalManagement: "A pharmacist or clinician can assess whether the rash is impetigo and choose a treatment plan based on the number of sores, location, extent, age, and overall health. Treatment may involve a topical or oral antibiotic; use it exactly as prescribed and finish the advised course. Keep sores gently clean and covered as advised. Ask the clinician, school, nursery, or workplace about return timing, because local guidance varies and lesions generally need to be covered and improving.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for impetigo. It should not replace appropriate antibacterial treatment or delay care for a spreading, painful, feverish, or high-risk skin infection.",
    lifestyleAdvice: "Wash hands often, especially before and after touching or caring for affected skin. Do not pick or scratch crusts, and do not share towels, face cloths, bedding, clothes, toys, razors, or sports equipment. Wash recently used towels, sheets, and clothing as advised, keep nails short, and avoid close-contact sports or food preparation while contagious. Treat and protect eczema, scabies, cuts, and bites promptly to reduce skin-barrier breaks.",
    references: ["CIT-0093", "CIT-0094"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" },
  reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" },
  evidenceLevel: "Consensus-Guidance",
  tags: ["Impetigo", "Honey-Coloured Crust", "Skin Infection", "Child Skin Rash", "Dermatology"],
  canonicalUrl: "https://homeo.healthcare/knowledge/diseases/impetigo",
  readingTimeMinutes: 4,
  audience: "patient",
  license: "CC BY-NC-ND 4.0",
  changeLog: ["1.0.0: Added patient-first impetigo guide with spread prevention, skin-tone-aware symptoms, and escalation boundaries."],
  quickFacts: { "Cause": "A contagious bacterial infection of the outer skin", "Common appearance": "Sores or blisters that leave golden-brown crusts", "Often affects": "The face, hands, arms, or legs", "Important to know": "It needs timely assessment because it can spread to other people and parts of the skin" },
  aiReadiness: {
    retrievalSummary: "Impetigo is a common contagious bacterial infection of the outer skin. It commonly causes sores or blisters that form golden-brown crusts around the mouth, nose, arms, or legs and needs appropriate antibacterial assessment and care.",
    clinicalSummary: "Assess distribution, extent, skin-barrier break, systemic symptoms, cellulitis, age, immune status, and recurrent disease. Consider a culture for recurrent, widespread, severe, or non-responsive infection, and distinguish from herpes, eczema, scabies, fungal infection, and other rashes.",
    patientSummary: "Impetigo is a contagious skin infection that often causes golden-crusted sores. A pharmacist or clinician can advise on the right treatment; keeping sores covered, washing hands, and not sharing towels or bedding helps limit spread.",
    studentSummary: "Impetigo is a superficial bacterial infection commonly associated with S. aureus and/or S. pyogenes. Non-bullous lesions evolve from papules or pustules to adherent honey-coloured crusts; escalation is needed for extensive disease, systemic illness, recurrence, or concern for deeper infection.",
    keywords: ["impetigo", "honey coloured crust", "golden crust rash", "child skin infection", "sores around mouth", "contagious skin rash"],
    semanticKeywords: ["superficial bacterial skin infection", "Staphylococcus aureus", "Streptococcus pyogenes", "non-bullous impetigo"],
    icd: "L01.00",
    bodySystem: "Dermatology & Integumentary",
    urgency: "monitor",
  },
};
