import { KnowledgeEntity } from "../../types";

export const InfluenzaDisease: KnowledgeEntity = {
  id: "D0093", slug: "influenza", entityType: "disease", editorialStatus: "published", reviewStatus: "owner-authorization-required",
  versionInfo: { version: "1.0.0", created: "2026-09-22T00:00:00Z", updated: "2026-09-22T00:00:00Z", reviewed: "2026-09-22T00:00:00Z" },
  title: { en: "Flu (Influenza)", hi: "इन्फ्लुएंजा: अचानक बुखार, खांसी, बदन दर्द और रिकवरी", gu: "ઇન્ફ્લુએન્ઝા: અચાનક તાવ, ઉધરસ, શરીરનો દુખાવો અને સાજા થવું", mr: "फ्लू: अचानक ताप, खोकला, अंगदुखी आणि बरे होणे", es: "Gripe: Fiebre Súbita, Tos, Dolor Corporal y Recuperación", ar: "الإنفلونزا: حمى مفاجئة وسعال وآلام الجسم وتعافٍ" },
  summary: { en: "Flu is a contagious respiratory infection that often starts suddenly with fever or chills, cough, sore throat, body aches, headache, and fatigue. Most people recover with rest and fluids, but babies, older adults, pregnant people, and people with long-term conditions should get advice early.", hi: "फ्लू एक संक्रामक श्वसन संक्रमण है जो अक्सर अचानक बुखार या ठंड, खांसी, गले में खराश, बदन दर्द और थकान से शुरू होता है।", gu: "ફ્લૂ ચેપી શ્વસન ચેપ છે જે ઘણીવાર અચાનક તાવ, ઉધરસ, ગળામાં દુખાવો, શરીરનો દુખાવો અને થાકથી શરૂ થાય છે.", mr: "फ्लू हा संसर्गजन्य श्वसन आजार आहे जो अचानक ताप, खोकला, घसा दुखणे, अंगदुखी आणि थकव्याने सुरू होतो.", es: "La gripe es una infección respiratoria contagiosa que suele comenzar de repente con fiebre, tos, dolor de garganta, dolores corporales y cansancio.", ar: "الإنفلونزا عدوى تنفسية معدية تبدأ غالبًا فجأة بحمى أو قشعريرة وسعال والتهاب الحلق وآلام الجسم والإرهاق." },
  content: {
    overview: "Influenza, commonly called flu, is a contagious respiratory infection of the nose, throat, and sometimes lungs. Sudden fever or chills, dry cough, sore throat, runny nose, headache, body aches, and fatigue are common. It can resemble COVID-19, a cold, or other infections, so symptoms alone cannot confirm the cause.", definition: "A viral respiratory illness caused mainly by influenza A and B viruses. It spreads through close respiratory contact and contaminated hands or surfaces.",
    causes: ["Influenza virus exposure from an infected person", "Close indoor contact when respiratory viruses are circulating", "Touching the face after contaminated hands or surfaces"], riskFactors: ["Pregnancy", "Children under 5, especially under 2, and adults 65 or older", "Asthma, diabetes, heart, lung, kidney, liver, neurologic, or immune conditions"],
    symptoms: ["Sudden fever or chills, dry cough, sore throat, runny or stuffy nose", "Headache, body aches, fatigue, and weakness", "Vomiting or diarrhoea can occur, especially in children", "Cough and tiredness can persist after fever improves"],
    diagnosis: "A clinician may diagnose flu from symptoms during an outbreak or use a respiratory swab test when it changes treatment, infection-control, or risk decisions. Testing may also look for COVID-19 or other respiratory viruses.", differentialDiagnosis: "COVID-19, common cold, RSV, pneumonia, strep throat, sinus infection, dengue and other febrile illnesses can overlap.", labTests: ["Respiratory swab tests for influenza when clinically useful", "COVID-19 or other respiratory-virus tests when indicated"], imaging: "Imaging is not needed for uncomplicated flu; a chest X-ray may be needed if pneumonia or another complication is suspected.",
    redFlags: ["Difficulty breathing, chest or persistent abdominal pain/pressure, blue lips or face, confusion, seizures, fainting, or severe weakness", "Dehydration, very little urine, inability to drink, or a child with no tears, dry mouth, or reduced alertness", "Fever or cough that improves then returns or worsens, or worsening of a long-term condition", "Any fever in an infant under 3 months, or flu symptoms in pregnancy, immune suppression, or high-risk chronic illness"],
    conventionalManagement: "Most mild flu improves with rest, fluids, and symptom relief recommended by a clinician or pharmacist. Prescription antiviral medicines can reduce complications for people at higher risk and work best when started early, so contact a clinician promptly if you are high-risk or very unwell. Antibiotics do not treat flu unless a clinician diagnoses a bacterial infection.", homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for influenza. It must not replace clinical assessment, prescription antivirals when indicated, hydration, vaccination, or urgent care for breathing or neurologic warning signs.", lifestyleAdvice: "Stay home and away from others while acutely unwell except to obtain medical care, rest, drink fluids, cover coughs and sneezes, and wash hands. Return to normal activities only when symptoms are improving and you have been fever-free for at least 24 hours without fever-reducing medicine, following local guidance. Annual influenza vaccination is the best prevention; ask a clinician or immunization service about eligibility.", references: ["CIT-0111", "CIT-0112"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" }, reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" }, evidenceLevel: "Consensus-Guidance", tags: ["Influenza", "Flu", "Fever Cough", "Respiratory Infection", "Flu Vaccine"], canonicalUrl: "https://homeo.healthcare/knowledge/diseases/influenza", readingTimeMinutes: 5, audience: "patient", license: "CC BY-NC-ND 4.0", changeLog: ["1.0.0: Added patient-first flu guide with high-risk, antiviral, and emergency-care boundaries."], quickFacts: { "Typical onset": "Often sudden", "Common symptoms": "Fever or chills, cough, aches, headache, and fatigue", "High-risk groups": "Young children, older adults, pregnancy, and chronic conditions", "Best prevention": "Annual influenza vaccination" },
  aiReadiness: { retrievalSummary: "Influenza is a contagious respiratory infection that often starts abruptly with fever, cough, aches, and fatigue. Most cases recover, but high-risk people need early clinical contact and breathing or neurologic signs require urgent care.", clinicalSummary: "Assess onset, respiratory distress, hydration, age, pregnancy, comorbidities, immune status, risk of pneumonia, and illness course. Consider influenza/COVID testing and early antiviral treatment when indicated.", patientSummary: "Sudden fever, cough, aches, and fatigue may be flu. Rest and hydrate, but contact a clinician early if you are high-risk or very unwell; seek urgent help for breathing trouble, chest pain, confusion, dehydration, or worsening after initial improvement.", studentSummary: "Influenza A and B cause acute contagious respiratory illness. Early antivirals are most useful for severe or high-risk disease. Distinguish from other respiratory viruses and watch for viral or bacterial pneumonia and exacerbation of chronic disease.", keywords: ["influenza", "flu", "sudden fever body aches", "flu cough", "flu vaccine"], semanticKeywords: ["influenza virus", "respiratory infection", "antiviral treatment", "flu emergency signs", "seasonal vaccination"], icd: "J11.1", bodySystem: "Respiratory", urgency: "routine" },
};
