import { KnowledgeEntity } from "../../types";

export const JockItchTineaCrurisDisease: KnowledgeEntity = {
  id: "D0079",
  slug: "jock-itch-tinea-cruris",
  entityType: "disease",
  editorialStatus: "published",
  reviewStatus: "owner-authorization-required",
  versionInfo: {
    version: "1.1.0",
    created: "2026-09-21T00:00:00Z",
    updated: "2026-09-24T00:00:00Z",
    reviewed: "2026-09-21T00:00:00Z",
  },
  title: {
    en: "Jock Itch",
    hi: "जॉक इच: जांघ की त्वचा में खुजली और पपड़ी वाला फंगल रैश",
    gu: "જોક ઇચ: જાંઘના વળાંકમાં ખંજવાળ અને છાલ ઉતરતો ફંગલ ચકામો",
    mr: "जॉक इच: मांडीच्या त्वचेत खाज आणि खवले असलेला फंगल पुरळ",
    es: "Tiña Inguinal: Erupción con Picor y Descamación en la Ingle",
    ar: "حكة جوك: طفح فطري متقشر ومثير للحكة في الأربية",
  },
  summary: {
    en: "Jock itch is a common fungal infection of the groin and inner thighs. It can cause itchy, scaly patches and is more likely when the area stays warm, sweaty, or damp.",
    hi: "जॉक इच जांघों और ग्रोइन का एक आम फंगल संक्रमण है। इसमें खुजली वाले, पपड़ीदार पैच हो सकते हैं।",
    gu: "જોક ઇચ જાંઘના વળાંક અને અંદરની જાંઘનો સામાન્ય ફંગલ ચેપ છે. તેમાં ખંજવાળવાળા, છાલ ઉતરતા ચકામા થઈ શકે છે.",
    mr: "जॉक इच हा जांघेच्या वळणाचा आणि आतील मांडीचा सामान्य बुरशीजन्य संसर्ग आहे. त्यात खाज आणि खवले असलेले चट्टे होऊ शकतात.",
    es: "La tiña inguinal es una infección fúngica común de la ingle y los muslos internos. Puede causar parches con picor y descamación.",
    ar: "حكة جوك عدوى فطرية شائعة في الأربية وداخل الفخذين وقد تسبب بقعًا متقشرة ومثيرة للحكة.",
  },
  content: {
    overview: "Jock itch, or tinea cruris, is a fungal infection that usually affects the inner thigh skin folds and nearby groin skin. It can cause itchy, scaly, red or discoloured patches. The same group of fungi can also cause athlete’s foot and other ringworm infections, so a foot infection can sometimes be part of the wider picture.",
    definition: "A superficial dermatophyte fungal infection affecting the groin and inner-thigh skin folds; it is a form of ringworm and not caused by a worm.",
    causes: [
      "Dermatophyte fungi affecting the outer skin layer in a warm, moist body area",
      "Transfer through skin contact, shared towels or clothing, or from a fungal infection elsewhere on the body such as the feet",
      "Sweating, damp clothing, friction, and tight or non-breathable clothing that leave skin folds warm and moist",
    ],
    riskFactors: [
      "Hot weather, frequent sweating, exercise, or staying in damp workout clothing",
      "Sharing towels, underwear, clothing, bedding, or sports gear",
      "Athlete’s foot, close skin contact, or reduced immune defenses; persistent groin rashes need careful assessment rather than self-diagnosis",
    ],
    symptoms: [
      "Itchy, scaly spots on the inner thigh skin folds that may slowly enlarge",
      "Redness on lighter skin or purple, brown, grey, or darker patches on darker skin",
      "A clearer centre or more active edge; symptoms may worsen with heat, friction, or sweating",
    ],
    diagnosis: "A clinician may assess the appearance and distribution of the rash. Skin scraping or fungal testing can help when the cause is unclear, the rash is widespread or recurrent, symptoms are severe, or treatment has not helped.",
    differentialDiagnosis: "Intertrigo, contact dermatitis, eczema, psoriasis, candidal infection, bacterial infection, and sexually transmitted infections can affect the groin region differently. A painful, blistering, ulcerated, genital, or unexplained rash should be assessed rather than assumed to be jock itch.",
    labTests: ["Skin scraping with microscopy or fungal testing may be used for an uncertain, recurrent, extensive, or treatment-resistant rash."],
    imaging: "Imaging is not used for uncomplicated jock itch.",
    redFlags: [
      "Fever, severe pain, pus, rapidly spreading warmth or swelling, or skin breakdown",
      "A rash on the genitals, anus, buttocks, or face; sores, blisters, or a rash after intimate contact",
      "Diabetes, reduced immune defenses, recurrent infection, or no improvement after appropriate pharmacist or clinician advice",
    ],
    conventionalManagement: "A pharmacist or clinician can advise on an appropriate antifungal treatment and how long to use it. The best treatment depends on the pattern, extent, other conditions, and whether infection elsewhere—such as athlete’s foot—also needs management. Do not use a steroid cream alone on a rash that could be fungal, because it can make ringworm worse.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for fungal groin infection. It should not replace antifungal care or delay assessment of a painful, persistent, severe, genital, or spreading rash.",
    lifestyleAdvice: "Gently wash and dry the area after bathing and exercise, change sweaty underwear and workout clothing promptly, choose breathable loose-fitting fabrics, do not share towels or clothing, and wash hands after touching a rash. Address possible athlete’s foot as well, because fungi can spread between body sites.",
    references: ["CIT-0084", "CIT-0082", "CIT-0023"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" },
  reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" },
  evidenceLevel: "Consensus-Guidance",
  tags: ["Jock Itch", "Tinea Cruris", "Fungal Groin Rash", "Itchy Inner Thigh", "Dermatology"],
  canonicalUrl: "https://homeo.healthcare/knowledge/diseases/jock-itch-tinea-cruris",
  readingTimeMinutes: 4,
  audience: "patient",
  license: "CC BY-NC-ND 4.0",
  changeLog: ["1.0.0: Added patient-first jock itch guide with symptom boundaries and moisture-reduction habits.", "1.1.0: Simplified the title and added focused condition and symptom connections."],
  quickFacts: { "Cause": "A fungal infection of groin and inner-thigh skin", "Often looks like": "Itchy, scaly patches in skin folds", "Helpful habit": "Change out of sweaty clothing promptly", "When to seek advice": "If it is painful, genital, blistering, spreading, persistent, or recurrent" },
  aiReadiness: {
    retrievalSummary: "Jock itch, or tinea cruris, is a fungal infection of groin and inner-thigh skin folds that can cause itchy, scaly patches and needs appropriate antifungal assessment or treatment.",
    clinicalSummary: "Assess distribution, concurrent tinea pedis, inflammatory severity, and mimics; test when diagnosis is unclear, disease is recurrent or extensive, or first treatment fails.",
    patientSummary: "Jock itch is a fungal skin infection. Keep the area dry, change sweaty clothing, do not share towels, and ask a pharmacist or clinician about the right antifungal treatment.",
    studentSummary: "Tinea cruris commonly affects the inguinal folds and inner thighs; distinguish from inflammatory, candidal, bacterial, and sexually transmitted causes of groin rash.",
    keywords: ["jock itch", "tinea cruris", "fungal groin rash", "itchy inner thigh", "groin rash"],
    semanticKeywords: ["dermatophyte", "inguinal fungal infection", "moisture-associated fungal rash"],
    icd: "B35.6",
    bodySystem: "Dermatology & Integumentary",
    urgency: "monitor",
  },
};
