import { KnowledgeEntity } from "../../types";

export const MalariaDisease: KnowledgeEntity = {
  id: "D0092", slug: "malaria", entityType: "disease", editorialStatus: "published", reviewStatus: "owner-authorization-required",
  versionInfo: { version: "1.0.0", created: "2026-09-22T00:00:00Z", updated: "2026-09-22T00:00:00Z", reviewed: "2026-09-22T00:00:00Z" },
  title: { en: "Malaria: Fever, Chills, Testing, Treatment, and Prevention", hi: "मलेरिया: बुखार, ठंड लगना, जांच, इलाज और बचाव", gu: "મેલેરિયા: તાવ, ઠંડી લાગવી, તપાસ, સારવાર અને બચાવ", mr: "मलेरिया: ताप, थंडी वाजणे, चाचणी, उपचार आणि प्रतिबंध", es: "Malaria: Fiebre, Escalofríos, Pruebas, Tratamiento y Prevención", ar: "الملاريا: الحمى والقشعريرة والفحوص والعلاج والوقاية" },
  summary: { en: "Malaria is a serious parasitic infection spread by some mosquitoes. Fever, chills, headache, aches, vomiting, or diarrhoea can be malaria but overlap with many illnesses. Prompt blood testing and clinician-directed treatment are essential, especially after travel or residence in an at-risk area.", hi: "मलेरिया कुछ मच्छरों से फैलने वाला गंभीर परजीवी संक्रमण है। बुखार, ठंड लगना, सिरदर्द, बदन दर्द, उल्टी या दस्त कई बीमारियों जैसे हो सकते हैं। जोखिम वाले क्षेत्र में रहने या यात्रा के बाद तुरंत रक्त जांच और इलाज जरूरी है।", gu: "મેલેરિયા કેટલાક મચ્છરોથી ફેલાતો ગંભીર પરજીવી ચેપ છે. તાવ, ઠંડી, માથાનો દુખાવો, શરીરનો દુખાવો, ઊલટી અથવા ઝાડા ઘણા રોગો જેવા હોઈ શકે છે. જોખમવાળા વિસ્તારમાં રહેવા કે મુસાફરી પછી તાત્કાલિક લોહીની તપાસ અને સારવાર જરૂરી છે.", mr: "मलेरिया हा काही डासांमुळे पसरणारा गंभीर परजीवी संसर्ग आहे. ताप, थंडी, डोकेदुखी, अंगदुखी, उलटी किंवा जुलाब इतर आजारांसारखे असू शकतात. जोखमीच्या भागात राहिल्यानंतर किंवा प्रवासानंतर त्वरित रक्तचाचणी आणि उपचार गरजेचे आहेत.", es: "La malaria es una infección parasitaria grave transmitida por ciertos mosquitos. Fiebre, escalofríos, dolor de cabeza, dolores, vómitos o diarrea pueden parecerse a muchas enfermedades. Las pruebas de sangre y el tratamiento clínico oportunos son esenciales.", ar: "الملاريا عدوى طفيلية خطيرة ينقلها بعض البعوض. قد تتشابه الحمى والقشعريرة والصداع والآلام والقيء أو الإسهال مع أمراض عديدة. يلزم فحص دم وعلاج سريعان بإشراف طبي." },
  content: {
    overview: "Malaria is a serious infection caused by parasites and spread mainly by infected female Anopheles mosquitoes. Early symptoms can be nonspecific: fever, chills, headache, tiredness, muscle aches, nausea, vomiting, or diarrhoea. It can become life-threatening quickly, so fever after possible exposure needs prompt clinical assessment rather than home diagnosis.",
    definition: "A parasitic infection caused by Plasmodium species. Some species can remain dormant in the liver and cause illness again later, which is why the exact species and complete treatment plan matter.",
    causes: ["Bite from an infected Anopheles mosquito", "Living in or travelling to an area with malaria transmission", "Rarely, infected blood products, contaminated needles, or transmission during pregnancy"],
    riskFactors: ["Infants and children under 5, pregnancy, travellers, and people with HIV or reduced immune defenses", "Not using recommended bite prevention or travel medicines when indicated", "Delayed testing or difficulty accessing urgent assessment"],
    symptoms: ["Fever, chills, headache, tiredness, muscle aches, and flu-like illness", "Nausea, vomiting, diarrhoea, or abdominal discomfort", "Symptoms may begin days to weeks after exposure; some types can present months later", "Mild symptoms can progress, so a familiar fever pattern cannot safely rule malaria in or out"],
    diagnosis: "Only a healthcare professional can diagnose malaria with a blood test. Microscopy of a blood smear helps identify parasites and species; rapid tests can support diagnosis where microscopy is unavailable, and other testing may confirm species. If symptoms and exposure strongly suggest malaria, urgent assessment should not wait for symptoms to become severe.",
    differentialDiagnosis: "Dengue, chikungunya, typhoid, influenza, COVID-19, leptospirosis, viral hepatitis, urinary infection, meningitis, and many other infections can overlap with malaria symptoms.",
    labTests: ["Blood smear microscopy to confirm malaria and identify the species", "Rapid diagnostic test where appropriate, with confirmatory testing according to local guidance", "Additional blood tests to assess anaemia, kidney or liver effects, glucose, and severity when needed"], imaging: "Imaging is not used to diagnose uncomplicated malaria, but hospital teams may arrange tests if severe complications or another condition are suspected.",
    redFlags: ["Confusion, seizures, fainting, marked drowsiness, severe weakness, or difficulty breathing", "Dark or bloody urine, yellow eyes or skin, abnormal bleeding, or severe dehydration", "Repeated vomiting or inability to drink, very little urine, or rapidly worsening fever", "Fever in a child under 5, pregnancy, or after travel/residence in an area where malaria occurs—seek prompt assessment"],
    conventionalManagement: "Malaria always needs clinician-directed prescription treatment. The medicine and duration depend on the parasite species, where infection was acquired, age, weight, pregnancy, severity, and local resistance. Severe malaria needs emergency hospital treatment. Do not use leftover or shared antimalarial medicines, and complete treatment exactly as prescribed.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for malaria. It must not replace urgent blood testing, prescribed antimalarial medicine, bite prevention, or emergency care for severe symptoms.",
    lifestyleAdvice: "If malaria is possible, seek testing promptly and follow the care plan. Reduce mosquito bites using treated bed nets, screens, covering clothing when practical, and locally approved repellents as directed. Ask a travel-health clinician before travel about destination-specific prevention medicines; they are chosen individually and do not replace bite prevention.", references: ["CIT-0109", "CIT-0110"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" }, reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" }, evidenceLevel: "Consensus-Guidance", tags: ["Malaria", "Fever and Chills", "Malaria Test", "Mosquito Prevention", "Travel Health"], canonicalUrl: "https://homeo.healthcare/knowledge/diseases/malaria", readingTimeMinutes: 6, audience: "patient", license: "CC BY-NC-ND 4.0", changeLog: ["1.0.0: Added patient-first malaria guide with urgent testing, severe-symptom boundaries, and prevention."], quickFacts: { "Cause": "Plasmodium parasites", "Confirmation": "Blood testing", "Primary action": "Prompt clinical assessment for possible exposure and fever", "Emergency signs": "Confusion, seizures, breathing difficulty, dark urine, jaundice, or rapid worsening" },
  aiReadiness: { retrievalSummary: "Malaria is a mosquito-borne parasitic infection with nonspecific fever and chills that requires prompt blood testing and clinician-directed treatment. It can progress to severe illness quickly.", clinicalSummary: "Assess exposure/travel, pregnancy, age, immune status, mental state, breathing, hydration, urine, jaundice, anaemia, and ability to obtain immediate diagnostics. Confirm with microscopy or RDT per local guidance and begin appropriate therapy promptly.", patientSummary: "Fever after possible malaria exposure needs urgent testing; do not wait for a classic pattern. Go for emergency care with confusion, seizures, breathing difficulty, dark urine, jaundice, severe weakness, or inability to drink.", studentSummary: "Malaria is caused by Plasmodium parasites transmitted predominantly by Anopheles mosquitoes. Diagnosis requires parasite-based testing. Species, resistance geography, host factors, and severity determine therapy; P. falciparum can become severe rapidly.", keywords: ["malaria", "fever chills", "malaria test", "mosquito fever", "travel fever"], semanticKeywords: ["Plasmodium", "blood smear", "rapid diagnostic test", "Anopheles", "severe malaria"], icd: "B54", bodySystem: "Infectious Disease", urgency: "urgent" },
};
