import { KnowledgeEntity } from "../../types";

export const MeaslesRubeolaDisease: KnowledgeEntity = {
  id: "D0087", slug: "measles-rubeola", entityType: "disease", editorialStatus: "published", reviewStatus: "owner-authorization-required",
  versionInfo: { version: "1.0.0", created: "2026-09-22T00:00:00Z", updated: "2026-09-22T00:00:00Z", reviewed: "2026-09-22T00:00:00Z" },
  title: { en: "Measles (Rubeola): Fever, Cough, Red Eyes, and a Spreading Rash", hi: "खसरा: बुखार, खांसी, लाल आंखें और फैलता रैश", gu: "ઓરી: તાવ, ઉધરસ, લાલ આંખો અને ફેલાતો ચકામો", mr: "गोवर: ताप, खोकला, लाल डोळे आणि पसरणारा पुरळ", es: "Sarampión: Fiebre, Tos, Ojos Rojos y una Erupción que se Extiende", ar: "الحصبة: حمى وسعال واحمرار العينين وطفح منتشر" },
  summary: { en: "Measles is a highly contagious viral respiratory disease. Fever, cough, runny nose, and red watery eyes are followed by a rash that usually begins on the face and spreads downward. Suspected measles needs prompt call-ahead medical advice.", hi: "खसरा एक अत्यंत संक्रामक वायरल श्वसन रोग है। बुखार, खांसी, नाक बहना और लाल आंखों के बाद रैश हो सकता है।", gu: "ઓરી ખૂબ ચેપી વાયરલ શ્વસન રોગ છે. તાવ, ઉધરસ, વહેતું નાક અને લાલ આંખો પછી ચકામો થઈ શકે છે.", mr: "गोवर हा अत्यंत संसर्गजन्य विषाणूजन्य श्वसन आजार आहे. ताप, खोकला, वाहणारे नाक आणि लाल डोळ्यांनंतर पुरळ येऊ शकतो.", es: "El sarampión es una enfermedad respiratoria viral muy contagiosa. La fiebre, tos y ojos llorosos son seguidos por una erupción que se extiende.", ar: "الحصبة مرض فيروسي تنفسي شديد العدوى. تتبعه حمى وسعال وسيلان الأنف واحمرار العينين ثم طفح ينتشر." },
  content: {
    overview: "Measles, also called rubeola, is a serious and highly contagious viral respiratory disease. It commonly starts with high fever, cough, runny nose, and red watery eyes. Small white spots inside the cheeks can occur before a flat or slightly raised rash begins on the face and upper neck and moves downward. If measles is possible, call a clinician or hospital before arriving so they can prevent exposing other people.",
    definition: "A vaccine-preventable disease caused by measles virus. It spreads through the air when an infected person breathes, coughs, or sneezes, and can cause severe complications.",
    causes: ["Measles virus exposure from an infected person", "Airborne spread in shared indoor spaces", "Lack of immunity from vaccination or prior infection"],
    riskFactors: ["No documented immunity or incomplete vaccination", "Exposure during an outbreak or travel to an area with measles transmission", "Young age, pregnancy, poor nutrition, or reduced immune defenses increase complication risk"],
    symptoms: ["High fever, cough, runny nose, and red or watery eyes", "Tiny white mouth spots in some people before rash", "Rash beginning on the face and upper neck and spreading down the body; on darker skin, look for new raised texture and a colour change from surrounding skin"],
    diagnosis: "A clinician considers symptoms, timing, vaccination history, and exposure, then arranges laboratory confirmation and public-health notification when needed. Other febrile rashes such as rubella, chickenpox, medicine reactions, dengue, and other viral illnesses can look similar, but suspected measles should be managed urgently.",
    differentialDiagnosis: "Rubella, chickenpox, hand-foot-and-mouth disease, scarlet fever, dengue, medicine reactions, and other viral exanthems may resemble the presentation.",
    labTests: ["Public-health and clinical teams may use measles PCR and blood testing to confirm suspected cases."], imaging: "Imaging is not used to diagnose measles.",
    redFlags: ["Difficulty breathing, pain when breathing or coughing, dehydration, persistent fever or headache, confusion, severe weakness, or blue colour around the mouth", "A baby or young child with poor feeding, low energy, fewer wet nappies or urination, or tears absent when crying", "Pregnancy, reduced immune defenses, or known exposure without immunity—contact a clinician immediately even before symptoms"],
    conventionalManagement: "There is no routine antiviral cure for uncomplicated measles; care is supportive and complications need medical treatment. Call ahead urgently if measles is possible. Stay home and away from other people until a clinician or public-health team says it is safe. Vaccination is the best protection; ask a clinician or immunization service about local MMR/MR eligibility and urgent advice after an exposure.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for measles. It must not replace urgent clinical contact, isolation guidance, vaccination, hydration, or care for complications.",
    lifestyleAdvice: "Do not attend a clinic, school, childcare, work, or public setting without calling ahead if measles is suspected. Avoid contact with babies, pregnant people, and anyone with a weakened immune system. Follow the isolation timeframe given by local public-health authorities, wash hands, cover coughs and sneezes, and ensure close contacts receive timely public-health guidance.", references: ["CIT-0099", "CIT-0100"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" }, reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" }, evidenceLevel: "Consensus-Guidance", tags: ["Measles", "Rubeola", "Fever Rash", "MMR Vaccine", "Infectious Disease"], canonicalUrl: "https://homeo.healthcare/knowledge/diseases/measles-rubeola", readingTimeMinutes: 5, audience: "patient", license: "CC BY-NC-ND 4.0", changeLog: ["1.0.0: Added patient-first measles guide with call-ahead, isolation, and urgent-risk advice."], quickFacts: { "Cause": "Measles virus", "Early pattern": "Fever, cough, runny nose, and red watery eyes", "Rash pattern": "Usually begins on face and spreads downward", "Most important action": "Call ahead urgently before attending medical care" },
  aiReadiness: { retrievalSummary: "Measles is a highly contagious respiratory virus causing fever, cough, coryza, conjunctivitis, and a downward-spreading rash. Suspected illness requires immediate call-ahead medical advice and isolation.", clinicalSummary: "Treat suspected measles as an urgent public-health matter; assess exposure, immunity, pregnancy, immune status, respiratory symptoms, dehydration, and neurologic change. Arrange laboratory confirmation and appropriate isolation.", patientSummary: "If measles is possible, call a clinician or hospital before going in and stay away from others. Vaccination is the best protection; get urgent advice after exposure or during pregnancy or immune suppression.", studentSummary: "Rubeola presents with prodromal fever, cough, coryza, conjunctivitis, possible Koplik spots, then a cephalocaudal maculopapular rash. It is airborne and requires public-health notification and laboratory confirmation.", keywords: ["measles", "rubeola", "measles rash", "fever cough red eyes", "mmr vaccine"], semanticKeywords: ["measles virus", "Koplik spots", "maculopapular rash", "airborne isolation"], icd: "B05.9", bodySystem: "Infectious Disease", urgency: "urgent" },
};
