import { KnowledgeEntity } from "../../types";

export const MouthUlcersDisease: KnowledgeEntity = {
  id: "D0094", slug: "mouth-ulcers", entityType: "disease", editorialStatus: "published", reviewStatus: "owner-authorization-required",
  versionInfo: { version: "1.0.0", created: "2026-09-22T00:00:00Z", updated: "2026-09-22T00:00:00Z", reviewed: "2026-09-22T00:00:00Z" },
  title: { en: "Mouth Ulcers: Painful Sores Inside the Mouth", hi: "मुंह के छाले: मुंह के अंदर दर्दनाक घाव", gu: "મોંના ચાંદા: મોંની અંદરના દુખાવાવાળા ઘા", mr: "तोंडातील व्रण: तोंडाच्या आत वेदनादायक फोड", es: "Úlceras Bucales: Llagas Dolorosas Dentro de la Boca", ar: "قرح الفم: تقرحات مؤلمة داخل الفم" },
  summary: { en: "Mouth ulcers, also called canker sores or aphthous ulcers, are common painful sores inside the mouth. They usually settle within 1 to 2 weeks and are not the same as contagious cold sores. An ulcer that lasts, recurs often, looks different, or makes eating or drinking difficult needs dental or clinical advice.", hi: "मुंह के छाले आम और दर्दनाक घाव हैं जो आमतौर पर 1 से 2 सप्ताह में ठीक हो जाते हैं।", gu: "મોંના ચાંદા સામાન્ય અને દુખાવાવાળા ઘા છે જે સામાન્ય રીતે 1 થી 2 અઠવાડિયામાં મટી જાય છે.", mr: "तोंडातील व्रण सामान्य आणि वेदनादायक असतात व सहसा 1 ते 2 आठवड्यांत बरे होतात.", es: "Las úlceras bucales son llagas comunes y dolorosas que suelen mejorar en 1 a 2 semanas.", ar: "قرح الفم شائعة ومؤلمة وتتحسن عادة خلال أسبوع إلى أسبوعين." },
  content: {
    overview: "Mouth ulcers are small painful sores that form inside the mouth—often on the inner lips or cheeks, gums, or tongue. They commonly have a pale white or yellow centre with a red edge and can sting while eating, drinking, or talking. A typical simple ulcer settles on its own in about 1 to 2 weeks. It is different from a cold sore: cold sores usually form as blisters on or around the lips and can spread to other people.",
    definition: "A mouth ulcer, often called a canker sore or aphthous ulcer, is a non-contagious sore in the lining of the mouth. A single simple ulcer is common; repeated, severe, or slow-healing ulcers need a broader assessment.",
    causes: ["Minor injury, such as biting the cheek or lip, a sharp tooth, braces, dentures, or a rough filling", "Emotional stress or hormonal changes", "Irritation from very hot, spicy, salty, acidic, or rough foods", "Some nutritional deficiencies, including iron, folate, or vitamin B12, especially with recurrent ulcers", "Less commonly, an underlying condition such as coeliac disease or inflammatory bowel disease, or a medicine-related reaction"],
    riskFactors: ["Previous recurrent mouth ulcers or a family tendency", "A sharp tooth, ill-fitting dental appliance, or repeated mouth trauma", "Stress or irritation from foods and oral-care products", "Conditions or medicines that affect immunity, nutrition, or the mouth lining"],
    symptoms: ["A round or oval painful white, yellow, or grey sore with a red border inside the mouth", "Stinging, burning, or soreness—especially when eating, drinking, brushing teeth, or talking", "One or more sores on the inside of the lips or cheeks, gums, tongue, or other mouth lining", "A mild tingling or burning feeling before the sore appears"],
    diagnosis: "A dentist or clinician can often identify a simple mouth ulcer from its location, appearance, and history. They may ask about recurrence, injuries, dental appliances, medicines, diet, fever, bowel symptoms, skin or genital ulcers, and other health conditions. Tests are rarely needed for a single typical ulcer.",
    differentialDiagnosis: "Cold sores (herpes) usually occur on or around the lips and are contagious, unlike typical mouth ulcers. Other possibilities include trauma, oral thrush, hand-foot-and-mouth disease, oral lichen planus, medication reactions, and less commonly a systemic illness or oral cancer. A persistent or unusual ulcer should be examined rather than self-diagnosed.",
    labTests: ["No test is usually needed for one typical, healing mouth ulcer", "A dentist or clinician may consider blood tests for iron, folate, vitamin B12, or other causes when ulcers are frequent, severe, or slow to heal", "A swab, biopsy, or other targeted tests may be considered for an atypical, persistent, or concerning lesion"],
    imaging: "Imaging is not usually part of evaluating a simple mouth ulcer. A persistent lesion may need examination and targeted testing decided by a dentist, oral-medicine clinician, or doctor.",
    redFlags: ["An ulcer lasting longer than 2 to 3 weeks, or one that keeps returning frequently", "An ulcer that is larger than usual, looks different, is near the back of the throat, bleeds, or becomes increasingly red and painful", "Difficulty drinking enough, uncontrolled pain, high fever, dehydration, or feeling very unwell", "A neck lump, unexplained weight loss, or a persistent red or white patch in the mouth", "Ulcers together with skin or genital sores, painful swollen joints, significant bowel symptoms, or immune suppression"],
    conventionalManagement: "Simple ulcers usually need time and pain relief rather than a quick cure. Avoiding irritants, using a soft toothbrush, and choosing cool or soft foods can make eating easier. A pharmacist, dentist, or clinician can advise on appropriate pain-relief gels, rinses, or other treatments; severe, infected, recurring, or persistent ulcers may need prescription treatment or assessment of a dental trigger or underlying cause.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for mouth ulcers. It must not replace dental or clinical assessment of an ulcer that persists, recurs frequently, prevents drinking, or has warning signs.",
    lifestyleAdvice: "Use a soft-bristled toothbrush and keep regular dental check-ups. Choose cool drinks and softer foods while the area is sore, and avoid very hot, spicy, salty, acidic, rough, or crunchy foods if they sting. Consider avoiding toothpaste containing sodium lauryl sulphate if it seems irritating. Arrange a dental review for a sharp tooth, rough filling, braces, or denture that repeatedly rubs the area, and keep a brief note of recurring triggers.",
    references: ["CIT-0113", "CIT-0114"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" }, reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" }, evidenceLevel: "Consensus-Guidance", tags: ["Mouth Ulcer", "Canker Sore", "Aphthous Ulcer", "Oral Health", "Cold Sore Difference"], canonicalUrl: "https://homeo.healthcare/knowledge/diseases/mouth-ulcers", readingTimeMinutes: 5, audience: "patient", license: "CC BY-NC-ND 4.0", changeLog: ["1.0.0: Added patient-first mouth-ulcer guide with cold-sore distinction and dental safety boundaries."], quickFacts: { "Usual location": "Inside the mouth", "Typical course": "Often heals in 1 to 2 weeks", "Contagious?": "Typical canker sores are not contagious", "Get advice": "If persistent, unusual, recurrent, or hard to drink with" },
  aiReadiness: { retrievalSummary: "Mouth ulcers, also called canker sores, are painful non-contagious sores inside the mouth that usually improve within 1 to 2 weeks. Persistent, unusual, recurrent, or severe ulcers need dental or clinical assessment.", clinicalSummary: "Assess duration, recurrence, exact location, trauma or dental irritants, systemic symptoms, nutrition, medicines, immune status, and features suggesting herpes, infection, inflammatory disease, or malignancy.", patientSummary: "A sore inside the mouth is often a mouth ulcer and may settle in 1 to 2 weeks. Use gentle care and avoid foods that sting, but arrange dental or clinical advice if it lasts 2 to 3 weeks, looks different, keeps returning, or makes drinking difficult.", studentSummary: "Recurrent aphthous ulcers are non-contagious lesions of oral mucosa. Differentiate from herpes by location and morphology; investigate recurrent, severe, non-healing, or systemically associated lesions for local trauma, deficiency, medication, immune, inflammatory, or malignant causes.", keywords: ["mouth ulcers", "canker sores", "aphthous ulcers", "painful sore inside mouth", "mouth ulcer not healing"], semanticKeywords: ["aphthous stomatitis", "cold sore difference", "oral ulcer red flags", "recurrent mouth ulcers", "mouth ulcer self care"], icd: "K12.0", bodySystem: "Oral Health", urgency: "routine" },
};
