import { KnowledgeEntity } from "../../types";

export const OnychomycosisFungalNailInfectionDisease: KnowledgeEntity = {
  id: "D0081",
  slug: "onychomycosis-fungal-nail-infection",
  entityType: "disease",
  editorialStatus: "published",
  reviewStatus: "owner-authorization-required",
  versionInfo: {
    version: "1.0.0",
    created: "2026-09-21T00:00:00Z",
    updated: "2026-09-21T00:00:00Z",
    reviewed: "2026-09-21T00:00:00Z",
  },
  title: {
    en: "Fungal Nail Infection (Onychomycosis): Thickened or Discoloured Nails",
    hi: "नाखून का फंगल संक्रमण: मोटे या बदरंग नाखून",
    gu: "નખનો ફંગલ ચેપ: જાડા અથવા રંગ બદલાયેલા નખ",
    mr: "नखांचा बुरशीजन्य संसर्ग: जाड किंवा रंग बदललेले नख",
    es: "Infección Fúngica de las Uñas: Uñas Engrosadas o Descoloridas",
    ar: "فطريات الأظافر: أظافر سميكة أو متغيرة اللون",
  },
  summary: {
    en: "A fungal nail infection can make one or more nails thicker, yellow-white or brown, brittle, crumbly, or separated from the nail bed. It is common in toenails and can look like several non-fungal nail conditions.",
    hi: "नाखून के फंगल संक्रमण में एक या अधिक नाखून मोटे, पीले-सफेद या भूरे, भंगुर या टूटने वाले दिख सकते हैं।",
    gu: "નખના ફંગલ ચેપમાં એક અથવા વધુ નખ જાડા, પીળા-સફેદ અથવા ભૂરા, બરડ અથવા ક્ષીણ દેખાઈ શકે છે.",
    mr: "नखांच्या बुरशीजन्य संसर्गात एक किंवा अधिक नखे जाड, पिवळट-पांढरी किंवा तपकिरी, ठिसूळ किंवा भुसभुशीत दिसू शकतात.",
    es: "Una infección fúngica puede volver una o más uñas más gruesas, amarillas, blanquecinas o marrones, frágiles o quebradizas.",
    ar: "قد تجعل فطريات الأظافر ظفرًا واحدًا أو أكثر أكثر سماكة أو أصفر أو أبيض أو بنيًا وهشًا أو متفتتًا.",
  },
  content: {
    overview: "Fungal nail infection, also called onychomycosis, is a common infection that usually affects toenails. A nail may slowly become thicker, discoloured, brittle, crumbly, or lift from the skin beneath it. It can occur alongside athlete’s foot, but injury, psoriasis, eczema, ageing, and other nail conditions can look similar—so a changing nail is worth checking rather than self-diagnosing.",
    definition: "An infection involving the nail plate or nail bed, often caused by fungi. Toenails are affected more often than fingernails because shoes can keep feet warm and moist and toenails grow slowly.",
    causes: [
      "Fungi entering through small breaks around or beneath a nail, or spreading from athlete’s foot",
      "Warm, damp footwear and repeated exposure to shared wet floors such as changing rooms or pool areas",
      "Nail injury, a separated nail, or repeated pressure from ill-fitting footwear",
    ],
    riskFactors: [
      "Athlete’s foot, sweaty feet, tight or non-breathable footwear, or frequent exposure to damp shared areas",
      "Older age, slower nail growth, previous nail infection, or a history of nail trauma",
      "Diabetes, poor circulation, numbness, psoriasis, or reduced immune defenses—these make a new foot or nail problem more important to assess promptly",
    ],
    symptoms: [
      "A nail that becomes thicker, yellow, white, brown, or cloudy; colour changes can look different across skin tones",
      "Brittle, crumbly, rough, or distorted nail edges, sometimes with debris beneath the nail",
      "The nail lifting away from the nail bed, tenderness from shoe pressure, or difficulty trimming the nail",
    ],
    diagnosis: "A clinician or dermatologist will examine the affected nails and surrounding skin. Because several conditions can mimic fungal infection, they may take a small nail clipping or scraping for microscopy or laboratory testing before recommending a treatment plan—especially if an oral medicine may be considered.",
    differentialDiagnosis: "Nail trauma, psoriasis, eczema, bacterial nail infection, nail separation from other causes, age-related thickening, and a dark pigment change can resemble fungal nail infection.",
    labTests: ["A nail clipping or scraping may be examined under a microscope or sent for fungal testing to confirm the cause."],
    imaging: "Imaging is not usually needed for a straightforward fungal nail infection.",
    redFlags: [
      "Increasing pain, redness, warmth, swelling, pus, fever, or an open sore around the nail or foot",
      "Diabetes, poor circulation, numbness, or reduced immune defenses with a new nail or skin problem",
      "A new dark brown or black streak, pigment spreading onto nearby skin, bleeding, rapid change, or a nail that changes without an obvious reason",
    ],
    conventionalManagement: "A pharmacist, podiatrist, dermatologist, or other clinician can help confirm whether a nail is fungal and advise on treatment. The right approach depends on how many nails are involved, how much of each nail is affected, other medicines and health conditions, and whether testing confirms fungus. Nails grow slowly, so visible improvement can take months even when treatment is working. Do not share or start prescription treatments based only on a photo or an assumption.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for fungal nail infection. It should not replace confirmed diagnosis, antifungal care, or timely assessment of painful, infected, rapidly changing, or high-risk foot and nail problems.",
    lifestyleAdvice: "Wash and dry feet carefully, including between toes; change socks after sweating; choose breathable shoes; alternate and air footwear; and wear sandals in shared showers or changing rooms. Do not share shoes, socks, towels, or nail tools. Keep nails trimmed straight across if you can do so safely, but seek professional foot care if nails are very thick, painful, difficult to cut, or you have diabetes, poor circulation, or numbness.",
    references: ["CIT-0087", "CIT-0088", "CIT-0083"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" },
  reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" },
  evidenceLevel: "Consensus-Guidance",
  tags: ["Fungal Nail Infection", "Onychomycosis", "Nail Fungus", "Thick Toenail", "Dermatology"],
  canonicalUrl: "https://homeo.healthcare/knowledge/diseases/onychomycosis-fungal-nail-infection",
  readingTimeMinutes: 4,
  audience: "patient",
  license: "CC BY-NC-ND 4.0",
  changeLog: ["1.0.0: Added patient-first fungal nail infection guide with diagnostic boundaries, prevention, and safety advice."],
  quickFacts: { "Usually affects": "Toenails more often than fingernails", "Common signs": "Thickening, colour change, brittleness, or crumbling", "How it is confirmed": "A clinician may test a nail clipping or scraping", "Important to know": "Nails grow slowly, so visible recovery can take months" },
  aiReadiness: {
    retrievalSummary: "Fungal nail infection, or onychomycosis, can cause a toenail or fingernail to become thicker, discoloured, brittle, crumbly, or lifted. It needs confirmation because non-fungal nail conditions can look similar.",
    clinicalSummary: "Consider microscopy or laboratory testing when the diagnosis is unclear, multiple nails are involved, treatment fails, or systemic treatment could be considered. Assess urgently for bacterial infection, ulceration, concerning pigment change, diabetes, circulation problems, or immunosuppression.",
    patientSummary: "A fungal nail infection often causes thick, discoloured or crumbly nails. Ask a clinician, podiatrist, or pharmacist for advice rather than treating an uncertain nail yourself; recovery is slow because nails grow slowly.",
    studentSummary: "Onychomycosis is an infection of the nail plate or bed, commonly affecting toenails. Confirm suspected cases with an appropriate nail specimen when possible and distinguish fungal infection from trauma, inflammatory nail disease, and pigment disorders.",
    keywords: ["nail fungus", "fungal nail infection", "onychomycosis", "yellow toenail", "thick toenail", "crumbly toenail"],
    semanticKeywords: ["dermatophyte nail infection", "nail plate infection", "nail clipping microscopy"],
    icd: "B35.1",
    bodySystem: "Dermatology & Integumentary",
    urgency: "monitor",
  },
};
