import { KnowledgeEntity } from "../../types";

export const PlantarWartsVerrucasDisease: KnowledgeEntity = {
  id: "D0082",
  slug: "plantar-warts-verrucas",
  entityType: "disease",
  editorialStatus: "published",
  reviewStatus: "owner-authorization-required",
  versionInfo: {
    version: "1.0.0",
    created: "2026-09-21T00:00:00Z",
    updated: "2026-09-21T00:00:00Z",
    reviewed: "2026-09-21T00:00:00Z",
  },
  title: {
    en: "Plantar Warts (Verrucas): A Rough, Tender Spot on the Sole",
    hi: "प्लांटर वॉर्ट्स (वेरुका): तलवे पर खुरदरा, दर्द वाला दाग",
    gu: "પ્લાન્ટર વૉર્ટ્સ (વેરુકા): પગના તળિયા પર ખરબચડો, સંવેદનશીલ દાગ",
    mr: "प्लांटर वॉर्ट्स (वेरुका): तळव्यावर खडबडीत, दुखरा डाग",
    es: "Verrugas Plantares: Un Punto Áspero y Sensible en la Planta del Pie",
    ar: "الثآليل الأخمصية: بقعة خشنة ومؤلمة في باطن القدم",
  },
  summary: {
    en: "A plantar wart, also called a verruca, is a common skin growth caused by a virus. It can look like a small rough area on the sole and may hurt when body weight presses on it.",
    hi: "प्लांटर वॉर्ट या वेरुका वायरस के कारण होने वाली आम त्वचा वृद्धि है। यह तलवे पर छोटे खुरदरे हिस्से जैसा दिख सकता है।",
    gu: "પ્લાન્ટર વૉર્ટ અથવા વેરુકા વાયરસથી થતી સામાન્ય ત્વચાની વૃદ્ધિ છે. તે પગના તળિયા પર નાના ખરબચડા વિસ્તાર જેવું દેખાઈ શકે છે.",
    mr: "प्लांटर वॉर्ट किंवा वेरुका ही विषाणूमुळे होणारी सामान्य त्वचेची वाढ आहे. ती तळव्यावर लहान खडबडीत भागासारखी दिसू शकते.",
    es: "Una verruga plantar es un crecimiento común de la piel causado por un virus. Puede parecer una pequeña zona áspera en la planta del pie.",
    ar: "الثؤلول الأخمصي أو الفيروكا نمو جلدي شائع يسببه فيروس وقد يبدو كمنطقة صغيرة خشنة في باطن القدم.",
  },
  content: {
    overview: "A plantar wart, often called a verruca, is a non-cancerous skin growth caused by a type of human papillomavirus (HPV). On the sole of the foot, pressure from standing and walking can push it inward, where it may look like a rough, thickened spot and feel tender. It is different from a corn or callus, which are usually caused by repeated friction or pressure rather than a virus.",
    definition: "A wart caused by HPV on the sole of the foot. Warts can be passed through direct skin contact or from surfaces and objects that have contacted a wart, although transmission is not inevitable.",
    causes: [
      "HPV entering the outer skin through a tiny break, softened skin, or irritation",
      "Contact with a wart on another person, or with surfaces or items that have contacted a wart",
      "Pressure on the sole causing the growth to be pushed inward and covered by hard skin",
    ],
    riskFactors: [
      "Walking barefoot in shared changing rooms, showers, or pool areas",
      "Small cuts, skin irritation, or softened feet after prolonged moisture exposure",
      "A weakened immune system, which can make warts more persistent or numerous",
    ],
    symptoms: [
      "A small rough, grainy, or thickened area on the sole, heel, or near the toes",
      "A tiny cluster of dark dots or disrupted skin lines within the rough area; these signs are not always visible",
      "Tenderness or pain when standing, walking, or squeezing the area from the sides; some plantar warts do not hurt",
    ],
    diagnosis: "A clinician, dermatologist, or podiatrist can often recognise a plantar wart by looking at the area and comparing it with a corn, callus, or other skin condition. If a growth is uncertain, changing, growing rapidly, looks like an open sore, or does not clear as expected, a dermatologist may need to assess it more closely and occasionally take a small sample.",
    differentialDiagnosis: "Corns, calluses, a foreign body, eczema, psoriasis, fungal foot problems, and less commonly other skin growths can resemble a plantar wart. A painful or changing spot should not be assumed to be a wart.",
    labTests: ["Tests are not usually needed; a clinician may consider a skin sample when the diagnosis is unclear or the lesion has concerning features."],
    imaging: "Imaging is not used for a typical plantar wart.",
    redFlags: [
      "A spot that is bleeding, ulcerated, rapidly growing, very painful, changing colour, or looks unlike a typical rough wart",
      "Diabetes, poor circulation, numbness, foot ulcer risk, or reduced immune defenses with a new sole lesion",
      "Uncertain diagnosis, many spreading warts, or no improvement after appropriate pharmacist or clinician advice",
    ],
    conventionalManagement: "Many warts are harmless and can clear on their own, but this may take months or longer. If a plantar wart is painful, spreading, affecting activity, or bothersome, a pharmacist or clinician can advise on suitable treatment. Common approaches include carefully selected topical treatments or in-clinic procedures such as freezing; the right option depends on the lesion, skin, age, comfort, health conditions, and diagnosis. Do not cut, burn, or pick a sole lesion yourself, and do not use strong over-the-counter treatments without professional advice if you have diabetes, poor circulation, numbness, or an uncertain diagnosis.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for plantar warts. It should not replace assessment of a changing, painful, bleeding, uncertain, or high-risk foot lesion.",
    lifestyleAdvice: "Do not pick, cut, or shave a wart. Wash hands after touching it, keep it covered when practical, and avoid sharing socks, shoes, towels, nail tools, or pumice stones. Wear sandals in shared showers and changing rooms. A clinician or pharmacist can help you choose safe care and prevent irritation of the surrounding healthy skin.",
    references: ["CIT-0089", "CIT-0090"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" },
  reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" },
  evidenceLevel: "Consensus-Guidance",
  tags: ["Plantar Wart", "Verruca", "Foot Wart", "Painful Sole", "Dermatology"],
  canonicalUrl: "https://homeo.healthcare/knowledge/diseases/plantar-warts-verrucas",
  readingTimeMinutes: 4,
  audience: "patient",
  license: "CC BY-NC-ND 4.0",
  changeLog: ["1.0.0: Added patient-first plantar wart guide with corn/callus differentiation and safe-treatment boundaries."],
  quickFacts: { "Cause": "A common virus affecting the outer skin", "Often appears on": "The sole, heel, or near the toes", "Why it may hurt": "Walking pressure can push it inward", "Important to know": "A corn or callus can look similar, so an uncertain lesion needs assessment" },
  aiReadiness: {
    retrievalSummary: "A plantar wart, or verruca, is a common HPV-related growth on the sole. It can look like a rough thickened spot and become tender under body weight; it can be confused with a corn or callus.",
    clinicalSummary: "Examine for disrupted skin lines, punctate dots, pressure-related tenderness, and mimics such as corn, callus, foreign body, inflammatory dermatoses, or other growths. Escalate for diagnostic uncertainty, concerning change, diabetes, neuropathy, poor circulation, immunosuppression, ulceration, or infection.",
    patientSummary: "A plantar wart is a common viral growth on the sole. It may settle with time, but ask a pharmacist, podiatrist, or clinician for advice if it hurts, spreads, changes, or you are unsure that it is a wart.",
    studentSummary: "Verruca plantaris is an HPV-associated epidermal growth on a weight-bearing sole that can be driven inward by pressure. Distinguish it from corns and calluses, and avoid destructive self-treatment in people with diabetes, vascular disease, neuropathy, or an uncertain lesion.",
    keywords: ["plantar wart", "verruca", "foot wart", "wart on sole", "painful sole spot", "wart vs corn"],
    semanticKeywords: ["human papillomavirus", "verruca plantaris", "hyperkeratotic sole lesion"],
    icd: "B07.0",
    bodySystem: "Dermatology & Integumentary",
    urgency: "monitor",
  },
};
