import { KnowledgeEntity } from "../../types";

export const RingwormTineaCorporisDisease: KnowledgeEntity = {
  id: "D0077",
  slug: "ringworm-tinea-corporis",
  entityType: "disease",
  editorialStatus: "published",
  reviewStatus: "owner-authorization-required",
  versionInfo: {
    version: "1.1.0",
    created: "2026-09-21T00:00:00Z",
    updated: "2026-09-24T00:00:00Z",
    reviewed: "2026-09-21T00:00:00Z",
  },
  title: {
    en: "Ringworm",
    hi: "दाद / रिंगवर्म: गोल, खुजलीदार फंगल रैश",
    gu: "દાદ / રિંગવર્મ: ગોળાકાર ખંજવાળવાળો ફંગલ ચકામો",
    mr: "दाद / रिंगवर्म: गोलाकार खाज येणारा फंगल पुरळ",
    es: "Tiña Corporal: Erupción Circular con Picor",
    ar: "السعفة الجلدية: طفح دائري مثير للحكة",
  },
  summary: {
    en: "Ringworm is a common fungal skin infection, not a worm. It often causes an itchy ring-shaped rash and can spread between people, animals, and shared items.",
    hi: "रिंगवर्म या दाद एक आम फंगल त्वचा संक्रमण है, कीड़ा नहीं। यह खुजली वाला गोल रैश बना सकता है और फैल सकता है।",
    gu: "રિંગવર્મ એક સામાન્ય ફંગલ ત્વચા ચેપ છે, કીડો નથી. તેમાં ખંજવાળવાળો ગોળ ચકામો થઈ શકે છે અને તે ફેલાઈ શકે છે.",
    mr: "रिंगवर्म हा कृमी नसून सामान्य बुरशीजन्य त्वचा संसर्ग आहे. त्यात गोलाकार खाज येणारा पुरळ दिसू शकतो आणि तो पसरू शकतो.",
    es: "La tiña es una infección fúngica común, no un gusano. Puede causar una erupción circular con picor y propagarse.",
    ar: "السعفة عدوى فطرية شائعة وليست دودة. قد تسبب طفحًا دائريًا مثيرًا للحكة ويمكن أن تنتشر.",
  },
  content: {
    overview: "Ringworm of the body, also called tinea corporis, is a fungal skin infection. It often appears as an itchy, ring-shaped patch that may slowly enlarge. It can spread through close contact, shared personal items, and contact with infected animals.",
    definition: "A superficial fungal infection of the skin caused by dermatophytes; despite the name, it is not caused by a worm.",
    causes: [
      "Dermatophyte fungi that infect the outer layer of skin",
      "Contact with an infected person, pet, or contaminated towels, clothing, sports equipment, or surfaces",
      "Warm, damp environments that make it easier for fungi to grow",
    ],
    riskFactors: [
      "Close-contact sport, shared changing facilities, or sharing towels and personal items",
      "Excess sweating, damp clothing, or skin that stays moist",
      "Close contact with an infected pet or person; weakened immune defenses can increase risk of persistent infection",
    ],
    symptoms: [
      "An itchy, round or ring-shaped patch that may be slightly raised or scaly",
      "A clearer or scaly centre with a more active edge; on darker skin it may look red-purple, brown, grey, or black",
      "More than one patch or gradual enlargement without appropriate treatment",
    ],
    diagnosis: "A clinician may diagnose ringworm from the appearance and use a skin scraping or other testing when the diagnosis is uncertain, the rash is widespread, or it has not improved as expected.",
    differentialDiagnosis: "Eczema, psoriasis, pityriasis rosea, contact dermatitis, granuloma annulare, and other fungal infections can mimic ringworm. Do not assume every circular rash is fungal.",
    labTests: ["Skin scraping with microscopy or fungal testing may be used when the diagnosis is uncertain or treatment has not worked."],
    imaging: "Imaging is not used for uncomplicated ringworm.",
    redFlags: [
      "Rapid spread, severe pain, pus, fever, or increasing warmth and swelling",
      "Scalp involvement with hair loss, a rash near the eyes, or extensive skin involvement",
      "A widespread, recurrent, or treatment-resistant rash, especially with weakened immunity",
    ],
    conventionalManagement: "Treatment depends on the body site and severity. A pharmacist or clinician can advise on an appropriate antifungal treatment and how long to use it. Scalp, nail, extensive, or recurrent infection may need medical assessment and prescription treatment.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for fungal skin infection. It should not replace antifungal care or delay assessment of a spreading, severe, or persistent rash.",
    lifestyleAdvice: "Keep the area clean and dry, change sweaty clothing promptly, do not share towels or clothing, wash hands after touching pets, and arrange veterinary care for a pet with suspected ringworm. Avoid close skin contact until a clinician or pharmacist has advised on management.",
    references: ["CIT-0082", "CIT-0023", "CIT-0024"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" },
  reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" },
  evidenceLevel: "Consensus-Guidance",
  tags: ["Ringworm", "Tinea Corporis", "Fungal Skin Infection", "Itchy Ring Rash", "Dermatology"],
  canonicalUrl: "https://homeo.healthcare/knowledge/diseases/ringworm-tinea-corporis",
  readingTimeMinutes: 4,
  audience: "patient",
  license: "CC BY-NC-ND 4.0",
  changeLog: ["1.0.0: Added patient-first ringworm guide with spread-prevention and treatment boundaries.", "1.1.0: Simplified the title and added focused condition and symptom connections."],
  quickFacts: { "Cause": "A fungal infection, not a worm", "Can it spread?": "Yes — through contact, shared items, and infected animals", "Common look": "An itchy ring-shaped patch", "When to seek advice": "If it spreads, affects scalp or nails, or does not improve" },
  aiReadiness: {
    retrievalSummary: "Ringworm, or tinea corporis, is a contagious fungal skin infection that often causes an itchy ring-shaped rash and needs antifungal assessment or treatment.",
    clinicalSummary: "Consider microscopy or fungal testing when the diagnosis is unclear, disease is extensive, or first treatment fails; distinguish from inflammatory and non-fungal annular rashes.",
    patientSummary: "Ringworm is a fungal infection, not a worm. Keep the area dry, avoid sharing personal items, and get advice about the right antifungal treatment.",
    studentSummary: "Tinea corporis commonly presents as an annular, pruritic, scaly lesion with active border; assess site, extent, source, and mimics before treating.",
    keywords: ["ringworm", "tinea corporis", "fungal rash", "circular rash", "itchy ring rash", "dad fungal rash"],
    semanticKeywords: ["dermatophyte", "annular rash", "fungal skin infection"],
    icd: "B35.4",
    bodySystem: "Dermatology & Integumentary",
    urgency: "monitor",
  },
};
