import { KnowledgeEntity } from "../../types";

export const ScabiesDisease: KnowledgeEntity = {
  id: "D0083",
  slug: "scabies",
  entityType: "disease",
  editorialStatus: "published",
  reviewStatus: "owner-authorization-required",
  versionInfo: {
    version: "1.0.0",
    created: "2026-09-21T00:00:00Z",
    updated: "2026-09-21T00:00:00Z",
    reviewed: "2026-09-21T00:00:00Z",
  },
  title: {
    en: "Scabies",
    hi: "स्केबीज़: तेज खुजली और फैलता हुआ रैश",
    gu: "સ્કેબીઝ: તીવ્ર ખંજવાળ અને ફેલાતો ચકામો",
    mr: "स्केबीज: तीव्र खाज आणि पसरणारा पुरळ",
    es: "Sarna: Picor Intenso y una Erupción que se Extiende",
    ar: "الجرب: حكة شديدة وطفح جلدي منتشر",
  },
  summary: {
    en: "Scabies is a contagious itchy skin infestation caused by a tiny human itch mite. It often causes intense night-time itching and a bumpy rash, especially around finger webs, wrists, waist, or groin.",
    hi: "स्केबीज़ एक संक्रामक खुजली वाली त्वचा समस्या है जो बहुत छोटे मानव खुजली माइट से होती है। इसमें रात में तेज खुजली और दाने हो सकते हैं।",
    gu: "સ્કેબીઝ નાનકડા માનવ ઇચ માઇટથી થતી ચેપી, ખંજવાળવાળી ત્વચાની સમસ્યા છે. તેમાં રાત્રે તીવ્ર ખંજવાળ અને દાણા થઈ શકે છે.",
    mr: "स्केबीज ही लहान मानवी खाज माइटमुळे होणारी संसर्गजन्य, खाज येणारी त्वचेची समस्या आहे. यात रात्री तीव्र खाज आणि पुरळ येऊ शकतो.",
    es: "La sarna es una infestación contagiosa y con picor causada por un diminuto ácaro humano. Suele provocar picor intenso por la noche y una erupción con granitos.",
    ar: "الجرب إصابة جلدية معدية ومسببة للحكة يسببها عث صغير خاص بالبشر. وغالبًا ما يسبب حكة شديدة ليلًا وطفحًا حبيبيًا.",
  },
  content: {
    overview: "Scabies is caused by a tiny human itch mite that lives in the outer layer of skin. It can cause intense itching—often worse at night—and small bumps or thin burrow-like lines. It spreads mainly through prolonged skin-to-skin contact and sometimes through shared bedding, clothing, or towels. Anyone can get scabies; it is not a sign of poor hygiene.",
    definition: "A contagious skin infestation caused by the human itch mite, Sarcoptes scabiei var. hominis. Human scabies is different from mange in pets; pets do not sustain or reproduce the human scabies mite.",
    causes: [
      "A reaction to the human itch mite and its products in the outer skin layer",
      "Prolonged close skin-to-skin contact with an affected person, including household or sexual contact",
      "Less commonly, sharing bedding, towels, or clothing used next to the skin by an affected person",
    ],
    riskFactors: [
      "Living, sleeping, or having prolonged close contact with someone who has untreated scabies",
      "Crowded settings where close personal contact is common, such as households, childcare, hostels, or care settings",
      "Reduced immune defenses or difficulty scratching, which can be associated with a more severe crusted form needing urgent clinical care",
    ],
    symptoms: [
      "Intense itch, often worse at night; itching may be difficult to notice on some people at first",
      "Small bumps, scratch marks, or thin curved burrow-like lines, commonly around finger webs, wrists, elbows, waist, buttocks, genitals, or under jewellery and watch straps",
      "On brown or black skin, redness can be harder to see; feel for raised areas and notice itch, texture change, or scratch marks instead",
    ],
    diagnosis: "A clinician can often diagnose scabies from the itch pattern, rash distribution, burrows, and whether close contacts are affected. They may use magnification or take a skin scraping when the diagnosis is uncertain. Eczema, hives, contact dermatitis, fungal infections, bedbug bites, and medicine reactions can look similar.",
    differentialDiagnosis: "Eczema, allergic or irritant contact dermatitis, hives, insect bites, fungal infection, bedbugs, psoriasis, and medicine reactions can cause an itchy rash and may need different care.",
    labTests: ["A skin scraping or examination under magnification may be used when the diagnosis is uncertain."],
    imaging: "Imaging is not used for scabies.",
    redFlags: [
      "Fever, increasing pain, warmth, swelling, pus, honey-coloured crusting, or open sores suggesting a secondary skin infection",
      "A widespread thick crusted or flaky rash, especially in an older adult, someone with reduced immunity, reduced sensation, or difficulty scratching",
      "An infant, pregnancy or breastfeeding, or persistent new burrows or rash after a complete clinician- or pharmacist-guided treatment plan",
    ],
    conventionalManagement: "Scabies needs a clinician- or pharmacist-guided treatment plan that is suitable for the person’s age, pregnancy status, skin condition, and local medicine availability. The key step is coordinated treatment: household members and other close contacts may need treatment at the same time, even if they do not yet itch, to prevent re-exposure. Follow the exact product instructions, clean recently used clothing, towels, and bedding as advised, and ask before treating very young children or people with complex health needs. Itching can continue for several weeks after successful treatment; new burrows or fresh bumps, however, deserve reassessment.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for scabies. It should not replace effective anti-scabies treatment, coordinated contact care, or prompt assessment of infection, crusted rash, or an uncertain diagnosis.",
    lifestyleAdvice: "Avoid prolonged skin-to-skin contact and avoid sharing bedding, clothing, towels, or personal items until the advised treatment course is complete. Wash recently used linens and clothes as directed; seal items that cannot be washed for the recommended period. Keep nails short to reduce skin injury from scratching, and let close household and relevant intimate contacts know so they can obtain timely advice without blame or stigma.",
    references: ["CIT-0091", "CIT-0092"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" },
  reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" },
  evidenceLevel: "Consensus-Guidance",
  tags: ["Scabies", "Night Itching", "Itchy Rash", "Skin Mites", "Dermatology"],
  canonicalUrl: "https://homeo.healthcare/knowledge/diseases/scabies",
  readingTimeMinutes: 5,
  audience: "patient",
  license: "CC BY-NC-ND 4.0",
  changeLog: ["1.0.0: Added patient-first scabies guide with contact coordination, stigma-free prevention, and safety boundaries."],
  quickFacts: { "Cause": "A tiny human itch mite in the outer skin", "Typical clue": "Intense itching, often worse at night", "How it spreads": "Usually prolonged close skin contact", "Important to know": "It is not caused by poor hygiene; close contacts may need coordinated treatment" },
  aiReadiness: {
    retrievalSummary: "Scabies is a contagious infestation caused by the human itch mite. It often causes severe night-time itch and small bumps or burrows around finger webs, wrists, waist, or groin and needs coordinated care for close contacts.",
    clinicalSummary: "Assess distribution, nocturnal pruritus, burrows, close-contact history, and secondary infection. Treat confirmed cases and appropriate close contacts together; identify crusted scabies and vulnerable people promptly. Persistent itch after therapy may be post-scabetic, but new burrows or new lesions need reassessment.",
    patientSummary: "Scabies is a treatable contagious itch caused by a tiny human mite, not poor hygiene. Get pharmacist or clinician advice, tell close contacts, and follow the plan together so reinfection is less likely.",
    studentSummary: "Sarcoptes scabiei var. hominis causes a hypersensitivity-driven pruritic eruption, often with nocturnal itch and characteristic distribution. Contact management, environmental measures, and identification of crusted scabies are central to control.",
    keywords: ["scabies", "night itching", "itching between fingers", "itchy rash at night", "scabies treatment", "skin mites"],
    semanticKeywords: ["Sarcoptes scabiei", "scabetic burrow", "post-scabetic pruritus", "crusted scabies"],
    icd: "B86",
    bodySystem: "Dermatology & Integumentary",
    urgency: "monitor",
  },
};
