import { KnowledgeEntity } from "../../types";

export const TineaVersicolorDisease: KnowledgeEntity = {
  id: "D0080",
  slug: "tinea-versicolor",
  entityType: "disease",
  editorialStatus: "published",
  reviewStatus: "owner-authorization-required",
  versionInfo: {
    version: "1.0.0",
    created: "2026-09-21T00:00:00Z",
    updated: "2026-09-21T00:00:00Z",
    reviewed: "2026-09-21T00:00:00Z",
  },
  title: {
    en: "Tinea Versicolor: Patchy Skin Colour Changes on the Chest or Back",
    hi: "टीनिया वर्सीकलर: छाती या पीठ पर त्वचा के रंग में धब्बेदार बदलाव",
    gu: "ટિનિયા વર્સીકલર: છાતી અથવા પીઠ પર ત્વચાના રંગમાં ચકામાવાળા ફેરફાર",
    mr: "टिनिया वर्सिकलर: छाती किंवा पाठीवरील त्वचेच्या रंगातील चट्टेदार बदल",
    es: "Tiña Versicolor: Cambios Manchados de Color en Pecho o Espalda",
    ar: "النخالية المبرقشة: تغيرات مبقعة في لون جلد الصدر أو الظهر",
  },
  summary: {
    en: "Tinea versicolor is a common yeast-related skin condition that can cause lighter, darker, or pink-brown patches with fine scale, often on the chest, back, upper arms, or neck.",
    hi: "टीनिया वर्सीकलर एक आम यीस्ट-संबंधित त्वचा समस्या है। इसमें छाती, पीठ, ऊपरी बांह या गर्दन पर हल्के, गहरे या गुलाबी-भूरे पैच हो सकते हैं।",
    gu: "ટિનિયા વર્સીકલર સામાન્ય યીસ્ટ-સંબંધિત ત્વચાની સ્થિતિ છે. તેમાં છાતી, પીઠ, ઉપરના હાથ અથવા ગરદન પર હળવા, ઘેરા અથવા ગુલાબી-ભૂરા ચકામા થઈ શકે છે.",
    mr: "टिनिया वर्सिकलर ही सामान्य यीस्ट-संबंधित त्वचेची स्थिती आहे. छाती, पाठ, वरच्या बाहू किंवा मानेवर फिकट, गडद किंवा गुलाबी-तपकिरी चट्टे दिसू शकतात.",
    es: "La tiña versicolor es una afección cutánea común relacionada con levaduras que puede causar parches más claros, oscuros o rosado-marrones con descamación fina.",
    ar: "النخالية المبرقشة حالة جلدية شائعة مرتبطة بالخمائر وقد تسبب بقعًا أفتح أو أغمق أو بنية وردية مع قشور دقيقة.",
  },
  content: {
    overview: "Tinea versicolor, also called pityriasis versicolor, happens when a yeast that normally lives on the skin grows more than usual. It often causes flat, finely scaly areas that look lighter, darker, pink, or brown than surrounding skin. It commonly affects the chest, upper back, neck, or upper arms and may be more noticeable after sun exposure.",
    definition: "A common superficial yeast-related skin condition, usually involving Malassezia on the outer skin layer. It is different from dermatophyte ringworm and does not spread from person to person.",
    causes: [
      "Overgrowth of yeast that normally lives on the skin",
      "Warm, humid weather and sweating, which can support yeast overgrowth",
      "Individual skin and climate factors; it is not caused by poor hygiene",
    ],
    riskFactors: [
      "Living in or visiting a warm, humid climate",
      "Sweating often or wearing clothing that stays damp after exercise",
      "Previous tinea versicolor, because it can recur during warm or humid seasons",
    ],
    symptoms: [
      "Flat patches that are lighter, darker, pink, red, or brown than the surrounding skin; colours can look different across skin tones",
      "Fine scale that may be easier to notice when the skin is gently scratched or stretched",
      "Mild itch in some people, especially in warm or humid weather; patches often occur on the chest, upper back, upper arms, neck, or abdomen",
    ],
    diagnosis: "A dermatologist can often identify tinea versicolor by examining the skin. If uncertain, they may examine a skin scraping under a microscope or use a Wood’s lamp. Assessment is important because vitiligo, psoriasis, eczema, post-inflammatory colour change, and other conditions can look similar.",
    differentialDiagnosis: "Vitiligo, psoriasis, eczema, pityriasis rosea, post-inflammatory pigment change, and other causes of patchy skin colour or scale can be mistaken for tinea versicolor.",
    labTests: ["A skin scraping examined under a microscope may be used when the diagnosis is uncertain."],
    imaging: "Imaging is not used for tinea versicolor.",
    redFlags: [
      "Rapidly changing, painful, blistering, bleeding, or ulcerated skin areas",
      "Fever, spreading warmth or swelling, pus, or significant skin tenderness",
      "A new or uncertain colour change, widespread rash, or no improvement after appropriate pharmacist or clinician advice",
    ],
    conventionalManagement: "A pharmacist or clinician can advise whether an antifungal shampoo, wash, cream, or other treatment is suitable. For larger, thick, or repeatedly recurring areas, a dermatologist may recommend prescription treatment. Even after the yeast is controlled, skin colour may take weeks or months to return to its usual appearance.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for tinea versicolor. It should not replace antifungal care or delay assessment of an uncertain, persistent, painful, or changing skin condition.",
    lifestyleAdvice: "Shower and change out of sweaty clothing after exercise, keep clothing and towels clean and dry, and use breathable fabrics in hot weather. Recurrence is common in warm or humid conditions, so ask a clinician whether a preventive medicated cleanser is appropriate for you. Avoid trying to self-diagnose patchy colour changes.",
    references: ["CIT-0085", "CIT-0086"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" },
  reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" },
  evidenceLevel: "Consensus-Guidance",
  tags: ["Tinea Versicolor", "Pityriasis Versicolor", "Patchy Skin Colour", "Upper Back Rash", "Dermatology"],
  canonicalUrl: "https://homeo.healthcare/knowledge/diseases/tinea-versicolor",
  readingTimeMinutes: 4,
  audience: "patient",
  license: "CC BY-NC-ND 4.0",
  changeLog: ["1.0.0: Added patient-first tinea versicolor guide with diagnostic boundaries and recurrence guidance."],
  quickFacts: { "Cause": "An overgrowth of yeast that normally lives on skin", "Can it spread?": "No — it does not spread person to person", "Often appears on": "Chest, upper back, neck, or upper arms", "Important to know": "Skin colour may recover slowly even after treatment works" },
  aiReadiness: {
    retrievalSummary: "Tinea versicolor is a common yeast-related skin condition that causes patchy colour changes and fine scale, usually on the chest, back, upper arms, or neck; it is not contagious.",
    clinicalSummary: "Confirm the diagnosis when uncertain; consider microscopy or Wood’s lamp and distinguish it from vitiligo, inflammatory dermatoses, and post-inflammatory pigment changes. Recurrence is common in warm, humid environments.",
    patientSummary: "Tinea versicolor is a common, non-contagious yeast-related skin condition. A pharmacist or clinician can advise on antifungal treatment, and skin colour may take time to return after treatment.",
    studentSummary: "Pityriasis versicolor is a superficial Malassezia-associated condition with variably pigmented, finely scaly patches on the upper trunk; it is not a dermatophyte infection and often recurs in warm, humid climates.",
    keywords: ["tinea versicolor", "pityriasis versicolor", "white patches on back", "patchy skin colour", "discoloured skin patches"],
    semanticKeywords: ["Malassezia", "superficial yeast overgrowth", "pigmentary skin change"],
    icd: "B36.0",
    bodySystem: "Dermatology & Integumentary",
    urgency: "monitor",
  },
};
