import { KnowledgeEntity } from "../../types";

export const ToothacheDisease: KnowledgeEntity = {
  id: "D0095", slug: "toothache", entityType: "disease", editorialStatus: "published", reviewStatus: "owner-authorization-required",
  versionInfo: { version: "1.1.0", created: "2026-09-22T00:00:00Z", updated: "2026-09-24T00:00:00Z", reviewed: "2026-09-22T00:00:00Z" },
  title: { en: "Toothache", hi: "दांत दर्द: संभावित कारण और दंत चिकित्सक से कब मिलें", gu: "દાંતનો દુખાવો: કારણો અને દંતચિકિત્સકને ક્યારે મળવું", mr: "दातदुखी: कारणे आणि दंतचिकित्सकांना कधी भेटावे", es: "Dolor de Muelas: Posibles Causas y Cuándo Ver al Dentista", ar: "ألم الأسنان: أسبابه المحتملة ومتى تزور طبيب الأسنان" },
  summary: { en: "Toothache can come from tooth decay, a cracked tooth, gum disease, a loose filling, sensitivity, or an infection. Pain that lasts more than 2 days, disrupts sleep or daily life, comes with swelling or fever, or follows an injury needs dental advice. Trouble breathing or swallowing with swelling is an emergency.", hi: "दांत दर्द कैविटी, टूटे दांत, मसूड़ों की बीमारी या संक्रमण से हो सकता है।", gu: "દાંતનો દુખાવો સડો, તૂટેલા દાંત, પેઢાના રોગ અથવા ચેપથી થઈ શકે છે.", mr: "दातदुखी दात किडणे, तडा जाणे, हिरड्यांचा आजार किंवा संसर्गामुळे होऊ शकते.", es: "El dolor de muelas puede deberse a caries, un diente agrietado, enfermedad de las encías o infección.", ar: "قد ينتج ألم الأسنان عن التسوس أو تشقق السن أو مرض اللثة أو العدوى." },
  content: {
    overview: "Toothache is pain in or around a tooth, gum, or jaw. It can be a short sensitivity to hot, cold, or sweet foods, or a persistent throbbing pain that makes sleep, eating, or work difficult. The underlying cause usually needs a dentist to identify and treat; pain relief can bridge the time to an appointment but cannot repair decay, a crack, or an infection.",
    definition: "Toothache is dental or tooth-related pain. Common sources include decay, damage to a tooth or filling, inflammation of the tooth pulp, gum disease, an erupting tooth, or an infection such as a dental abscess.",
    causes: ["Tooth decay (cavities) exposing sensitive inner tooth layers", "A cracked, broken, loose, or damaged tooth, filling, crown, or other dental restoration", "Gum inflammation or gum disease", "Dental infection or abscess", "Sensitivity from worn enamel or exposed roots", "An erupting wisdom tooth, food trapped between teeth, jaw clenching, or referred pain from the jaw or sinuses"],
    riskFactors: ["Infrequent brushing with fluoride toothpaste or missed dental check-ups", "Frequent sugary food or drink, especially between meals", "Dry mouth, reflux, or medicines that reduce saliva", "Previous fillings, cracks, gum disease, or untreated decay", "Teeth grinding or clenching, and tobacco use"],
    symptoms: ["Sharp, dull, throbbing, or constant pain in a tooth, gum, or jaw", "Sensitivity to hot, cold, sweet foods, or pressure when biting", "Pain when chewing, a bad taste, red gums, or tenderness around a tooth", "Swelling of the gum, cheek, jaw, or face; fever can suggest infection", "Pain that disrupts sleep, eating, speaking, or everyday activities"],
    diagnosis: "A dentist will ask about the timing and triggers of the pain, examine the teeth and gums, and may tap or test teeth for sensitivity. Dental X-rays can help detect decay between teeth, infection around roots, cracks, bone loss, or an impacted tooth. The goal is to identify and treat the cause rather than only suppressing pain.",
    differentialDiagnosis: "Tooth pain can overlap with gum disease, dental abscess, a cracked tooth, sensitivity, jaw-joint pain, sinusitis, migraine, nerve pain, or pain referred from nearby structures. A persistent, severe, or unexplained pain needs dental assessment; facial swelling or infection may need urgent triage.",
    labTests: ["Lab tests are not used for ordinary toothache", "A dentist may use dental X-rays and clinical tests to assess decay, infection, cracks, or gum and bone changes", "A clinician may order blood tests only when a wider infection or non-dental illness is suspected"],
    imaging: "Dental X-rays are commonly used when the cause cannot be seen directly or when the dentist suspects decay, an abscess, a crack, bone loss, or an impacted tooth. More advanced imaging is reserved for selected complex cases.",
    redFlags: ["Toothache lasting more than 2 days, not improving with suitable pain relief, or disrupting sleep, eating, or daily activities", "Fever, worsening cheek or jaw swelling, red gums, a bad taste, trouble opening the mouth, or a suspected dental abscess", "A broken or knocked-out tooth, uncontrolled bleeding, or significant injury to the face or jaw", "Swelling around the eye or neck, or swelling causing trouble breathing, swallowing, speaking, seeing, or opening the mouth—seek emergency help immediately", "Severe weakness, confusion, rapidly spreading swelling, or feeling acutely unwell with dental symptoms"],
    conventionalManagement: "A dentist needs to treat the cause, which may involve cleaning decay, repairing a tooth or restoration, treating gum disease, draining an abscess, root-canal treatment, or extraction where appropriate. While arranging care, a pharmacist can help with pain-relief choices that are safe for you; follow the product label and personal medical advice. Antibiotics are not a substitute for dental treatment and are used only when a clinician decides they are needed.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for toothache, dental infection, or a dental abscess. It must not replace dental assessment, treatment of the cause, or urgent care for swelling, fever, injury, or breathing and swallowing problems.",
    lifestyleAdvice: "Arrange a dental appointment rather than waiting for pain to settle on its own. Until then, choose softer foods, avoid chewing on the sore side, and avoid foods or drinks that trigger sensitivity, such as very hot, cold, or sweet items. Keep brushing gently with fluoride toothpaste; avoid placing aspirin or other substances directly on the gum or tooth. Long term, regular dental care, twice-daily fluoride toothpaste, cleaning between teeth where appropriate, and reducing frequent sugary snacks and drinks help lower risk.",
    references: ["CIT-0115", "CIT-0116"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" }, reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" }, evidenceLevel: "Consensus-Guidance", tags: ["Toothache", "Tooth Pain", "Dental Abscess", "Dental Emergency", "Cavity"], canonicalUrl: "https://homeo.healthcare/knowledge/diseases/toothache", readingTimeMinutes: 5, audience: "patient", license: "CC BY-NC-ND 4.0", changeLog: ["1.0.0: Added patient-first toothache guide with dental urgency and emergency-care boundaries.", "1.1.0: Simplified the title and added focused oral-health connections."], quickFacts: { "Common causes": "Decay, cracks, gum disease, sensitivity, or infection", "Who can treat it": "A dentist identifies and treats the cause", "See a dentist": "If pain lasts more than 2 days or is severe", "Emergency": "Breathing or swallowing difficulty with swelling" },
  aiReadiness: { retrievalSummary: "Toothache has many causes, including decay, a crack, gum disease, sensitivity, and infection. Dental care treats the cause; facial or neck swelling with breathing or swallowing difficulty is an emergency.", clinicalSummary: "Assess duration, severity, thermal and biting triggers, dental trauma, swelling, fever, systemic symptoms, airway or eye involvement, medical history, and access to urgent dental care. Examine and image as clinically indicated.", patientSummary: "Toothache usually needs a dentist to find and treat the cause. Arrange care if it lasts more than 2 days or affects sleep, eating, or daily life; seek emergency help for swelling that affects breathing or swallowing.", studentSummary: "Toothache differential includes caries with pulpal inflammation, cracked tooth, periodontal disease, abscess, hypersensitivity, eruption, TMD, and referred pain. Prioritize airway risk, spreading infection, trauma, and timely definitive dental treatment.", keywords: ["toothache", "tooth pain", "dental abscess", "pain when biting", "swollen cheek tooth pain"], semanticKeywords: ["tooth sensitivity", "dental emergency", "facial swelling toothache", "cavity pain", "urgent dentist"], icd: "K08.89", bodySystem: "Oral Health", urgency: "routine" },
};
