import { KnowledgeEntity } from "../../types";

export const TyphoidFeverDisease: KnowledgeEntity = {
  id: "D0091", slug: "typhoid-fever", entityType: "disease", editorialStatus: "published", reviewStatus: "owner-authorization-required",
  versionInfo: { version: "1.1.0", created: "2026-09-22T00:00:00Z", updated: "2026-09-24T00:00:00Z", reviewed: "2026-09-22T00:00:00Z" },
  title: { en: "Typhoid Fever", hi: "टाइफाइड: लगातार बुखार, जांच, इलाज और बचाव", gu: "ટાઈફોઈડ: સતત તાવ, તપાસ, સારવાર અને બચાવ", mr: "टायफॉइड: सतत ताप, चाचणी, उपचार आणि प्रतिबंध", es: "Tifo: Fiebre Persistente, Pruebas, Tratamiento y Prevención", ar: "التيفوئيد: حمى مستمرة وفحوص وعلاج ووقاية" },
  summary: { en: "Typhoid is a potentially serious bacterial infection usually spread through contaminated food or water. Persistent fever with fatigue, headache, nausea, belly pain, constipation, or diarrhoea needs clinical assessment because it overlaps with many illnesses. Blood testing and clinician-selected antibiotics are important.", hi: "टाइफाइड दूषित भोजन या पानी से फैलने वाला संभावित गंभीर बैक्टीरियल संक्रमण है। लगातार बुखार के साथ थकान, सिरदर्द, मतली, पेट दर्द, कब्ज या दस्त में क्लिनिकल जांच जरूरी है क्योंकि इसके लक्षण कई बीमारियों से मिलते हैं।", gu: "ટાઈફોઈડ દૂષિત ખોરાક અથવા પાણીથી ફેલાતો સંભવિત ગંભીર બેક્ટેરિયલ ચેપ છે. સતત તાવ સાથે થાક, માથાનો દુખાવો, ઊબકા, પેટદર્દ, કબજિયાત અથવા ઝાડામાં ક્લિનિકલ તપાસ જરૂરી છે.", mr: "टायफॉइड हा दूषित अन्न किंवा पाण्यामुळे पसरणारा संभाव्य गंभीर जिवाणूजन्य संसर्ग आहे. सतत ताप, थकवा, डोकेदुखी, मळमळ, पोटदुखी, बद्धकोष्ठता किंवा जुलाब असल्यास तपासणी गरजेची आहे.", es: "El tifo es una infección bacteriana potencialmente grave, generalmente transmitida por alimentos o agua contaminados. La fiebre persistente con cansancio, dolor de cabeza, náuseas, dolor abdominal, estreñimiento o diarrea necesita evaluación clínica.", ar: "التيفوئيد عدوى بكتيرية قد تكون خطيرة تنتقل عادة عبر الطعام أو الماء الملوث. تحتاج الحمى المستمرة مع الإرهاق أو الصداع أو الغثيان أو ألم البطن أو الإمساك أو الإسهال إلى تقييم سريري." },
  content: {
    overview: "Typhoid, also called enteric fever, is a potentially serious infection caused by Salmonella Typhi. It is usually acquired through contaminated food or water. Fever may build over days and occur with fatigue, headache, nausea, belly pain, constipation, diarrhoea, or sometimes a rash. Its symptoms are not specific, so a persistent fever should not be assumed to be typhoid without medical assessment.",
    definition: "A systemic bacterial infection caused by Salmonella Typhi. After entering through the intestinal tract, the bacteria can spread into the bloodstream. Paratyphoid is a similar illness caused by related Salmonella bacteria; a clinician distinguishes them with laboratory testing.",
    causes: ["Ingesting food or water contaminated with Salmonella Typhi", "Exposure where safe water, sanitation, or food hygiene are limited", "Contact with a person who is shedding the bacteria when hand hygiene and food-safety practices break down"],
    riskFactors: ["Living in or travel to an area where typhoid is common", "Limited access to safely treated drinking water and sanitation", "Children and people with limited access to timely medical care", "Eating food or drinking water with uncertain safety"],
    symptoms: ["Persistent or gradually increasing fever, fatigue, headache, chills, or muscle aches", "Nausea, reduced appetite, belly pain, constipation, or diarrhoea", "Occasional faint pink spots on the trunk, though many people will not have a rash", "Symptoms can overlap with malaria, dengue, viral infections, and many other causes of fever"],
    diagnosis: "A clinician considers the symptom pattern, residence or travel, food and water exposures, and examination. Blood culture is a main method to diagnose typhoid; more than one culture may be needed. Stool or urine cultures can sometimes help. Some blood antibody tests can be misleading, so test choice and interpretation should be led by a clinician and local laboratory guidance.",
    differentialDiagnosis: "Malaria, dengue, chikungunya, leptospirosis, viral hepatitis, influenza, COVID-19, gastroenteritis, appendicitis, urinary infections, and other bacterial or viral illnesses can resemble typhoid.",
    labTests: ["Blood culture to identify Salmonella Typhi and, where possible, test antibiotic susceptibility", "Additional blood cultures when a clinician advises", "Stool or urine culture in selected situations", "Blood counts and other tests to assess a persistent fever or possible complications"], imaging: "Imaging is not routinely used to diagnose uncomplicated typhoid. Hospital teams may arrange ultrasound, CT, or other tests if they suspect an abdominal complication or another diagnosis.",
    redFlags: ["Severe or worsening belly pain, swollen or rigid abdomen, black stools, visible blood in stool, or vomiting blood", "Confusion, extreme drowsiness, fainting, breathing difficulty, dehydration, or inability to keep fluids down", "Persistent high fever with worsening weakness, particularly after more than a week of illness", "A young child, pregnancy, older age, reduced immune defenses, or important long-term conditions with persistent fever"],
    conventionalManagement: "Typhoid needs clinician-selected antibiotics; resistance is common, so do not self-start, share, or stop antibiotics early. A clinician may tailor treatment to local resistance patterns and culture results. Take prescribed antibiotics exactly as directed and complete the course unless the prescriber changes it. Rest and fluids support recovery, but urgent hospital care is needed for red flags or complications.",
    homeopathicApproach: "Reliable clinical evidence has not established homeopathy as a treatment for typhoid. It must not replace clinical assessment, blood culture, prescribed antibiotics, hydration, food-safety measures, or urgent treatment for complications.",
    lifestyleAdvice: "Use safe drinking water and food-handling practices: wash hands with soap after using the toilet and before preparing food, eat thoroughly cooked food served hot, and use water known to be safe. While being treated, follow clinician advice about food preparation and follow-up testing; avoid preparing or serving food for others if advised. Ask a clinician or immunization service whether typhoid vaccination is relevant for your age, location, or travel plans.", references: ["CIT-0107", "CIT-0108"],
  },
  author: { name: "Homeo Healthcare Editorial Team", credentials: "Patient Education" }, reviewer: { name: "Dr. Narayan Jethwani", credentials: "MD (Hom)", specialty: "Clinical Governance", institution: "Homeo Healthcare" }, evidenceLevel: "Consensus-Guidance", tags: ["Typhoid", "Enteric Fever", "Persistent Fever", "Food Safety", "Blood Culture"], canonicalUrl: "https://homeo.healthcare/knowledge/diseases/typhoid-fever", readingTimeMinutes: 6, audience: "patient", license: "CC BY-NC-ND 4.0", changeLog: ["1.1.0: Simplified the title and added focused fever and abdominal-pain connections.", "1.0.0: Added patient-first typhoid guide with blood-culture, antibiotic-resistance, and food-safety guidance."], quickFacts: { "Cause": "Salmonella Typhi bacteria", "How it spreads": "Usually contaminated food or water", "Best confirmation": "Blood culture", "Treatment": "Clinician-selected antibiotics; complete the prescribed course" },
  aiReadiness: { retrievalSummary: "Typhoid is a systemic Salmonella Typhi infection, usually spread by contaminated food or water, causing persistent fever and gastrointestinal symptoms. Diagnosis relies on culture and treatment requires clinician-selected antibiotics.", clinicalSummary: "Assess persistent fever, residence/travel, food and water exposure, hydration, abdominal signs, neurologic status, bleeding, pregnancy, age, and immune status. Obtain cultures before or early in treatment where possible; consider resistance patterns and alternate diagnoses.", patientSummary: "Persistent fever with belly symptoms should be assessed rather than treated as typhoid at home. Ask about blood testing and take only prescribed antibiotics for the full advised course. Seek urgent help for severe belly pain, bleeding, confusion, dehydration, or worsening illness.", studentSummary: "Enteric fever is caused by S. Typhi or S. Paratyphi and produces a nonspecific systemic febrile illness. Blood culture is the preferred diagnostic test; resistance patterns guide therapy. Complications include gastrointestinal bleeding, perforation, and encephalopathy.", keywords: ["typhoid", "enteric fever", "persistent fever", "typhoid test", "food water infection"], semanticKeywords: ["Salmonella Typhi", "blood culture", "antibiotic resistance", "foodborne infection", "enteric fever"], icd: "A01.0", bodySystem: "Infectious Disease", urgency: "urgent" },
};
