export type PatientId = string & { readonly __brand: unique symbol };
export type EpisodeId = string & { readonly __brand: unique symbol };
export type AllergyId = string & { readonly __brand: unique symbol };
export type ConsentId = string & { readonly __brand: unique symbol };
export type EncounterId = string & { readonly __brand: unique symbol };
export type OrganizationId = string & { readonly __brand: unique symbol };
export type ClinicId = string & { readonly __brand: unique symbol };
export type PractitionerId = string & { readonly __brand: unique symbol };
export type ConceptId = string & { readonly __brand: unique symbol };
export type PrescriptionId = string & { readonly __brand: unique symbol };
export type AuditLogId = string & { readonly __brand: unique symbol };
export type TimelineEventId = string & { readonly __brand: unique symbol };
export type ConsultationId = string & { readonly __brand: unique symbol };
export type SymptomId = string & { readonly __brand: unique symbol };
export type AssessmentId = string & { readonly __brand: unique symbol };
export type TotalitySymptomId = string & { readonly __brand: unique symbol };
export type SelectedRubricId = string & { readonly __brand: unique symbol };
export type DifferentialReasoningId = string & { readonly __brand: unique symbol };
export type ObstacleId = string & { readonly __brand: unique symbol };
export type RubricId = string & { readonly __brand: unique symbol };

export const toPatientId = (id: string): PatientId => id as PatientId;
export const toEpisodeId = (id: string): EpisodeId => id as EpisodeId;
export const toAllergyId = (id: string): AllergyId => id as AllergyId;
export const toConsentId = (id: string): ConsentId => id as ConsentId;
export const toEncounterId = (id: string): EncounterId => id as EncounterId;
export const toOrganizationId = (id: string): OrganizationId => id as OrganizationId;
export const toClinicId = (id: string): ClinicId => id as ClinicId;
export const toPractitionerId = (id: string): PractitionerId => id as PractitionerId;
export const toConceptId = (id: string): ConceptId => id as ConceptId;
export const toPrescriptionId = (id: string): PrescriptionId => id as PrescriptionId;
export const toAuditLogId = (id: string): AuditLogId => id as AuditLogId;
export const toTimelineEventId = (id: string): TimelineEventId => id as TimelineEventId;
export const toConsultationId = (id: string): ConsultationId => id as ConsultationId;
export const toSymptomId = (id: string): SymptomId => id as SymptomId;
export const toAssessmentId = (id: string): AssessmentId => id as AssessmentId;
export const toTotalitySymptomId = (id: string): TotalitySymptomId => id as TotalitySymptomId;
export const toSelectedRubricId = (id: string): SelectedRubricId => id as SelectedRubricId;
export const toDifferentialReasoningId = (id: string): DifferentialReasoningId => id as DifferentialReasoningId;
export const toObstacleId = (id: string): ObstacleId => id as ObstacleId;
export const toRubricId = (id: string): RubricId => id as RubricId;
